"""Plain-English meaning + an everyday example for every card's quote, in card order.
Shown when a reader taps a quote. Keep each line short and modern."""

M = {
"prince": [
 ("To see ordinary people clearly you need a ruler's distance; to see rulers clearly you need to be ordinary.", "Your manager can't see what the team really thinks, and the team can't see the pressure the manager is under."),
 ("You often see something big best from far below it, not from on top of it.", "The new intern spots the confusing parts of an app that the people who built it no longer notice."),
 ("Every government is either run by citizens (a republic) or by one ruler (a principality).", "A cricket club run by votes of all members versus one run by the owner alone."),
 ("A ruler who inherits power has fewer reasons to hurt people, so people like him more.", "The boss's daughter who grew up in the family firm doesn't need to prove herself by firing anyone."),
 ("People happily swap leaders because they hope the new one will make life better.", "Voters switch parties each election, hoping this time prices will fall."),
 ("Either treat people well or remove their power completely; a small injury just makes them want revenge.", "Half-criticising a coworker in public makes an enemy who can still hurt you."),
 ("Whoever helps someone else rise to power usually gets dropped by them later.", "The friend who introduced you to the startup gets edged out once you're the CEO."),
 ("Countries have been governed in two main ways.", "Some offices have one boss and assistants; others have a boss plus powerful department heads."),
 ("People who once lived free never stop resenting a new master; the memory of freedom stays.", "A team that used to set its own hours will grumble for years about a strict new schedule."),
 ("Copy the habits of the greatest people in your field.", "A young cook practises the recipes of master chefs before inventing her own."),
 ("Changing how things are done is the hardest, riskiest job there is.", "Switching a whole office to new software meets complaints from everyone used to the old one."),
 ("Ideas backed by real power win; ideas without power get crushed.", "A good proposal with no sponsor dies in the meeting; the same idea from the director passes."),
 ("Luck can lift you up easily, but keeping your place after luck is hard.", "A viral video makes someone famous overnight; staying popular takes real work."),
 ("The cruel display left the people both relieved and frightened.", "When the bullying manager is fired publicly, staff feel both glad and nervous."),
 ("New favours don't make powerful people forget old wrongs you did them.", "Buying your sister a gift won't make her forget you read her diary."),
 ("Killing and betraying can win power, but never real respect or glory.", "A cheater may win the tournament, but no one admires the trophy."),
 ("Do the painful things all at once, and give good things slowly so they're enjoyed longer.", "Rip the bandage off quickly; hand out the holiday bonus in two parts."),
 ("The powerful want to control and squeeze ordinary people.", "Big landlords push rents up whenever they can."),
 ("A leader needs ordinary people on his side, or he has no safety in hard times.", "A captain loved by the players is backed when results go badly."),
 ("A well-defended place whose ruler isn't hated rarely gets attacked.", "A shop with good locks and friendly neighbours is seldom robbed."),
 ("Church states are won by skill or luck but held by tradition alone.", "An old family temple keeps its trust for centuries without anyone campaigning."),
 ("Every state stands on good laws and a strong defence.", "A school needs both fair rules and teachers who enforce them."),
 ("Hired soldiers love the pay in peacetime and vanish when real fighting starts.", "Fair-weather friends are around for parties but busy when you need to move house."),
 ("A wise leader relies on his own people, not borrowed or hired help.", "A shop owner trains her own staff instead of depending on temp agencies."),
 ("Borrowed help either fails you, burdens you or controls you.", "A loan from a pushy relative comes with endless opinions on how you spend it."),
 ("A ruler must think about defence above everything else.", "A business owner should always think about competitors, even in a good year."),
 ("Real life is very different from how life should be; ignoring that ruins you.", "Plans built on 'everyone will be on time' fall apart in real traffic."),
 ("To survive, a leader must know how to do wrong and use it only when needed.", "A good negotiator knows the tricks even if they rarely use them."),
 ("Spending freely to look generous quickly drains you.", "Paying for everyone's dinner every week empties your wallet fast."),
 ("Above all avoid being hated or looked down on; showy generosity leads to both.", "The boss who hands out favours, then cuts them, ends up resented."),
 ("A ruler who keeps people safe and united shouldn't worry about being called harsh.", "A strict teacher whose class does well is respected, even if called tough."),
 ("If you can't have both, it's safer to be feared than loved.", "Students obey the strict teacher's deadline more reliably than the friendly one's."),
 ("People forgive a death sooner than the loss of their property.", "Families fight longer over an inheritance than over the funeral."),
 ("Be clever like a fox to spot traps, and strong like a lion to scare off enemies.", "Read the contract's fine print, and also have the confidence to walk away."),
 ("A smart leader needn't keep a promise that would now harm him.", "A business drops a deal when the partner has already broken their side."),
 ("Everyone sees your image; very few know who you really are.", "Social media shows the holiday photos, not the arguments."),
 ("People judge by what they see, not by what they can touch or test.", "A nicely packaged product sells better than a better product in a plain box."),
 ("Being changeable, silly or indecisive makes people look down on you.", "A leader who changes the plan every day loses the team's respect."),
 ("The best protection against plots is not being hated by ordinary people.", "A well-liked manager hears about trouble before it starts."),
 ("Let others deliver bad news; keep the pleasant tasks for yourself.", "The CEO announces bonuses; HR announces the layoffs."),
 ("The best defence is not being hated by your own people.", "A shop owner liked by the street has neighbours who watch the shop."),
 ("Nothing earns respect like big achievements and setting an example.", "The team respects the captain who scored the winning goal."),
 ("Leaders who can't decide stay neutral to avoid trouble, and usually lose anyway.", "The friend who won't take a side in a fight ends up trusted by neither."),
 ("You judge a leader first by the people they keep around them.", "You can tell a lot about a startup founder from who they hire."),
 ("The only defence against flatterers is letting people know honesty won't anger you.", "A good boss says 'tell me the bad news first' and means it."),
 ("Good advice only helps a leader who is wise enough to recognise it.", "A great coach's tips are wasted on a player who won't listen."),
 ("People rarely prepare for bad times while things are calm.", "Nobody saves an emergency fund until the car breaks down."),
 ("Luck controls about half of what happens to us; the rest is up to us.", "You can't control the exam questions, but you can control how much you study."),
 ("Success comes to those who act in a way that suits the times.", "Shops that started selling online early did well when the lockdowns came."),
 ("Taking a bold risk is usually better than being too careful.", "Applying for the job you're not sure you'll get beats never applying."),
 ("Everyone is sick of this foreign domination.", "The whole neighbourhood is fed up with the noisy factory and wants change."),
 ("Courage will win against blind rage.", "A calm team beats an angry one that keeps getting yellow cards."),
],
"laws": [
 ("Beating your boss creates hatred; it is foolish or even disastrous.", "Correcting your manager in front of the client may cost you the next promotion."),
 ("A smart person learns more from enemies than a fool from friends.", "A harsh online review often teaches a café more than its friends' praise."),
 ("Showing all your plans at once is pointless and boring.", "Announcing your job search to the whole office before you have an offer."),
 ("Careful silence is the deepest form of practical wisdom.", "In a negotiation, the one who stays quiet longer usually gets the better deal."),
 ("Once a mocking nickname sticks, your reputation is in danger.", "A teacher nicknamed 'Snore' struggles to be taken seriously by new classes."),
 ("Keep showing something new and surprising, like a sunrise every day.", "Creators who post fresh content keep their audience; those who repeat lose it."),
 ("You can look wise by using the hard work of others.", "A manager presents the team's research and gets the applause."),
 ("A clever fighter makes the enemy follow his plan, never the other way round.", "Choose the meeting place and time yourself instead of fitting someone else's."),
 ("Disagreeing with people's opinions feels like an insult to them.", "Telling a friend their favourite film is bad starts an argument, not a discussion."),
 ("Bad luck often comes from foolishness, and it spreads to those close by.", "Hanging around a friend who always gets in trouble drags you into trouble too."),
 ("A wise person prefers to be needed rather than merely thanked.", "The only person who knows the server password is never let go."),
 ("Give good things little by little so they are appreciated longer.", "A series that releases one episode a week keeps viewers talking longer."),
 ("Self-interest can pretend to be anything, even generosity.", "A 'free' webinar that ends with a sales pitch."),
 ("Wise leaders win because they know what will happen before it happens.", "Checking the weather before a trip saves you from being caught in the rain."),
 ("Either treat people well or remove their power to strike back.", "If you must report a bully, report everything at once, not one small thing."),
 ("Move away from where you shine so people miss you.", "A singer who takes a year off returns to bigger crowds."),
 ("Don't always act the same way, so rivals can't predict you.", "A footballer who doesn't always shoot the same way keeps keepers guessing."),
 ("The safest defence is to not be hated by ordinary people.", "A landlord who treats tenants fairly rarely has trouble collecting rent."),
 ("Know your rival and yourself, and you need not fear any contest.", "Study the other team's tactics and your own weaknesses before the final."),
 ("Stay free of any single group, trend or era.", "Don't let one client become your only source of income."),
 ("Sometimes the wisest move is to look less clever than you are.", "Letting the know-it-all explain something you already understand, to keep the peace."),
 ("Pretend to be weak so your opponent becomes overconfident.", "Act unsure at the start of a chess game so your rival plays carelessly."),
 ("Stay united while forcing the other side to split up.", "A team that sticks together while the other team argues wins the match."),
 ("Respect others if you want respect back.", "Greet the security guard by name and they'll help you when you forget your badge."),
 ("Refresh your talents and image, like a phoenix rising again.", "An old brand redesigns its logo and suddenly feels new again."),
 ("Let others do the unpopular tasks; keep the pleasant ones yourself.", "The principal announces the trip; the vice-principal handles the detentions."),
 ("Most people are won over by appearances and results.", "Crowds trust the fancy-looking shop more than the plain one next door."),
 ("Taking bold risks usually beats being too cautious.", "The person who speaks first in the meeting sets the agenda."),
 ("The winner plans the victory before the fight; the loser fights hoping to win.", "Plan your route and parking before the job interview, not on the way."),
 ("A clever fighter wins, and wins easily.", "The best students make exams look easy because they prepared for months."),
 ("Offer something attractive so the other side comes to you willingly.", "A shop's free samples draw people in without any advertising."),
 ("Anyone who wants to deceive will always find someone ready to believe.", "Scam messages work because a few people always click."),
 ("Learn what drives each person; that is how you move them.", "One colleague wants praise, another wants time off — reward each differently."),
 ("Act with dignity, as if you were royalty, whatever your rank.", "A waiter who carries himself with pride gets more respect than a sloppy manager."),
 ("Patience and time can beat any two opponents.", "Waiting for a sale instead of buying at full price."),
 ("Foolish people look down on everyone.", "A troll mocking everything online shows only their own emptiness."),
 ("Big projects and good examples earn the most respect.", "A mayor who builds a bridge is remembered more than one who gives speeches."),
 ("Think freely with a few trusted people; talk like everyone else in public.", "Share your wild business idea with close friends, not the whole family WhatsApp."),
 ("If your opponent is short-tempered, provoke him so he makes mistakes.", "Trash talk in sport is meant to make the other player lose focus."),
 ("Things that cost nothing are usually worth little.", "The free gym trial nobody uses versus the paid membership people actually go to."),
 ("It's no honour if you only look good because a weak successor follows you.", "A coach who leaves a team in chaos isn't great just because the next coach is worse."),
 ("Take what your opponent values most, and he will do what you want.", "Hold the TV remote and the whole family listens to your plan."),
 ("A leader needs the people on his side or he has no safety in bad times.", "A brand loved by its customers survives a bad product launch."),
 ("Win by carefully adapting to what the other side is trying to do.", "A good salesperson mirrors the customer's pace and style."),
 ("Introducing a new way of doing things is the hardest, riskiest task.", "Changing the family's holiday tradition meets more resistance than you'd expect."),
 ("Allow yourself a small harmless flaw; it makes your talent less threatening.", "The brilliant new colleague who admits she can't park is liked more."),
 ("Quit while you're winning; a good retreat is as good as a bold attack.", "Leave the casino after a win instead of betting it all again."),
 ("Be flexible like water, flowing around obstacles.", "When a road is blocked, a good driver takes side streets instead of waiting."),
],
"artofwar": [
 ("War is the most serious thing a country does.", "Starting a lawsuit is a big decision — think hard before you do it."),
 ("Every war depends on tricking the enemy.", "Poker players hide their real hand with a calm face."),
 ("In conflict, aim to win quickly, not to drag things out.", "Settle a dispute with a neighbour fast before it becomes a years-long feud."),
 ("No country has ever gained from a long war.", "A long divorce case leaves both sides poorer; only the lawyers gain."),
 ("The best victory is breaking the other side's will without fighting.", "Winning a deal because your offer is so good the rival gives up."),
 ("Know your opponent and yourself, and you won't fear any contest.", "Before a debate, learn the other side's points and your own weak spots."),
 ("First make yourself impossible to beat, then wait for the enemy's mistake.", "Save money and build skills, then pounce when a great job opens."),
 ("Winners set up the win before the fight; losers fight first and hope.", "Students who revised early walk into the exam already confident."),
 ("There are only direct and indirect attacks, but they combine endlessly.", "In football, the plain pass and the surprise trick play mix into countless moves."),
 ("A charging army is like a torrent that rolls stones along.", "Once a sale becomes a trend, it sells itself like a snowball."),
 ("A clever fighter controls the situation and never lets the enemy control him.", "Set the meeting agenda yourself instead of reacting to someone else's."),
 ("Tactics should be like water: avoid the high, strong points, flow to the weak ones.", "A new café opens where there's no coffee shop, not next to a famous one."),
 ("Keep your plans dark as night, then strike fast like lightning.", "Work quietly on your project, then launch it all at once."),
 ("When you surround an enemy, leave them a way out.", "In an argument, let the other person save face so they don't fight to the end."),
 ("Some roads should not be taken.", "Not every job offer or deal is worth accepting."),
 ("Rashness leads to ruin.", "Quitting your job in anger, without a plan, often ends badly."),
 ("Polite words plus quiet preparations mean the enemy is about to attack.", "A suddenly super-friendly rival may be planning something."),
 ("Treat soldiers kindly first, but keep firm discipline.", "A good teacher is warm with students but still enforces deadlines."),
 ("Know the enemy and yourself, and victory is certain.", "A shop that knows its customers and its own strengths rarely fails."),
 ("Care for your soldiers like children, and they'll follow you anywhere.", "A manager who protects the team gets loyal staff."),
 ("Put soldiers where there's no escape and they will fight with everything.", "Burning your bridges — like announcing a launch date — forces you to finish."),
 ("Seize what your opponent values most, and he will do as you say.", "A child who hides the TV remote suddenly has everyone's attention."),
 ("Act only when there's real advantage; fight only when you must.", "Don't argue in the group chat unless something important is at stake."),
 ("Never go to war out of anger or wounded pride.", "Don't send that angry email at midnight."),
 ("Wise leaders win because they know things in advance.", "A trader who reads the news early acts before others."),
 ("That is why spies are used — and there are five kinds.", "Companies research rivals through customers, ex-staff and public reports."),
],
"gita": [
 ("The blind king asks Sanjaya what happened when the two armies met at Kurukshetra.", "Like asking a friend at the stadium for live updates of the match."),
 ("Arjuna is lost in pity and doubt and turns to Krishna for advice.", "Before a big decision, you call the one person you trust most."),
 ("You are sad about something that isn't truly worth grieving.", "Crying over a lost phone when your family is safe at home."),
 ("The soul was never born and will never die; beginnings and endings are like dreams.", "People change and age, but the person you love stays the same inside."),
 ("Do the right thing for its own sake, not for the reward.", "Study to learn, not just for marks — and the marks often follow."),
 ("A wise person pulls back the senses from distractions, like a tortoise pulls in its legs.", "Putting your phone in a drawer while you study."),
 ("Doing your work is better than doing nothing.", "Even a small walk beats a whole day on the sofa."),
 ("Do your own task, even imperfectly, rather than someone else's.", "Be a good version of yourself instead of copying a cousin's career."),
 ("Whenever goodness fades and evil grows, God comes to restore what is right.", "When things go wrong in a community, someone always rises to set them right."),
 ("Knowledge burns away the bad effects of past actions, like fire burns wood to ash.", "Understanding why you made a mistake frees you from repeating it."),
 ("A true renouncer wants nothing and rejects nothing and stays steady.", "A calm person accepts both a pay rise and a setback without losing balance."),
 ("Lift yourself up by your own effort; you can be your own best friend or worst enemy.", "Your own habits can build you up — or pull you down."),
 ("A steady mind is like a lamp flame in a windless place.", "During exams, a calm mind keeps its focus despite the noise."),
 ("Earth, water, fire, air, space, mind and ego make up the visible world.", "Everything you see, from mountains to moods, is made of these building blocks."),
 ("Keep God in your heart always, and do your duty.", "A doctor prays, then goes into surgery and does her best."),
 ("Even a leaf, flower, fruit or water, offered with love, is accepted.", "A handmade card from a child means more than an expensive gift."),
 ("With the lamp of wisdom, God removes the darkness of ignorance.", "A good teacher's explanation suddenly makes a confusing topic clear."),
 ("Krishna reveals himself as Time, which destroys everything.", "Time eventually wears down even the strongest buildings and empires."),
 ("The person dear to God hates no living being, is kind, and free of pride.", "A neighbour who helps everyone without boasting about it."),
 ("Humility, honesty, non-violence, patience and respect for the wise mark true knowledge.", "The smartest people you meet are often the most modest."),
 ("Nature has three qualities: goodness, passion and dullness.", "A calm morning, a stressful rush hour and a lazy afternoon — all three in one day."),
 ("The world is like an upside-down tree with roots above and branches below.", "Your actions branch out from deep, hidden roots — your desires."),
 ("A good person is truthful, slow to anger, and lets go of what others cling to.", "Not fighting over the last slice of pizza."),
 ("Each person's faith matches their true nature.", "A patient person is drawn to quiet prayer; an energetic one to festivals."),
 ("Make God your only refuge; you will be freed from all sins — do not worry.", "Handing over a worry to someone you completely trust, and finally sleeping well."),
],
}


def apply(book_id, cards):
    rows = M.get(book_id)
    if rows is None:
        return
    assert len(rows) == len(cards), f"{book_id}: {len(rows)} meanings for {len(cards)} cards"
    for c, (mean, life) in zip(cards, rows):
        c["qMean"], c["qLife"] = mean, life
