"""Bindery shelves filled + Indian Wisdom shelf. Run: python3 shelf4_content.py"""
import folio_build
from folio_build import build, SOURCES
from shelf2_content import C

SOURCES.update({
    "speaking": ("speaking.txt", "J. B. Esenwein & Dale Carnegie, The Art of Public Speaking (1915)"),
    "franklin": ("franklin.txt", "Benjamin Franklin, Autobiography (1791)"),
    "chesterfield": ("chesterfield.txt", "Lord Chesterfield, Letters to His Son (1774)"),
    "onwar": ("onwar.txt", "Carl von Clausewitz, On War (tr. Graham, 1873)"),
    "livy": ("livy.txt", "Niccolò Machiavelli, Discourses on Livy (tr. Thomson, 1883)"),
    "republic": ("republic.txt", "Plato, The Republic (tr. Jowett)"),
    "ovid": ("ovid.txt", "Ovid, The Art of Love (tr. Riley, 1885)"),
    "emerson": ("emerson.txt", "Ralph Waldo Emerson, Essays: First Series (1841)"),
    "seneca": ("seneca.txt", "Seneca, On the Shortness of Life (tr. Stewart, 1889)"),
    "pancha": ("panchatantra.txt", "The Panchatantra (tr. Arthur W. Ryder, 1925)"),
    "hito": ("hitopadesa.txt", "The Hitopadesha (tr. Edwin Arnold)"),
    "kural": ("kural.txt", "Tiruvalluvar, The Kural (tr. V. V. S. Aiyar, 1916)"),
})
folio_build.OCR.update({"kural", "pancha"})
BOOKS = []
def B(about, gl, src, rows):
    BOOKS.append((dict(about, self_src=src), gl, C(src, rows)))

# ------------------------------------------------ Persuasion & Rhetoric
B(dict(id="speaking", title="The Art of Public Speaking", short="Esenwein & Carnegie", author="J. Berg Esenwein & Dale Carnegie", year="1915",
       translator="Original text (public domain, Project Gutenberg #16317)", era="modern", shelf="Persuasion & Rhetoric",
       blurb="Dale Carnegie's first book, written before How to Win Friends: beating stage fright, killing monotony, and speaking so people listen."),
  {"monotony": ("Boring sameness, with no change.", "The monotony of the long drive made him sleepy.", []),
   "self-confidence": ("Trust in your own abilities.", "Practice gave her the self-confidence to sing on stage.", []),
   "audience": ("The people watching or listening.", "The audience laughed at the first joke.", [])},
  "speaking", [
  ("Chapter I", "Acquiring Confidence", "Everyone gets stage fright",
   "The book opens with the question every beginner asks: how do I stop being afraid in front of people? The authors promise it can be learned.",
   "the fear that paralyzes me before an audience",
   "The fear that freezes you when everyone is watching.", "Your mind going blank during a class presentation."),
  ("Chapter I", "Acquiring Confidence", "Be like the calm horses",
   "From a train window you see some horses bolt at the noise and others keep grazing, used to it. Speakers grow calm the same way — by facing audiences again and again.",
   "some horses feed near the track and never even pause to look up at the thundering cars",
   "Repeated exposure makes frightening things ordinary.", "After ten presentations, the eleventh barely scares you."),
  ("Chapter I", "Acquiring Confidence", "Confidence needs content",
   "You can't fake confidence. Know your subject so well that you have something real to be confident about.",
   "to acquire self-confidence you must have something in which to be confident.",
   "Real confidence comes from being well prepared.", "Knowing your project inside out before the client meeting."),
  ("Chapter II", "The Sin of Monotony", "Don't drone",
   "The deadliest fault in speaking is monotony — the same tone, pace and pitch. Vary them and people stay awake.",
   "the nature--and the curse--of monotony",
   "Speaking in one flat tone ruins a talk.", "A lecturer who reads slides in the same voice for an hour."),
  ("Chapter III", "Efficiency through Emphasis", "Be natural — by practice",
   "Telling someone to 'be natural' doesn't help. Natural speaking is built by copying what good speakers do until it becomes your own.",
   "It is useless to warn the student that he must be natural.",
   "Just saying 'be natural' doesn't make anyone natural.", "Rehearsing a toast many times so it sounds effortless."),
])

B(dict(id="franklin", title="The Autobiography", short="Benjamin Franklin", author="Benjamin Franklin", year="1791",
       translator="Original text (public domain, Project Gutenberg #20203)", era="enlightenment", shelf="Persuasion & Rhetoric",
       blurb="How a runaway printer's apprentice became one of history's great persuaders — by never arguing, keeping a little book of virtues, and asking favours."),
  {"contradiction": ("Saying the opposite of what someone said.", "Her blunt contradiction annoyed the speaker.", []),
   "obliged": ("Did a favour for someone.", "You obliged me by driving me home.", []),
   "industry": ("Hard, steady work.", "Through industry she paid off her loan early.", []),
   "virtues": ("Good qualities of character.", "Patience and honesty are virtues.", [])},
  "franklin", [
  ("Part I", "The Humble Inquirer", "Stop winning arguments",
   "As a young man Franklin loved debating and crushing people. He noticed it made enemies. So he switched to asking modest questions instead — and persuaded far more people.",
   "put on the humble inquirer and doubter",
   "Instead of arguing, ask questions like someone curious.", "'Have you thought about…?' works better than 'You're wrong.'"),
  ("Part II", "No Direct Contradiction", "Never say 'you're wrong'",
   "Franklin banned himself from flat contradiction and from words like 'certainly'. He said 'I imagine' or 'it appears to me' — and people stopped resisting his ideas.",
   "I made it a rule to forbear all direct contradiction to the sentiments of others, and all positive assertion of my own.",
   "Don't bluntly contradict people or insist you're right.", "Saying 'I might be wrong, but…' before a suggestion."),
  ("Part II", "The Favour Trick", "Ask for a favour",
   "To win over a hostile rival, Franklin asked to borrow a rare book. The man lent it, and became a lifelong friend. People like those they've helped — now called the 'Ben Franklin effect'.",
   "He that has once done you a kindness will be more ready to do you another, than he whom you yourself have obliged.",
   "Someone who helped you once is more likely to help again than someone you helped.", "Asking a cold colleague for advice often warms them up."),
  ("Part II", "Thirteen Virtues", "A little book of habits",
   "Franklin listed thirteen virtues and kept a small book with a page for each, marking his slips every day. A habit tracker, 250 years early.",
   "I made a little book, in which I allotted a page for each of the virtues.",
   "He tracked his habits daily in a notebook.", "Ticking off 'no sugar' days on a calendar."),
  ("Part II", "Thirteen Virtues", "Lose no time",
   "His sixth virtue, Industry: never waste time, always be doing something useful, and cut out what isn't needed.",
   "Lose no time; be always employ'd in something useful; cut off all unnecessary actions.",
   "Don't waste time; keep doing useful things.", "Listening to an audiobook during your commute."),
  ("Part II", "Thirteen Virtues", "Speak usefully",
   "His second virtue, Silence: only say what helps others or yourself, and skip empty chatter.",
   "Speak not but what may benefit others or yourself; avoid trifling conversation.",
   "Only say things that are helpful.", "Skipping office gossip and talking about real work."),
])

B(dict(id="chesterfield", title="Letters to His Son", short="Lord Chesterfield", author="Philip Stanhope, Lord Chesterfield", year="1774",
       translator="Original text (public domain, Project Gutenberg #3361)", era="enlightenment", shelf="Persuasion & Rhetoric",
       blurb="A worldly English lord's private letters to his son on charm, manners, attention and getting on in society — the 18th century's guide to being liked."),
  {"procrastination": ("Putting things off until later.", "Procrastination left him writing the essay at midnight.", []),
   "resent": ("Feel bitter or annoyed about.", "She resented being left out of the plan.", []),
   "attention": ("Careful focus on something.", "Give the recipe your full attention.", []),
   "learning": ("Knowledge gained by study.", "Her learning showed in every answer.", [])},
  "chesterfield", [
  ("Letter", "On Learning", "Hide your watch",
   "Don't show off your knowledge. Keep it like a watch in your pocket: bring it out when someone asks the time, not every minute to show you own one.",
   "Wear your learning, like your watch, in a private pocket",
   "Don't show off what you know.", "Answering a question simply instead of lecturing about it."),
  ("Letter", "On Company", "Don't seem wiser",
   "Never try to look smarter or more educated than the people you're with. It makes them resent you.",
   "Never seem wiser, nor more learned, than the people you are with.",
   "Don't act cleverer than the people around you.", "Not correcting a friend's grammar at dinner."),
  ("Letter", "On Attention", "Do it well or not at all",
   "Whatever is worth doing is worth doing well, and nothing is done well without attention — even dancing and dressing.",
   "ver is worth doing at all, is worth doing well",
   "If something is worth doing, do it properly.", "Writing a thank-you note carefully, not in five seconds."),
  ("Letter", "On Time", "Seize every moment",
   "Know what time is worth; use every moment. No laziness, no putting off till tomorrow what you can do today.",
   "Know the true value of time; snatch, seize, and enjoy every moment of it.",
   "Value your time and use it fully.", "Finishing a small task now instead of adding it to tomorrow's list."),
  ("Letter", "On Pleasing", "The art of pleasing",
   "Being liked is a skill — necessary and hard. It can't be fully reduced to rules; watch people and learn.",
   "The art of pleasing is a very necessary one to possess; but a very difficult one to acquire.",
   "Being pleasant to others is important but hard to learn.", "Noticing what makes a colleague smile and doing more of it."),
  ("Letter", "On Truth", "Fools lie most",
   "In his experience the biggest fools are the biggest liars; he judges people's honesty by their intelligence.",
   "the greatest fools are the greatest liars.",
   "The most foolish people tend to lie the most.", "The friend with wild excuses is rarely the sharpest."),
])

# ------------------------------------------------ War & Statecraft
B(dict(id="onwar", title="On War", short="Clausewitz", author="Carl von Clausewitz", year="1832",
       translator="J. J. Graham, 1873 (public domain, Project Gutenberg #1946)", era="germanic", shelf="War & Statecraft",
       blurb="A Prussian general's deep study of war: a duel, a gamble, a fog — and always the servant of politics."),
  {"friction": ("Small difficulties that make simple things hard.", "Traffic, rain and a missed call added friction to the move.", []),
   "policy": ("A government's plan or aim.", "The new policy cut school fees.", []),
   "duel": ("A fight between two people.", "The chess final was a duel of minds.", [])},
  "onwar", [
  ("Book I", "What Is War?", "A duel on a large scale",
   "Clausewitz begins simply: war is two wrestlers, each trying to throw the other and make him do what he wants.",
   "War is nothing but a duel on an extensive scale.",
   "War is like a fight between two people, but huge.", "Two companies fighting for the same market share."),
  ("Book I", "War and Politics", "Politics by other means",
   "His most famous idea: war is never its own purpose. It continues a country's political aims with other tools.",
   "ntinuation of State policy by other means",
   "War is politics carried on with force.", "A trade war is economics used to win a political argument."),
  ("Book I", "Friction", "Everything is simple — and hard",
   "On paper war looks simple. In reality, tiny problems pile up — tired horses, wrong reports, rain — and the simplest action becomes hard. He calls it friction.",
   "s very simple in War, but the simplest thing is difficult.",
   "Plans look easy, but small problems make them hard.", "A simple house move becomes chaos when the van is late."),
  ("Book I", "Friction", "The fog of war",
   "Weather and chance cloud every decision: fog hides the enemy, rain delays a battalion. A general must act without full information.",
   "the fog prevents the enemy from being discovered in time",
   "You often must decide without seeing everything clearly.", "Launching a product without knowing exactly how customers will react."),
])

B(dict(id="livy", title="Discourses on Livy", short="Machiavelli", author="Niccolò Machiavelli", year="1531",
       translator="Ninian Hill Thomson, 1883 (public domain, Project Gutenberg #10827)", era="renaissance", shelf="War & Statecraft",
       blurb="The other Machiavelli: a love letter to republics, arguing that free peoples are wiser and steadier than princes."),
  {"commonwealth": ("A state governed for the common good.", "The town ran itself like a small commonwealth.", []),
   "prudent": ("Careful and sensible.", "A prudent driver slows down in rain.", []),
   "inclinations": ("Natural tendencies or likings.", "His inclinations lean towards music.", [])},
  "livy", [
  ("Book I", "Founders and Laws", "Assume the worst",
   "Anyone founding a state must write laws as if people will misbehave when given the chance — not because everyone is evil, but because good laws must hold even when they are.",
   "all men are bad, and will always, when they have free field, give loose to their evil inclinations",
   "Design rules assuming people will misuse freedom.", "Apps add two-step login because some people will try to break in."),
  ("Book I", "The People", "The people are wiser",
   "Surprising from the author of The Prince: a people, he argues, is more prudent, more stable and has better judgement than a prince.",
   "a people is more prudent, more stable, and of better judgment than a prince.",
   "Ordinary people together judge better than a single ruler.", "A team vote often beats the boss's hunch."),
  ("Book I", "Succession", "Plan for the next leader",
   "Good states don't depend on one great ruler; they arrange a steady succession of able ones.",
   "in every well ordered commonwealth provision will be made for a succession of this sort.",
   "Well-run places plan who leads next.", "A family business training the next generation early."),
])

B(dict(id="republic", title="The Republic", short="Plato", author="Plato", year="c. 375 BC",
       translator="Benjamin Jowett (public domain, Project Gutenberg #1497)", era="ancient", shelf="War & Statecraft",
       blurb="Socrates asks what justice is — and imagines a whole city to find out. Home of the cave, the ring of invisibility and the philosopher-king."),
  {"justice": ("Fairness; giving each what is right.", "Justice was served when the thief returned the bike.", []),
   "philosophers": ("Lovers of wisdom; deep thinkers.", "Philosophers argue about what makes life good.", []),
   "den": ("A cave or hidden room.", "The bear slept in its den.", [])},
  "republic", [
  ("Book I", "Thrasymachus", "Might is right?",
   "A brash teacher, Thrasymachus, claims justice is just whatever benefits the strong. Socrates spends the whole book proving him wrong.",
   "justice the interest of the stronger",
   "Some argue 'justice' is just what helps the powerful.", "When rules seem written to protect the rich."),
  ("Book II", "The Ring of Gyges", "If no one could see you",
   "A shepherd finds a ring that makes him invisible — and uses it for crime. Would anyone stay good if they could never be caught?",
   "every one will do evil if he can.",
   "Some say everyone would do wrong if they couldn't be caught.", "Would you return extra change if no one would ever know?"),
  ("Book II", "Education", "Beginnings matter most",
   "Childhood shapes character more than anything later, so what children hear and see must be chosen with care.",
   "the beginning is the most important part of any work",
   "The start of anything matters most.", "Good habits learned young last a lifetime."),
  ("Book V", "Philosopher-Kings", "Wise rulers",
   "Plato's boldest claim: cities will have no rest from trouble until philosophers rule or rulers become philosophers.",
   "philosophers are kings",
   "Leaders should be truly wise people.", "Wishing your city's mayor were an expert, not a celebrity."),
  ("Book VII", "The Cave", "The cave",
   "Prisoners chained in a cave see only shadows on a wall and think that is reality. One escapes into sunlight — and when he returns, no one believes him.",
   "human beings living in an underground den which is open towards the light",
   "Most people mistake shadows for reality.", "Believing social-media highlights are what people's lives are really like."),
])

# ------------------------------------------------ Love & Human Nature
B(dict(id="ovid", title="The Art of Love", short="Ovid", author="Ovid", year="c. 2 AD",
       translator="Henry T. Riley, 1885 (public domain, Project Gutenberg #47677)", era="ancient", shelf="Love & Human Nature",
       blurb="Rome's cheekiest poet writes a mock-serious handbook on romance — so popular, and so naughty, that the emperor exiled him."),
  {"compliments": ("Words of praise.", "He paid her compliments on her cooking.", []),
   "fair": ("(Old use) a beautiful woman; the beloved.", "Poets wrote endless songs to the fair.", [])},
  "ovid", [
  ("Book I", "The Plan", "Love as a campaign",
   "Ovid jokes that a lover is like a new soldier: first find someone to love, then win them by pleasing, then make the love last.",
   "are now coming for the first time to engage as a soldier in a new service.",
   "Starting a romance is like signing up for a new campaign.", "Planning a first date like a careful project."),
  ("Book I", "Winning Hearts", "Please first",
   "The second task, he says, is simply to please — kindness and attention come before any grand gesture.",
   "The next task after that, is to prevail on the fair by pleasing her.",
   "The next step is to win them over by being pleasant.", "Remembering someone's favourite tea before trying to impress them."),
  ("Book I", "Letters", "Write it down",
   "Ovid advises sending letters full of compliments — words reach where you cannot.",
   "Let it carry your compliments",
   "Let your message carry your praise.", "A thoughtful text after a first meeting."),
  ("Book I", "Grooming", "Don't overdo it",
   "He tells men not to fuss too much over looks; heroes of myth won hearts without curling their hair.",
   "A neglect of beauty becomes men",
   "Men don't need to over-groom to be attractive.", "Clean and simple beats ten hair products."),
  ("Book I", "Promises", "The danger of easy promises",
   "Ovid cheekily says lovers promise everything — and the gods laugh at lovers' broken vows. Read it as satire: two thousand years ago, people already knew sweet talk is cheap.",
   "promises attract the fair",
   "Promises are attractive — which is why they're easily made.", "Be wary of someone who promises the moon on day one."),
])

B(dict(id="emerson", title="Self-Reliance & Other Essays", short="Emerson", author="Ralph Waldo Emerson", year="1841",
       translator="From Essays: First Series (public domain, Project Gutenberg #2944)", era="victorian", shelf="Love & Human Nature",
       blurb="America's great essayist on trusting yourself, on love, and on friendship — short, quotable and fearless."),
  {"nonconformist": ("Someone who doesn't follow the crowd's rules.", "The nonconformist wore sandals to the wedding.", []),
   "hobgoblin": ("A mischievous imp; a silly fear.", "Worry about trends was his hobgoblin.", []),
   "consistency": ("Always doing or saying the same thing.", "Consistency matters in training a puppy.", [])},
  "emerson", [
  ("Self-Reliance", "", "Trust yourself",
   "Emerson's call: trust your own thoughts. Every heart responds to that iron string of self-trust.",
   "Trust thyself: every heart vibrates to that iron string.",
   "Believe in yourself; everyone feels the pull of self-trust.", "Choosing the career you love over the 'safe' one."),
  ("Self-Reliance", "", "Be a nonconformist",
   "To be your own person, you must not simply follow the crowd's idea of right.",
   "Whoso would be a man, must be a nonconformist.",
   "To be truly yourself, you can't just follow everyone else.", "Wearing what you like instead of what's trending."),
  ("Self-Reliance", "", "Foolish consistency",
   "Don't be trapped by what you said yesterday. Changing your mind when you learn more is a strength.",
   "A foolish consistency is the hobgoblin of little minds",
   "Refusing to change your mind is a small-minded habit.", "Admitting you were wrong about a restaurant after trying it."),
  ("Self-Reliance", "", "Misunderstood greatness",
   "Socrates, Jesus, Galileo and Newton were all misunderstood. Being misunderstood is not a sign you're wrong.",
   "To be great is to be misunderstood.",
   "Great people are often misunderstood.", "An inventor laughed at before the idea succeeds."),
  ("Friendship", "", "Be a friend",
   "You can't buy or chase friendship. The only way to have a friend is to be one.",
   "the only way to have a friend is to be one.",
   "To have friends, be a good friend first.", "Calling to check on someone instead of waiting for them to call."),
  ("Love", "", "All love a lover",
   "Everyone warms to someone in love; love brings out kindness and grace even in rough people.",
   "All mankind love a lover.",
   "Everyone likes seeing someone in love.", "The whole office smiling at a colleague's engagement news."),
])

# ------------------------------------------------ Stoic Wisdom
B(dict(id="seneca", title="On the Shortness of Life", short="Seneca", author="Lucius Annaeus Seneca", year="c. 49 AD",
       translator="Aubrey Stewart, 1889 (public domain, Project Gutenberg #64576)", era="ancient", shelf="Stoic Wisdom",
       blurb="Life isn't short — we waste it. Seneca's sharp little essay on time, busyness and living now."),
  {"carelessness": ("Not paying attention or care.", "Carelessness cost him his keys.", []),
   "luxury": ("Expensive comfort.", "A spa day felt like pure luxury.", [])},
  "seneca", [
  ("I", "Life Is Long Enough", "Life is long — if used",
   "We complain life is short, but we waste so much of it. Used well, it is long enough for great things.",
   "life is long enough to carry out the most important projects",
   "Life is long enough if you use it well.", "Two focused hours a day can write a book in a year."),
  ("I", "Life Is Long Enough", "Where time leaks",
   "Luxury and carelessness drain our days; we only notice at the end how fast it slipped away.",
   "when it all runs to waste through luxury and carelessness",
   "Time disappears through comfort and carelessness.", "Hours vanishing into scrolling on the sofa."),
  ("II", "Busy People", "Busy, but life is hurrying",
   "Busy people keep postponing living. Meanwhile life rushes on, and death won't wait for their schedule.",
   "you are busy, but life is hurrying on",
   "While you're busy, life passes quickly.", "Always 'too busy' to visit grandparents."),
  ("II", "Busy People", "Nobody owns himself",
   "Everyone gives their time to others — clients, cases, crowds — but no one claims time for himself.",
   "no one lays claim to his own self, every one wastes his time over some one else.",
   "People give all their time to others and none to themselves.", "Answering every message instantly but never having an hour for yourself."),
])

# ------------------------------------------------ Indian Wisdom
B(dict(id="panchatantra", title="The Panchatantra", short="Vishnu Sharma", author="Vishnu Sharma (trad.)", year="c. 300 BC",
       translator="Arthur W. Ryder, 1925 (public domain in the US; archive.org)", era="indic", shelf="Indian Wisdom",
       blurb="Animal fables written to teach three dull princes the art of ruling — the world's most travelled storybook, ancestor of Aesop and La Fontaine."),
  {"fetters": ("Chains that hold someone back.", "Debt became fetters on his freedom.", []),
   "fortress": ("A strong castle.", "The hill fort was a fortress no army took.", []),
   "consummation": ("Completion; fulfilment.", "The wedding was the consummation of years of love.", [])},
  "pancha", [
  ("Introduction", "Why the Book Was Written", "A book for dull princes",
   "A king despaired: his three sons hated learning. The wise Vishnu Sharma promised to make them wise in six months — by telling stories of animals who scheme, trust and betray.",
   "intercourse with like-minded friends",
   "Spending time with friends who think like you.", "A study group that keeps each other on track."),
  ("Book I", "The Loss of Friends", "Wisdom first",
   "In the fables, wisdom must lead every undertaking; then memory, plans and good advice follow.",
   "For Wisdom broods o'er the inception",
   "Wisdom should guide the start of anything.", "Researching before starting a business."),
  ("Book I", "The Loss of Friends", "Riches as chains",
   "A merchant reflects that wealth hoarded and never used is just foolish chains, kept for someone else to enjoy.",
   "His riches serve as foolish fetters",
   "Unused wealth only ties you down.", "Saving every rupee but never enjoying any of it."),
  ("Book III", "Crows and Owls", "Safety behind walls",
   "The animals of the fables talk like generals: one well-defended fortress is worth thousands of soldiers.",
   "A single royal fortress adds More military force Than do a thousand elephants",
   "A strong defence beats a huge army.", "One good password manager protects better than many weak passwords."),
])

B(dict(id="hitopadesa", title="The Hitopadesha", short="Narayana", author="Narayana (trad.)", year="c. 1100",
       translator="Sir Edwin Arnold, The Book of Good Counsels (public domain, Project Gutenberg #13268)", era="indic", shelf="Indian Wisdom",
       blurb="'Beneficial advice': Sanskrit fables of crows, deer, tigers and kings, packed with verses on friendship, money and war."),
  {"enmity": ("Deep hostility between enemies.", "The old enmity between the families ended at the wedding.", []),
   "scripture": ("Holy writings.", "She quoted scripture at the ceremony.", ["scripture-learning"]),
   "fate": ("A force believed to decide events.", "He blamed fate for the missed train.", [])},
  "hito", [
  ("Book I", "Winning of Friends", "An unlikely friendship",
   "A crow asks a mouse to be his friend. The mouse laughs — crows eat mice! The story asks whether trust can cross natural enmity.",
   "give me thy friendship",
   "Please be my friend.", "Making friends with a rival team's player."),
  ("Book I", "Winning of Friends", "Money and respect",
   "A bitter verse: people treat wealth as friends, family and even wisdom — and the fable calls this a shame.",
   "Wealth is friends, home, father, brother",
   "Money buys people's attention and respect.", "Suddenly having many 'friends' after a lottery win."),
  ("Book I", "Winning of Friends", "Some things never change",
   "However learned a cheat is, he's still a cheat; however bitter the pasture, a cow's milk is sweet. Nature shows through.",
   "Be his Scripture-learning wondrous, yet the cheat will be a cheat",
   "Education doesn't change a dishonest nature.", "A well-spoken scammer is still a scammer."),
  ("Introduction", "On Effort", "Lions must hunt",
   "Fate isn't enough: even a hungry lion must hunt, for no deer walks into his den while he sleeps.",
   "While the hungry lion slumbers, not a deer comes to his den.",
   "Success needs effort; it won't come to you while you sleep.", "Job offers don't arrive unless you apply."),
])

B(dict(id="kural", title="The Thirukkural", short="Tiruvalluvar", author="Tiruvalluvar", year="c. 300 BC–500 AD",
       translator="V. V. S. Aiyar, 1916 (public domain; archive.org)", era="indic", shelf="Indian Wisdom",
       blurb="1,330 two-line couplets from Tamil Nadu on virtue, wealth and love — the 'universal scripture' of South India."),
  {"knowledge": ("What you know and understand.", "Her knowledge of plants saved the garden.", []),
   "garment": ("A piece of clothing.", "She folded each garment neatly.", []),
   "instinctively": ("Without thinking; naturally.", "He instinctively ducked when the ball flew past.", [])},
  "kural", [
  ("Couplet 1", "In Praise of the Lord", "A is the first letter",
   "The Kural opens with a famous image: as 'A' begins every alphabet, so the divine begins everything that exists.",
   "A is the starting-point of the world of sound",
   "Just as 'A' starts every alphabet…", "Every great journey begins with a first, simple step."),
  ("Couplet 100", "Sweet Speech", "Why choose harsh words?",
   "Using hard words when gentle ones would work is like choosing unripe fruit over ripe.",
   "Behold the man who useth hard words when sweet ones serve : he preferreth the unripe fruit to the ripe.",
   "Choosing harsh words over kind ones is foolish.", "Snapping at a waiter when a polite word would work better."),
  ("Couplet 314", "Not Doing Evil", "Shame them with kindness",
   "The best punishment for those who hurt you: do them a good turn, so they feel ashamed.",
   "Let him do them a good turn and make them ashamed in their hearts.",
   "Answer people who hurt you with kindness.", "Helping a neighbour who once complained about you."),
  ("Couplet 396", "Learning", "Knowledge is a spring",
   "Knowledge is like water from a sand-spring: the more you dig, the more freely it flows.",
   "Knowledge is like unto a sand-spring: the more thou diggest and drawest thereat, the more excellent is the flow thereof.",
   "The more you learn, the more you're able to learn.", "Learning a second language makes the third easier."),
  ("Couplet 664", "Firmness in Action", "Saying vs doing",
   "Anyone can say a thing; doing it as promised is rare.",
   "To say a thing is easy for any man : but to do it in the manner undertaken is a rare thing indeed.",
   "Talking is easy; doing what you promised is rare.", "Everyone plans to start the gym; few actually go."),
  ("Couplet 788", "Friendship", "Like a hand catching a slipping cloth",
   "A true friend rushes to help in trouble as instinctively as your hand grabs a garment blown loose.",
   "Behold the hand of the man whose garment bath been blown aside",
   "A real friend helps instantly, without being asked.", "The friend who shows up at the hospital before you call."),
])

CAPS4 = {
 "speaking_01": "Robert Dighton, The Specious Orator", "speaking_02": "Franz Marc, Grazing Horses, 1911",
 "speaking_03": "Reading room, Bibliothèque Mazarine, 19th c.", "speaking_04": "William Hogarth, The Sleeping Congregation",
 "speaking_05": "Demosthenes, bust", "franklin_02": "Benjamin Franklin at the Court of France",
 "franklin_03": "The Continental Almanac, 1780", "franklin_04": "Poor Richard's Almanack, 1733", "franklin_05": "Franklin the printer",
 "chesterfield_01": "Pocket watch, 18th century", "chesterfield_02": "William Hogarth, The Holland House Group",
 "chesterfield_03": "The York Minuet, 18th-century print", "chesterfield_04": "Lord and lady with Death and the hourglass, after Dürer",
 "onwar_01": "Naval battle of 13 March 1806", "onwar_02": "The Congress of Vienna", "onwar_03": "Adolphe Yvon, Marshal Ney in the retreat from Russia",
 "onwar_04": "George Jones, The Battle of Borodino", "livy_01": "Cesare Maccari, Appius Claudius in the Senate",
 "livy_03": "Busts of Lucius and Marcus Junius Brutus", "republic_01": "Bust of Socrates, Capitoline Museums",
 "republic_02": "A shepherd's rural scene", "republic_03": "Douris, red-figure school cup, c. 480 BC",
 "republic_05": "Jan Saenredam, Plato's Cave, 1604", "ovid_01": "Mongez, Mars and Venus", "ovid_03": "'Sappho' with writing tablets, Pompeii fresco",
 "seneca_02": "A coronation banquet, 18th century", "seneca_03": "Manuel Domínguez, The Death of Seneca",
 "seneca_04": "Johannes Lingelbach, Roman Street Scene", "panchatantra_01": "Kalila wa Dimna, manuscript page",
 "panchatantra_02": "Dimna presents himself to the lion, Kalila and Dimna, c. 1380", "panchatantra_03": "The monkeys outwit the bears, Anvar-i Suhayli, 1600",
 "panchatantra_04": "Edwin Lord Weeks, The Palace of Amber", "hitopadesa_01": "The lion, crow, wolf and jackal, Kalila wa Dimna",
 "hitopadesa_02": "The merchant returns, Tuti-nama, Mughal, 16th century", "hitopadesa_04": "Abu'l Hasan, Raja Anup Rai intercepting a lion, c. 1615",
 "kural_01": "Palm-leaf style manuscript, 16th century", "kural_02": "A mango bird on a branch", "kural_03": "Raja Ravi Varma, Mandodari",
 "kural_04": "Encounter at the well, Indian painting", "kural_05": "A blacksmith, gouache on mica", "kural_06": "Krishna welcoming Sudama, Bhagavata Purana",
}

if __name__ == "__main__":
    import pathlib
    out = pathlib.Path(__file__).parent.parent / "library-only/books"
    for about, gl, cards in BOOKS:
        about = dict(about, version=2, cover=f"{about['id']}_cover")
        build(about, gl, cards, credits_file="commons/credits.json", caps=CAPS4, out_dir=out)
