"""Ten more books for the online library (not bundled in the APK). Run: python3 shelf2_content.py
Each card: (section, section title, card title, summary, verbatim quote, plain meaning, everyday example)."""
import folio_build
from folio_build import build, SOURCES

SOURCES.update({
    "meditations": ("meditations.txt", "Marcus Aurelius, Meditations (tr. Casaubon, 1634)"),
    "enchiridion": ("enchiridion.txt", "Epictetus, The Enchiridion (tr. Higginson)"),
    "tao": ("taoteching.txt", "Lao Tzu, Tao Te Ching (tr. Legge, 1891)"),
    "dhamma": ("dhammapada.txt", "The Dhammapada (tr. Max Müller, 1881)"),
    "artha": ("artha_r.-shamasastry-kautilyas-arthashastra-1915.txt", "Kautilya, Arthashastra (tr. Shamasastry, 1915)"),
    "crowd": ("crowd.txt", "Gustave Le Bon, The Crowd (1895)"),
    "thinketh": ("thinketh.txt", "James Allen, As a Man Thinketh (1903)"),
    "bge": ("bge.txt", "Friedrich Nietzsche, Beyond Good and Evil (tr. Zimmern, 1907)"),
})
folio_build.OCR.add("artha")
folio_build.CAPS.update({
 "arthashastra_04": "A Practical Treatise on the Hive and Honey-Bee", "arthashastra_05": "Fishing in India, old engraving",
 "bge_02": "Gustave Doré, Into the Abyss (Dante's Inferno)", "crowd_02": "The Storming of the Bastille, 1789", "crowd_05": "Honoré Daumier, crowd lithograph",
 "dhammapada_02": "Ajanta painting, National Museum, New Delhi", "dhammapada_03": "Thatched huts by a river, Bengal",
 "dhammapada_06": "Jataka tales, illustrated manuscript", "dhammapada_08": "Pillar of Ashoka (replica)",
 "enchiridion_01": "Epictetus, engraving, 1653", "enchiridion_03": "Wheel of Fortune with the Fates",
 "enchiridion_05": "Roman funeral relief, Galleria Borghese", "enchiridion_06": "Banquet scene, fresco from Herculaneum",
 "enchiridion_07": "Theatre masks, Roman mosaic, Naples", "enchiridion_08": "The Orator (Aulus Metellus), Roman bronze",
 "gracian_01": "Velázquez, Las Meninas", "gracian_02": "Velázquez, Philip IV as a Hunter", "gracian_05": "Portrait of a Lady, Spanish school, 17th century",
 "gracian_07": "Franciscus Gijsbrechts, Vanitas still life", "gracian_08": "Gheeraerts, The Phoenix, 1568",
 "maxims_01": "Portrait engraving, 17th-century France", "maxims_03": "Illustration for Molière's Tartuffe",
 "maxims_04": "Van der Meulen, Louis XIV and his court", "maxims_06": "The Triumph of Fortune",
 "meditations_01": "Marcus Aurelius, marble head", "meditations_02": "Column of Marcus Aurelius, relief",
 "meditations_05": "Roman villa fresco, Oplontis", "meditations_06": "Piranesi, Roman ruins", "meditations_07": "Piranesi, View of the Roman Forum",
 "meditations_08": "After Guido Reni, Aurora", "meditations_09": "Portrait of a philosopher, engraving", "meditations_10": "Cucumber and eggplant, botanical print",
 "taoteching_01": "Chinese landscape fan painting", "taoteching_02": "Portrait of a Chinese sage", "taoteching_08": "Chinese fish painting",
})

BOOKS = []
def book(about, glossary, cards):
    BOOKS.append((about, glossary, cards))

def C(src, rows):
    return [dict(ch=r[0], chTitle=r[1], title=r[2], text=r[3], quote=r[4], qMean=r[5], qLife=r[6], src=src) for r in rows]

# ---------------------------------------------------------------- Meditations
book(dict(id="meditations", title="Meditations", short="Marcus Aurelius", author="Marcus Aurelius", year="c. 175",
          translator="Meric Casaubon, 1634 (public domain, Project Gutenberg #2680)", era="ancient", shelf="Stoic Wisdom",
          blurb="The private notebook of a Roman emperor, written in army camps at night: how to stay calm, fair and useful when the world is not."),
 {"betimes": ("Early; in good time (old use).", "Betimes on Monday, plan the week before the emails arrive.", []),
  "railer": ("Someone who complains or insults angrily.", "Every office has a railer who hates every new rule.", []),
  "meek": ("Gentle and patient; not easily angered.", "The meek waiter stayed polite with the rudest customer.", []),
  "discretion": ("Good judgement about what to do or say.", "Use discretion before forwarding that private message.", []),
  "vanity": ("Too much pride in yourself or your looks.", "Posting ten selfies a day can be vanity.", []),
  "brambles": ("Prickly wild bushes.", "We took the long path to avoid the brambles.", []),
  "impediment": ("Something that blocks progress.", "A bad internet connection is an impediment to online classes.", []),
  "stoic": ("Calm and uncomplaining in hard times; also the philosophy that teaches this.", "She stayed stoic while the flight was delayed six hours.", ["stoics"])},
 C("meditations", [
  ("Book I", "Debts of Gratitude", "Thank you, grandfather",
   "Marcus opens not with ideas but with thanks. Line by line he lists what each person taught him: gentleness from his grandfather, modesty from his father, generosity from his mother. Before he lectures himself, he remembers that character is borrowed from the people we admire.",
   "Of my grandfather Verus I have learned to be gentle and meek, and to refrain from all anger and passion.",
   "From my grandfather I learned to be gentle and to control my temper.", "Noticing you handle stress calmly because your mum always did."),
  ("Book II", "Morning Preparation", "Expect difficult people",
   "Each morning, Marcus warns himself: today I will meet rude, ungrateful, jealous people. They act this way from ignorance of what is truly good. Since we are made to work together, like hands and feet, he refuses to be harmed by them or to hate them.",
   "Betimes in the morning say to thyself, This day I shalt have to do with an idle curious man, with an unthankful man, a railer, a crafty, false, or an envious man",
   "Every morning, remind yourself you will meet nosy, ungrateful, rude or jealous people today.", "Walking into a family wedding already decided not to let your one difficult uncle ruin it."),
  ("Book II", "No More Delay", "Stop putting it off",
   "How many times have you said 'tomorrow'? Marcus tells himself his time is limited; if he wastes it, it will pass and never return. The cure for anxiety is simple: do the task in front of you as if it were the last thing you'll ever do — carefully, honestly, without fuss.",
   "Remember how long thou hast already put off these things",
   "Think about how long you've been postponing what matters.", "The gym membership you've 'started next Monday' for a year."),
  ("Book II", "Act As If It's the Last", "The last action",
   "Do each thing as if it were your final act: without show, without selfishness, without complaining. This takes away the restless worry that ruins most days. Few rules are needed for a good life, and the gods ask nothing more.",
   "if thou shalt go about every action as thy last action, free from all vanity",
   "Do everything as if it were the last thing you'll do — without showing off.", "Writing a birthday message as if it might be the last one you send that person."),
  ("Book IV", "The Inner Citadel", "Retreat into yourself",
   "People look for peace in country houses and beaches. Marcus says you can retreat any time — into your own mind. Keep a few short, true principles ready, and a moment of reflection will refresh you better than any holiday.",
   "At what time soever thou wilt, it is in thy power to retire into thyself, and to be at rest",
   "Whenever you choose, you can step back into your own mind and find calm.", "Three slow breaths in a crowded metro instead of losing your temper."),
  ("Book IV", "Everything Changes", "This world is change",
   "Look around: everything you see will soon change and vanish, as you have already seen many things change in your own lifetime. Most of our suffering comes from opinions, not from things. Change the opinion and the hurt changes too.",
   "This world is mere change, and this life, opinion.",
   "Everything keeps changing, and how we feel about life depends on our views of it.", "The exam that felt like the end of the world at sixteen barely matters at twenty-five."),
  ("Book IV", "Fame Fades", "Fame is a breath",
   "Many people have never heard your name, many who have will soon forget it, and some who praise you today will mock you tomorrow. So don't build your life on fame or praise; build it on doing what is right.",
   "how many that will soon forget it; how many who but even now did commend thee, within a very little while perchance will speak ill of thee",
   "People who praise you now may forget you or criticise you soon.", "A viral post's fans move on to someone else within a week."),
  ("Book V", "Getting Out of Bed", "Get up — there's work to do",
   "On mornings when he wants to stay under the blanket, Marcus argues with himself: was I born only to feel warm? Plants, birds and bees all do their work; should a human refuse to do a human's work?",
   "In the morning when thou findest thyself unwilling to rise, consider with thyself presently, it is to go about a man's work that I am stirred up.",
   "When you don't want to get up, remind yourself you're getting up to do your real work.", "Turning off the snooze button by thinking of the people counting on you today."),
  ("Book VI", "The Future", "Don't fear tomorrow",
   "Worrying about the future is wasted strength. Whatever comes, you will face it with the same reason that helps you handle today. Be ready, not anxious.",
   "Let not things future trouble thee.",
   "Don't let worries about the future upset you now.", "Preparing for an interview, then sleeping well instead of imagining every bad outcome."),
  ("Book VIII", "Bitter Cucumbers", "Just step around it",
   "A bitter cucumber? Throw it away. Brambles on the path? Walk around them. Don't add a complaint about why such things exist. Most of life's small annoyances need action or acceptance, not philosophy.",
   "Is the cucumber bitter? set it away. Brambles are in the way? avoid them.",
   "If something's bad, put it aside; if something's in the way, go around it.", "A slow app? Delete it and move on instead of ranting online."),
 ])),

# ---------------------------------------------------------------- Enchiridion
book(dict(id="enchiridion", title="The Enchiridion", short="Epictetus", author="Epictetus", year="c. 125",
          translator="Thomas Wentworth Higginson (public domain, Project Gutenberg #45109)", era="ancient", shelf="Stoic Wisdom",
          blurb="A pocket handbook from a philosopher born a slave: separate what you control from what you don't, and you will never be a slave again."),
 {"aversion": ("A strong dislike.", "She has an aversion to crowded malls.", []),
  "impediment": ("Something that blocks or slows you.", "His injury was an impediment to playing football.", []),
  "humor": ("Mood (old use).", "He was in a bad humor after the long queue.", []),
  "banquet": ("A large formal feast.", "The wedding banquet had twenty dishes.", []),
  "tribunals": ("Courts or panels that judge.", "The case went to three tribunals before being settled.", []),
  "drama": ("A play; a story acted out.", "The school drama needed someone to play the king.", [])},
 C("enchiridion", [
  ("I", "What Is Ours", "Control what you can",
   "The whole handbook rests on one split. Some things are up to us: our opinions, aims, desires and dislikes. Others are not: our body, property, reputation and position. Treat the second kind as yours and you will be frustrated and blame everyone. Focus on the first and nobody can harm you.",
   "There are things which are within our power, and there are things which are beyond our power.",
   "Some things you can control; some things you can't.", "You can't control the traffic, but you can control when you leave home."),
  ("V", "Views, Not Things", "It's the story you tell",
   "We are not upset by events, but by our judgements about them. Death is not terrible — otherwise Socrates would have feared it. When we are troubled, we should blame our own views, not others.",
   "Men are disturbed not by things, but by the views which they take of things.",
   "What upsets us is not what happens, but what we think about it.", "Two people stuck in the same rain: one is miserable, the other enjoys the smell."),
  ("VIII", "Want What Happens", "Wish for what is",
   "Don't demand that the world go your way. Wish instead that things happen as they actually do happen, and you will live at peace.",
   "Demand not that events should happen as you wish; but wish them to happen as they do happen, and you will go on well.",
   "Stop insisting things go your way; accept how they go, and life is easier.", "Rain on your picnic day? Move it indoors and have fun anyway."),
  ("IX", "The Free Will", "The body can be stopped",
   "Illness can stop the body, but not the will — unless the will agrees. Lameness stops the leg, not the mind. Whatever happens, ask what it stops, and you'll find it stops something else, not you.",
   "Sickness is an impediment to the body, but not to the will unless itself pleases.",
   "Illness can limit your body, but not your choices, unless you let it.", "A friend with a broken leg who still finishes her course online."),
  ("XI", "Given Back", "Nothing is lost, only returned",
   "Never say 'I have lost it' — say 'I have given it back.' Everything we have is on loan from life. While it is with you, take care of it, as a traveller takes care of an inn.",
   "Never say of anything, “I have lost it,” but, “I have restored it.”",
   "Don't call things lost; think of them as returned to where they came from.", "When an old phone dies, being grateful for the years it worked."),
  ("XV", "The Banquet", "Take a modest share",
   "Behave in life as at a dinner party. When a dish comes to you, take a polite portion. If it passes you by, don't grab at it. If it hasn't come yet, wait. Treat children, money and status the same way.",
   "Remember that you must behave as at a banquet.",
   "Act in life like a polite guest at a big dinner.", "Not pushing for a promotion that isn't open yet, but being ready when it comes."),
  ("XVII", "The Actor", "Play your role well",
   "You are an actor in a play written by someone else. Whether your part is short or long, poor or royal, your job is to play it well; choosing the part is not.",
   "Remember that you are an actor in a drama of such sort as the Author chooses",
   "You don't choose your role in life, but you choose how well you play it.", "Being the best possible assistant manager instead of sulking about not being the boss."),
  ("XLII", "When Others Wrong You", "They think they're right",
   "When someone harms or insults you, remember they acted on what seemed right to them. If they are wrong, they are the ones deceived and hurt. Say to yourself: 'It seemed so to him.'",
   "When any person does ill by you, or speaks ill of you, remember that he acts or speaks from an impression that it is right for him to do so.",
   "When someone hurts you, remember they believe they're right.", "The driver who honked at you probably thought you cut him off."),
 ])),

# ---------------------------------------------------------------- Tao Te Ching
book(dict(id="taoteching", title="Tao Te Ching", short="Lao Tzu", author="Lao Tzu", year="c. 400 BC",
          translator="James Legge, 1891 (public domain, Project Gutenberg #216)", era="eastern", shelf="Eastern Paths",
          blurb="Eighty-one tiny poems on the Way: soft beats hard, empty is useful, the leader who leads least leads best."),
 {"tao": ("'The Way' — the natural flow behind everything.", "Gardeners who work with the seasons follow the Tao of plants.", []),
  "sage": ("A very wise person.", "Grandma was the family sage everyone asked for advice.", ["sages"]),
  "nave": ("The centre of a wheel where the spokes meet.", "The bicycle's nave was rusted.", []),
  "obscurity": ("Being unknown or unnoticed.", "After retiring, the famous actor lived in obscurity.", []),
  "excellence": ("Very high quality.", "The restaurant is known for its excellence.", []),
  "discerning": ("Good at judging things well.", "A discerning buyer checks reviews first.", [])},
 C("tao", [
  ("Chapter 1", "The Nameless Way", "The Tao that can't be named",
   "The book opens with a puzzle: the true Way cannot be fully spoken. Any name we give it is a label, not the thing itself. Lao Tzu is warning us — words point at wisdom, but living it is something else.",
   "The Tao that can be trodden is not the enduring and unchanging Tao.",
   "Any Way you can fully describe is not the deepest, everlasting Way.", "No recipe can fully capture how your mother's dal tastes."),
  ("Chapter 7", "Last, Yet First", "Put yourself last",
   "The sage puts himself last and ends up first; he forgets himself and is kept safe. Because he has no selfish aims, his real aims are achieved.",
   "Therefore the sage puts his own person last, and yet it is found in the foremost place",
   "The wise person puts themselves last, and ends up ahead.", "A captain who passes the ball and lets others score becomes the team's leader."),
  ("Chapter 8", "Like Water", "The highest good is like water",
   "Water helps all things and fights with none. It flows to the low places that people avoid. Lao Tzu's ideal is just as humble, useful and patient.",
   "The highest excellence is like (that of) water.",
   "The best kind of goodness is like water — helpful and humble.", "A colleague who quietly helps everyone and never competes for credit."),
  ("Chapter 9", "Know When to Stop", "Step back when it's done",
   "Fill a bowl to the brim and it spills; sharpen a blade too much and it breaks. When the work is done and your name is known, step back. That is the way of Heaven.",
   "When the work is done, and one's name is becoming distinguished, to withdraw into obscurity is the way of Heaven.",
   "When the job's done and you're getting famous, quietly step aside.", "A founder who hands the company to new leaders at its peak."),
  ("Chapter 11", "The Use of Emptiness", "Empty is useful",
   "Thirty spokes meet at the hub, but the hole in the middle makes the wheel work. A pot is useful because it is hollow; a room because of its empty space. What isn't there matters as much as what is.",
   "The thirty spokes unite in the one nave; but it is on the empty space (for the axle), that the use of the wheel depends.",
   "A wheel works because of the empty space at its centre.", "A calendar with free time in it is what lets you handle surprises."),
  ("Chapter 33", "Knowing Yourself", "Mastering yourself",
   "Knowing others is cleverness; knowing yourself is wisdom. Beating others shows strength; beating your own habits shows real power. Being content is being rich.",
   "He who knows other men is discerning; he who knows himself is intelligent.",
   "Understanding others is clever; understanding yourself is wise.", "Knowing you get cranky when hungry, and eating before the big meeting."),
  ("Chapter 56", "Silent Knowing", "Those who know don't say",
   "People who truly understand the Way rarely lecture about it; people who talk about it constantly usually don't understand it.",
   "He who knows (the Tao) does not (care to) speak (about it); he who is (ever ready to) speak about it does not know it.",
   "Those who really know don't brag; those who brag don't really know.", "The best cook in the family just cooks; the one who talks endlessly about food burns the rice."),
  ("Chapter 60", "Small Fish", "Govern gently",
   "Ruling a big country is like cooking small fish: poke and stir too much and they fall apart. A good ruler interferes as little as possible.",
   "Governing a great state is like cooking small fish.",
   "Running a big country needs a light touch, like frying small fish.", "A manager who micromanages every email breaks the team's flow."),
  ("Chapter 64", "The First Step", "A thousand miles, one step",
   "Big things grow from small beginnings: a giant tree from a sprout, a tower from a heap of earth, a long journey from a single step. Handle problems while they are small.",
   "the journey of a thousand li commenced with a single step.",
   "Every long journey begins with one small step.", "Writing one page today is how a whole book gets written."),
 ])),

# ---------------------------------------------------------------- Dhammapada
book(dict(id="dhammapada", title="The Dhammapada", short="The Buddha", author="The Buddha (trad.)", year="c. 250 BC",
          translator="F. Max Müller, 1881 (public domain, Project Gutenberg #2017)", era="indic", shelf="Eastern Paths",
          blurb="Short verses from the Buddha's teaching on the mind: what you think, you become."),
 {"earnestness": ("Serious, sincere effort and alertness.", "Her earnestness in practice made her the best in class.", []),
  "nirvana": ("In Buddhism, freedom from suffering and desire.", "Monks meditate for years seeking nirvana.", []),
  "fletcher": ("A maker of arrows.", "The fletcher straightened each arrow over a flame.", []),
  "liberality": ("Generosity.", "His liberality helped the whole village build a well.", []),
  "serene": ("Calm and peaceful.", "The lake was serene at dawn.", []),
  "passion": ("Strong feeling or desire.", "Passion for music kept him practising daily.", [])},
 C("dhamma", [
  ("Chapter I", "The Twin-Verses", "You are your thoughts",
   "The Dhammapada begins with the mind. Everything we are comes from what we think. Act from a bad thought and pain follows like a cart wheel behind an ox; act from a pure one and happiness follows like a shadow.",
   "All that we are is the result of what we have thought: it is founded on our thoughts, it is made up of our thoughts.",
   "Your life is shaped by your thoughts.", "Thinking 'I'm bad at maths' makes you stop trying — and so you stay bad at it."),
  ("Chapter I", "The Twin-Verses", "Hatred never ends hatred",
   "Answering hatred with hatred keeps it going forever. Only love — or friendliness — brings it to an end. This, says the Buddha, is an ancient law.",
   "For hatred does not cease by hatred at any time: hatred ceases by love, this is an old rule.",
   "Hate never stops hate; only love stops it.", "Ending a family feud by being the first to apologise."),
  ("Chapter I", "The Twin-Verses", "A well-thatched roof",
   "Rain leaks through a badly thatched roof; desire leaks into a mind that never reflects. A mind that pauses and thinks keeps passion out, like a good roof keeps out the rain.",
   "As rain breaks through an ill-thatched house, passion will break through an unreflecting mind.",
   "A careless mind lets cravings in, like rain through a bad roof.", "Impulse-buying everything in the cart because you never stopped to think."),
  ("Chapter II", "On Earnestness", "Wakefulness is life",
   "Alert, careful effort leads to freedom; carelessness is a kind of death. Those who stay awake to their lives truly live; the thoughtless are as if already dead.",
   "Earnestness is the path of immortality (Nirvana), thoughtlessness the path of death.",
   "Paying careful attention leads to freedom; carelessness leads to ruin.", "Reading the contract carefully instead of clicking 'agree'."),
  ("Chapter III", "Thought", "Straighten the mind",
   "The mind trembles and wanders like a fish thrown on dry land. A wise person straightens it the way an arrow-maker straightens an arrow — patiently, with skill.",
   "As a fletcher makes straight his arrow, a wise man makes straight his trembling and unsteady thought",
   "A wise person steadies their restless mind like an arrow-maker straightens an arrow.", "Bringing your attention back to the page every time your phone buzzes."),
  ("Chapter V", "The Fool", "The wise fool",
   "A fool who knows he is a fool is at least that much wise; the real fool is the one who thinks himself wise.",
   "The fool who knows his foolishness, is wise at least so far.",
   "Knowing you don't know is a kind of wisdom.", "The new employee who asks questions learns faster than the one who pretends."),
  ("Chapter VI", "The Wise Man", "Like a rock",
   "A solid rock is not moved by the wind; the wise are not moved by praise or blame. They stay calm and clear like a deep lake.",
   "As a solid rock is not shaken by the wind, wise people falter not amidst blame and praise.",
   "Wise people stay steady whether they are praised or criticised.", "Reading both good and bad comments on your work without your mood swinging."),
  ("Chapter VIII", "The Thousands", "The greatest victory",
   "Winning a thousand battles is less than winning over yourself. Self-mastery is a victory nobody can take away.",
   "If one man conquer in battle a thousand times thousand men, and if another conquer himself, he is the greatest of conquerors.",
   "Beating your own weaknesses is greater than beating any army.", "Quitting smoking is a bigger win than any argument you ever won."),
  ("Chapter XVII", "Anger", "Answer anger with love",
   "Overcome anger with kindness, evil with good, greed with generosity, and lies with truth.",
   "Let a man overcome anger by love, let him overcome evil by good; let him overcome the greedy by liberality, the liar by truth!",
   "Beat anger with love, greed with generosity, and lies with truth.", "Replying calmly and kindly to an angry customer until they calm down too."),
 ])),

# ---------------------------------------------------------------- Arthashastra
book(dict(id="arthashastra", title="Arthashastra", short="Kautilya", author="Kautilya (Chanakya)", year="c. 300 BC",
          translator="R. Shamasastry, 1915 (public domain, archive.org)", era="indic", shelf="Power & Strategy",
          blurb="India's ancient handbook of statecraft, by the strategist who helped build the Maurya empire: ministers, spies, money, punishment — and a king who must serve his people."),
 {"subjects": ("People ruled by a king.", "The king's subjects paid taxes in grain.", []),
  "sovereignty": ("Supreme power to rule.", "The island fought for its sovereignty.", []),
  "ministers": ("Senior advisers who help run a government.", "The ministers met every morning with the king.", []),
  "revenue": ("Money a government or business takes in.", "The shop's revenue doubled at Diwali.", []),
  "punishment": ("A penalty for doing wrong.", "The punishment for littering is a fine.", []),
  "danda": ("Sanskrit for 'the rod' — the power to punish.", "Kautilya said danda keeps the strong from crushing the weak.", []),
  "contemptible": ("Deserving no respect.", "Cheating your own friends is contemptible.", []),
  "spies": ("Secret gatherers of information.", "Kautilya's spies dressed as monks and merchants.", ["spy"])},
 C("artha", [
  ("Book I", "Duties of a King", "The king's happiness",
   "Kautilya's most famous line turns power upside down: a king's happiness lies in his people's happiness. He must not call good what pleases him, but what pleases them. So a king must always be active and alert.",
   "In the happiness of his subjects lies his happiness; in their welfare his welfare",
   "A ruler is happy only when the people are happy.", "A school head who measures success by how the students are doing, not by her own awards."),
  ("Book I", "The Saintly King", "One wheel can't move",
   "Power can't be held alone. Just as a cart needs two wheels, a ruler needs ministers and their honest opinions.",
   "A single wheel can never move.",
   "No one can rule or succeed alone.", "A startup founder who hires good people instead of doing everything herself."),
  ("Book I", "On Punishment", "Neither harsh nor soft",
   "Some teachers say rule by fear. Kautilya disagrees: too-harsh punishment makes a ruler hated, too-mild punishment makes him a joke. Only fair punishment, matched to the wrong, earns respect.",
   "for whoever imposes severe punishment becomes repulsive to the people; while he who awards mild punishment becomes contemptible.",
   "Too much punishment makes people hate you; too little makes them not respect you.", "A parent whose rules are fair is obeyed more than one who shouts or one who never says no."),
  ("Book II", "Embezzlement", "Honey on the tongue",
   "Kautilya, a realist, says officials handling money will be tempted, as surely as you'd taste honey placed on your tongue. So a wise government doesn't rely on trust alone: it checks, rotates and audits its officers.",
   "it is impossible not to taste the honey or the poison that finds itself at the tip of the tongue",
   "When you handle something tempting, it's almost impossible not to take a little.", "Why companies audit accounts even when they trust the accountant."),
  ("Book II", "Embezzlement", "Fish in water",
   "Just as you can't see a fish drinking water, you can't easily see an official quietly taking money. Watch results and records, not appearances.",
   "Just as fish moving under water cannot possibly be found out either as drinking or not drinking water, so government servants employed in the government work cannot be found out (while) taking money (for themselves).",
   "Hidden dishonesty is hard to spot, like a fish drinking underwater.", "Checking the stock count, not just the cashier's smile."),
  ("Book I", "The King's Vow", "Action is the king's prayer",
   "For a king, Kautilya says, the holy vow is being ready to act; doing his duties well is his sacrifice; treating everyone equally is his gift to the priests.",
   "Of a king, the religious vow is his readiness to action",
   "A leader's true devotion is being ready to act.", "A manager who answers problems the same day instead of 'looking into it' for weeks."),
 ])),

# ---------------------------------------------------------------- The Crowd
book(dict(id="crowd", title="The Crowd", short="Gustave Le Bon", author="Gustave Le Bon", year="1895",
          translator="English translation, 1896 (public domain, Project Gutenberg #445)", era="victorian", shelf="Mind & the Crowd",
          blurb="A French doctor explains why sensible people turn wild in a mob — the book later studied by propagandists, marketers and dictators."),
 {"contagion": ("The spreading of a feeling or idea from person to person.", "Laughter in a cinema spreads by contagion.", []),
  "affirmation": ("A firm statement presented as true.", "Ads use affirmation: 'The best tea in India.'", []),
  "illusions": ("False ideas or beliefs that seem real.", "Get-rich-quick schemes sell illusions.", ["illusion"]),
  "barbarian": ("A wild, uncivilised person.", "At the match he shouted like a barbarian.", []),
  "prestige": ("Respect and admiration from success or status.", "The university's prestige attracts students worldwide.", []),
  "deify": ("To treat someone or something like a god.", "Fans sometimes deify film stars.", [])},
 C("crowd", [
  ("Book I", "The Mind of Crowds", "Down the ladder",
   "Le Bon's key idea: a person in a crowd is not the same person alone. Joining a mob, a man drops several steps down the ladder of civilisation — he becomes impulsive, emotional and easy to lead.",
   "by the mere fact that he forms part of an organised crowd, a man descends several rungs in the ladder of civilisation.",
   "In a crowd, people behave less thoughtfully than they would alone.", "Normally calm fans throwing bottles after their team loses."),
  ("Book I", "The Mind of Crowds", "Barbarian in a crowd",
   "Alone, someone may be thoughtful and educated; in a crowd, instinct takes over. Crowds feel quickly, decide quickly, and forget quickly.",
   "Isolated, he may be a cultivated individual; in a crowd, he is a barbarian",
   "On your own you may be civilised; in a crowd you may act wildly.", "A polite colleague who joins a pile-on in a group chat."),
  ("Book I", "Contagion", "Feelings are contagious",
   "Emotions and actions spread through a crowd like an infection. One person panics or cheers, and soon everyone does — even against their own interests.",
   "Contagion is a phenomenon of which it is easy to establish the presence",
   "Feelings spread through groups like a disease.", "One person runs at a sale and suddenly everyone is running."),
  ("Book II", "Words and Images", "Words over reasons",
   "Crowds don't follow arguments; they follow words and pictures. A striking slogan can move them to things none would do alone.",
   "allows himself to be impressed by words and images",
   "Crowds are moved by catchy words and pictures, not by logic.", "A short election slogan sways more voters than a long policy paper."),
  ("Book II", "Illusions", "Crowds want illusions",
   "Masses have never wanted hard truth. They prefer comforting illusions, and whoever supplies them becomes their master.",
   "The masses have never thirsted after truth.",
   "Most people prefer comforting stories to uncomfortable facts.", "Miracle-cure ads sell better than honest doctors' advice."),
  ("Book II", "How Leaders Persuade", "Say it, repeat it, spread it",
   "Leaders win crowds with three tools: bold affirmation without proof, endless repetition, and contagion — letting the idea spread on its own.",
   "affirmation, repetition, and contagion",
   "Leaders persuade by stating things boldly, repeating them, and letting them spread.", "A jingle repeated on every channel until everyone hums it."),
 ])),

# ---------------------------------------------------------------- As a Man Thinketh
book(dict(id="thinketh", title="As a Man Thinketh", short="James Allen", author="James Allen", year="1903",
          translator="Original English text (public domain, Project Gutenberg #4507)", era="modern", shelf="Mind & the Crowd",
          blurb="A tiny classic of self-help: your thoughts are seeds, your life is the garden."),
 {"aphorism": ("A short, wise saying.", "'Practice makes perfect' is an aphorism.", []),
  "cultivated": ("Carefully grown or developed.", "She cultivated a habit of reading daily.", []),
  "circumstance": ("A condition or fact around you.", "Bad circumstances can still teach good lessons.", ["circumstances"]),
  "serenity": ("Peaceful calm.", "The temple courtyard was full of serenity.", []),
  "calmness": ("The state of being calm.", "Her calmness in the exam hall helped her think.", [])},
 C("thinketh", [
  ("Thought and Character", "", "You are what you think",
   "Allen starts from an old proverb: as a man thinks in his heart, so he is. Character, he says, is the sum of all our thoughts.",
   "\"As a man thinketh in his heart so is he,\"",
   "Who you are comes from what you think.", "Telling yourself 'I'm a learner' makes you keep learning."),
  ("Effect of Thought on Circumstances", "", "The mind is a garden",
   "The mind is like a garden. Plant nothing and weeds grow on their own. A good gardener pulls out weeds and plants flowers; a wise person does the same with thoughts.",
   "MAN'S mind may be likened to a garden, which may be intelligently cultivated or allowed to run wild",
   "Your mind is a garden: tend it or it grows weeds.", "Choosing what to watch and read instead of scrolling whatever comes."),
  ("Effect of Thought on Circumstances", "", "Circumstance reveals",
   "Hard situations don't create who we are; they show it. The habits of thought we built quietly come out when life tests us.",
   "Circumstance does not make the man; it reveals him to himself",
   "Situations don't make you; they show who you already are.", "A crisis at work shows who stays calm and who panics."),
  ("Effect of Thought on Circumstances", "", "Change yourself first",
   "People want better lives but don't want to change their habits, so they stay stuck. Improve yourself and your situation follows.",
   "Men are anxious to improve their circumstances, but are unwilling to improve themselves; they therefore remain bound.",
   "People want better lives but won't change themselves, so they stay stuck.", "Wanting a promotion but not learning the new skill it needs."),
  ("Thought and Purpose", "", "Purpose makes thought powerful",
   "Thought joined to a clear purpose becomes a creative force. Without aim, thoughts wander and waste energy.",
   "Thought allied fearlessly to purpose becomes creative force",
   "Thinking with a clear goal turns ideas into results.", "A clear plan to save for a bike makes small savings add up."),
  ("Serenity", "", "Calm is power",
   "The book ends with calm: it comes from long practice in self-control, and it is a jewel of wisdom. Self-control is strength; calmness is power.",
   "Self-control is strength; Right Thought is mastery; Calmness is power.",
   "Controlling yourself is strength, and staying calm is power.", "The calm negotiator usually gets the better deal."),
 ])),

# ---------------------------------------------------------------- Beyond Good and Evil
book(dict(id="bge", title="Beyond Good and Evil", short="Nietzsche", author="Friedrich Nietzsche", year="1886",
          translator="Helen Zimmern, 1907 (public domain, Project Gutenberg #4363)", era="germanic", shelf="Mind & the Crowd",
          blurb="Nietzsche's sharpest book: our morals hide deeper drives, every deep thinker wears a mask, and the herd hates whoever stands apart."),
 {"abyss": ("A very deep hole; a frightening emptiness.", "Staring into the abyss of debt kept him awake.", []),
  "esteems": ("Respects; holds in high regard.", "She esteems her teacher deeply.", ["esteem"]),
  "profound": ("Very deep or serious.", "Losing a pet can be a profound sadness.", []),
  "militant": ("Ready to fight, aggressive.", "The militant fan argued with everyone online.", []),
  "insanity": ("Madness; extreme foolishness.", "Driving at that speed in rain is insanity.", []),
  "despises": ("Feels strong dislike and disrespect for.", "He despises people who litter.", ["despiser"])},
 C("bge", [
  ("Aphorism 146", "Apophthegms", "Fighting monsters",
   "Nietzsche's most quoted warning: whoever fights monsters must be careful not to become one. Stare too long into darkness and it gets into you.",
   "He who fights with monsters should be careful lest he thereby become a monster.",
   "When you fight something evil, be careful not to become evil yourself.", "A team fighting online trolls by turning into trolls themselves."),
  ("Aphorism 146", "Apophthegms", "The abyss looks back",
   "The second half of the line: gaze long into an abyss and the abyss gazes into you. What we obsess over changes us.",
   "And if thou gaze long into an abyss, the abyss will also gaze into thee.",
   "If you dwell on darkness too long, it starts to change you.", "Reading crime news all night and then fearing every stranger."),
  ("Aphorism 40", "The Free Spirit", "Every deep mind wears a mask",
   "Deep people grow masks, partly because others always misunderstand them. The mask is protection, not just deceit.",
   "Every profound spirit needs a mask",
   "Deep thinkers hide behind a public face.", "A comedian who jokes all the time but is serious in private."),
  ("Aphorism 156", "Apophthegms", "The madness of groups",
   "Madness is rare in single people but normal in groups, parties, nations and eras.",
   "Insanity in individuals is something rare--but in groups, parties, nations, and epochs it is the rule.",
   "One person rarely goes mad, but groups often do.", "Sensible people joining a crazy online trend together."),
  ("Aphorism 78", "Apophthegms", "Self-contempt is pride",
   "Even someone who despises himself still respects himself — as the one who judges.",
   "He who despises himself, nevertheless esteems himself thereby, as a despiser.",
   "Even self-criticism hides a little self-respect.", "The person who says 'I'm the worst' is often waiting for you to disagree."),
  ("Aphorism 76", "Apophthegms", "Fighters at peace",
   "In peaceful times, the fighting kind of person turns against himself.",
   "Under peaceful conditions the militant man attacks himself.",
   "Fighters with no outside enemy start fighting themselves.", "An athlete forced to rest starts being hard on themselves."),
 ])),

# ---------------------------------------------------------------- The Art of Worldly Wisdom
book(dict(id="gracian", title="The Art of Worldly Wisdom", short="Baltasar Gracián", author="Baltasar Gracián", year="1647",
          translator="Joseph Jacobs, 1892 (public domain, archive.org)", era="baroque", shelf="Courtly Wisdom",
          blurb="Three hundred maxims by a Spanish Jesuit on getting on in a dangerous world — the source behind many of the 48 Laws."),
 {"superiors": ("People above you in rank.", "Always be polite to your superiors in an email.", []),
  "insipid": ("Dull; lacking flavour or interest.", "The insipid soup needed salt.", []),
  "thumbscrew": ("An old torture tool; here, the pressure point that moves someone.", "Praise is his thumbscrew.", []),
  "venial": ("Small and easily forgiven.", "Being five minutes late is a venial fault.", []),
  "phoenix": ("A mythical bird that is reborn from its ashes.", "The old company rose like a phoenix after bankruptcy.", []),
  "dependence": ("Needing someone or something.", "The village's dependence on one well was risky.", [])},
 C("gracian", [
  ("Maxim v", "Create a Feeling of Dependence", "Be needed",
   "Gracián: people honour you while they need you, and forget you once satisfied. Keep others hoping rather than fully paid off.",
   "The wise man would rather see men needing him than thanking him.",
   "It's better to be needed than just thanked.", "The plumber everyone calls back because nobody else understands the old pipes."),
  ("Maxim vii", "Avoid Victories over Superiors", "Don't beat the boss",
   "Everyone hates being outshone, and bosses most of all. Hide your advantages from those above you.",
   "All victories breed hate, and that over your superior is foolish or fatal.",
   "Winning against your boss makes them hate you.", "Not correcting your manager's spelling in front of the whole team."),
  ("Maxim iii", "Keep Matters in Suspense", "Don't show all your cards",
   "Novelty creates admiration. Don't announce everything at once; a little mystery makes people watch you.",
   "It is both useless and insipid to play with the cards on the table.",
   "Revealing everything at once is pointless and dull.", "Teasing a product launch instead of posting all details on day one."),
  ("Maxim xxvi", "Find out Each Man's Thumbscrew", "Know what moves people",
   "Everyone has a pressure point — fame, money, pleasure. Find it and you know how to move them.",
   "Find out each Man's Thumbscrew. 'Tis the art of setting their wills in action.",
   "Learn what drives each person; that's how you motivate them.", "One friend joins the trip for food, another for photos — invite each with their reason."),
  ("Maxim xliii", "Think with the Few", "Think freely, speak plainly",
   "Swimming against the stream is dangerous. Hold your rare opinions among a few trusted friends, and speak like everyone else in public.",
   "Think with the Few and speak with the Many.",
   "Think independently, but talk the way most people do.", "Keeping your unusual views off the family WhatsApp group."),
  ("Maxim xxxviii", "Leave Your Luck while Winning", "Quit while ahead",
   "Good players leave the table while they're winning. A good retreat is as fine as a brave attack.",
   "Leave your Luck while Winning. All the best players do it. A fine retreat is as good as a gallant attack.",
   "Stop while you're winning; a smart exit is as good as a bold move.", "Selling your shares after a big gain instead of waiting for more."),
  ("Maxim lxxxiii", "Allow Yourself some venial Fault", "A small flaw protects you",
   "Envy attacks perfection. A small harmless flaw makes your talent easier for others to accept.",
   "Allow Yourself some venial Fault. Some such carelessness is often the greatest recommendation of talent.",
   "A small harmless flaw makes your talents more likeable.", "The brilliant student who laughs at her own terrible handwriting."),
  ("Maxim lxxxi", "Renew your Brilliance", "Keep reinventing",
   "Talent grows stale and fame fades. Like the phoenix, renew yourself so you don't become old news.",
   "Renew your Brilliance. 'Tis the privilege of the Phoenix.",
   "Keep refreshing yourself so you stay interesting.", "A singer who changes style every few years to stay fresh."),
 ])),

# ---------------------------------------------------------------- Maxims
book(dict(id="maxims", title="Maxims", short="La Rochefoucauld", author="François de La Rochefoucauld", year="1665",
          translator="J. W. Willis Bund & J. Hain Friswell, 1871 (public domain, Project Gutenberg #9105)", era="baroque", shelf="Courtly Wisdom",
          blurb="A French duke's razor-sharp one-liners about vanity, self-interest and the hidden motives behind our 'virtues'."),
 {"self-love": ("Love of yourself; vanity.", "Self-love made him fish for compliments.", []),
  "disinterestedness": ("Not caring about personal gain.", "Her disinterestedness made her a fair judge.", []),
  "hypocrisy": ("Pretending to have virtues you don't have.", "Preaching saving money while splurging is hypocrisy.", []),
  "homage": ("Respect shown publicly.", "The crowd paid homage to the old singer.", []),
  "misfortunes": ("Bad events; bad luck.", "Their misfortunes included a flood and a fire.", [])},
 C("roche", [
  ("Maxim 39", "", "Self-interest speaks every language",
   "Self-interest can pretend to be anything — even someone who cares nothing for gain.",
   "Interest speaks all sorts of tongues and plays all sorts of characters; even that of disinterestedness.",
   "Self-interest can disguise itself as anything, even generosity.", "A 'free' trial that quietly turns into a monthly charge."),
  ("Maxim 19", "", "Others' troubles are light",
   "We all have plenty of strength to bear other people's misfortunes.",
   "We have all sufficient strength to support the misfortunes of others.",
   "It's easy to be brave about other people's problems.", "Telling a friend 'it's just a breakup, you'll be fine.'"),
  ("Maxim 218", "", "Hypocrisy pays respect",
   "When people fake virtue, they admit that virtue is valuable.",
   "Hypocrisy is the homage vice pays to virtue.",
   "Pretending to be good shows that even bad people respect goodness.", "A polluting company adding green leaves to its logo."),
  ("Maxim 38", "", "Promises and fears",
   "We promise according to our hopes and deliver according to our fears.",
   "We promise according to our hopes; we perform according to our fears.",
   "We promise big when hopeful, and do less when afraid.", "Promising to finish the project in a week, then delivering half because of worry."),
  ("Maxim 2", "", "The best flatterer",
   "Nobody flatters you as well as your own self-love.",
   "Self-love is the greatest of flatterers.",
   "Your own vanity praises you more than anyone else does.", "Thinking you sang perfectly until you hear the recording."),
  ("Maxim 49", "", "Never as happy or sad",
   "We are never as happy or as unhappy as we imagine.",
   "We are never so happy or so unhappy as we suppose.",
   "Good and bad times are rarely as extreme as they feel.", "The rejection that felt like the end turned out to be a small bump."),
 ]))

COMING = []  # shelves announced in the catalog, not books

if __name__ == "__main__":
    import json, pathlib
    out = pathlib.Path(__file__).parent.parent / "library-only/books"
    out.mkdir(parents=True, exist_ok=True)
    for about, gl, cards in BOOKS:
        about = dict(about, version=2, self_src=cards[0]["src"], cover=f"{about['id']}_cover")
        build(about, gl, cards, credits_file="commons/credits.json", out_dir=out)
