from deep_build import K, N

SRC = "sunzi"
TARGET = 52

BRIDGE = {
    "Chapter II": "Plans are made in the temple before a war. Now Sun Tzu counts what a war actually costs.",
    "Chapter III": "Long wars ruin a country. So the best victory is the one that needs no fighting at all.",
    "Chapter IV": "If you can't win without a fight, first make yourself impossible to beat.",
    "Chapter V": "Being unbeatable is defence. Winning takes energy: the force of direct and surprise moves combined.",
    "Chapter VI": "Energy must be aimed. Here Sun Tzu teaches how to strike where the enemy is weak.",
    "Chapter VII": "Knowing where to strike, you must get there first. The hardest art: manoeuvring.",
    "Chapter VIII": "On the march, rules must bend. A general must know when to break them.",
    "Chapter IX": "From principles to practice: camping, crossing rivers, and reading the enemy's camp.",
    "Chapter X": "Every battlefield has its own shape. Six kinds of ground, and six ways to lose.",
    "Chapter XI": "Ground also changes how soldiers feel. Nine situations, from home soil to death ground.",
    "Chapter XII": "Beyond men and ground there are other weapons. The most dangerous is fire.",
    "Chapter XIII": "Every chapter has needed one thing above all: knowing the enemy. The book ends with how to get it.",
}

GLOSS = {
    "stratagem": ("A clever plan or trick to outwit someone.", "Leaving the lights on was her stratagem to fool burglars.", ["stratagems"]),
    "calculations": ("Careful thinking and counting before deciding.", "His calculations showed the trip would cost more than the hotel.", []),
    "foreknowledge": ("Knowing something before it happens.", "With foreknowledge of the exam topics, she studied only what mattered.", []),
}

C = lambda r: f"Chapter {r}"

PAGES = [
    K(0),
    N(C("I"), None, "Five things to weigh",
      "Before any war, Sun Tzu says, compare both sides on five things: the moral law that unites people with their ruler, heaven (weather and seasons), earth (distance and terrain), the commander's qualities, and method and discipline. Know these and you will win; ignore them and you will lose.",
      "These five heads should be familiar to every general: he who knows them will be victorious; he who knows them not will fail.",
      "Every leader must know these five factors; those who know them win, those who don't fail.", "Before opening a shop, check the location, the timing, your skills, your team and your money.",
      "Chinese general portrait Qing"),
    K(1),
    N(C("I"), None, "Win in the planning room",
      "Victory starts long before the battle. The general who wins has made many calculations beforehand; the one who loses made few. Sun Tzu says he can predict the winner just by seeing who planned more.",
      "Thus do many calculations lead to victory, and few calculations to defeat: how much more no calculation at all!",
      "Careful planning leads to winning, little planning to losing, and none at all is hopeless.", "The team that studied the other side's past matches usually wins the final.",
      "Chinese scholars studying scroll painting"),
    K(2),
    N(C("II"), None, "War drains the country",
      "An army costs a thousand ounces of silver a day. Drag a campaign on and weapons grow dull, courage fades and the treasury empties, until even the wisest adviser cannot repair the damage.",
      "if the campaign is protracted, the resources of the State will not be equal to the strain",
      "A long war will exhaust the country's money and supplies.", "A long court case can cost both sides more than the thing they were fighting over.",
      "Chinese army supply wagons painting"),
    K(3),
    N(C("II"), None, "Anger and rewards",
      "Soldiers fight hard for two reasons: anger at the enemy and the hope of reward. Sun Tzu advises rewarding the first men who capture enemy chariots, and treating captured soldiers kindly so they may join you.",
      "Now in order to kill the enemy, our men must be roused to anger; that there may be advantage from defeating the enemy, they must have their rewards.",
      "People fight harder when they feel strongly and know they'll be rewarded.", "A sales team works hardest when the target matters to them and the bonus is real.",
      "Chinese war chariot bronze"),
    N(C("III"), None, "Take it whole",
      "The best result is to take the enemy's country, army or town intact, not smashed. Destruction wastes what you could have gained. The aim is to win the prize, not wreck it.",
      "the best thing of all is to take the enemy’s country whole and intact",
      "The best victory captures everything undamaged.", "Buying a rival company and keeping its good staff beats driving it out of business.",
      "Chinese walled city painting"),
    K(4),
    N(C("III"), None, "Know when to run",
      "Size up the odds honestly. If you are equal, fight. If you are slightly weaker, avoid battle. If you are much weaker, get away. A small force that stubbornly fights a big one is simply captured.",
      "if quite unequal in every way, we can flee from him.",
      "When the other side is far stronger in every way, get away.", "A small shop shouldn't start a price war with a giant chain.",
      "Chinese cavalry retreat painting"),
    K(5),
    K(6),
    N(C("IV"), None, "Knowing isn't doing",
      "You can understand exactly how to win and still be unable to do it, because victory also depends on the enemy making a mistake. What you can control is not losing.",
      "One may know how to conquer without being able to do it.",
      "Knowing how to win is not the same as being able to win.", "You can know every rule of cricket and still get bowled first ball.",
      "Chinese chess players painting"),
    K(7),
    N(C("IV"), None, "Winning made to look easy",
      "The truly great general's victories look ordinary. He wins where winning is easy, because he set it up that way. No one praises his genius, because the battle never looked hard.",
      "What the ancients called a clever fighter is one who not only wins, but excels in winning with ease.",
      "Real skill makes winning look effortless.", "A great host's party seems to run itself because of weeks of quiet preparation.",
      "Chinese landscape with army painting"),
    K(8),
    N(C("V"), None, "Five notes, endless songs",
      "There are only five musical notes, five colours and five tastes, yet their combinations are endless. Battle is the same: only direct and surprise attacks, but they mix into countless moves.",
      "There are not more than five musical notes, yet the combinations of these five give rise to more melodies than can ever be heard.",
      "A few simple elements can combine into endless variety.", "Twenty-six letters make every book ever written.",
      "Chinese musicians playing qin painting"),
    K(9),
    N(C("V"), None, "The drawn crossbow",
      "Energy is like a crossbow bent tight; decision is the moment of pulling the trigger. Build up force patiently, then release it all at once, at the right instant.",
      "Energy may be likened to the bending of a crossbow; decision, to the releasing of the trigger.",
      "Build up strength, then act decisively at the right moment.", "A sprinter crouched at the blocks, then exploding at the gun.",
      "Chinese crossbow"),
    K(10),
    N(C("VI"), None, "Strike where they must defend",
      "Go where the enemy must rush to protect something, and march fast to places they don't expect. Make them react to you, and they will be tired and scattered when the fight comes.",
      "Appear at points which the enemy must hasten to defend; march swiftly to places where you are not expected.",
      "Threaten what the enemy must protect and go where they won't expect.", "A chess player who attacks the queen forces the opponent to play their game.",
      "Chinese fortress mountain pass painting"),
    K(11),
    N(C("VI"), None, "Adapt to win",
      "There are no fixed shapes in war, just as water has no fixed shape. The general who changes his tactics to fit the enemy and wins deserves to be called heaven-born.",
      "He who can modify his tactics in relation to his opponent and thereby succeed in winning, may be called a heaven-born captain.",
      "A leader who adapts to each opponent and wins is truly gifted.", "A teacher who changes the lesson when the class is lost.",
      "Chinese river landscape painting Song"),
    N(C("VII"), None, "Turn the long way short",
      "Manoeuvring is hard because you must make the roundabout route the quick one, and turn bad luck into an advantage. Take a winding road, distract the enemy with bait, and still arrive first.",
      "The difficulty of tactical manœuvering consists in turning the devious into the direct, and misfortune into gain.",
      "The skill is making the indirect route faster and turning setbacks into gains.", "Taking the back roads in a traffic jam and still arriving first.",
      "Chinese army crossing mountains painting"),
    K(12),
    N(C("VII"), None, "Use local guides",
      "You cannot lead an army through country you don't know: its mountains and forests, its swamps and cliffs. Without local guides you can't turn the land to your advantage.",
      "We shall be unable to turn natural advantages to account unless we make use of local guides.",
      "You can't use the land well without people who know it.", "Asking a local which street food stall is actually good.",
      "Chinese mountain path travellers painting"),
    K(13),
    K(14),
    N(C("VIII"), None, "Weigh both sides",
      "A wise leader always thinks about gains and losses together. Seeing the risks in an advantage keeps him careful; seeing the chance in a danger keeps him hopeful.",
      "Hence in the wise leader’s plans, considerations of advantage and of disadvantage will be blended together.",
      "Smart planners consider both the benefits and the risks.", "Before taking a job, weigh the higher salary against the longer commute.",
      "Chinese official at desk painting"),
    N(C("VIII"), None, "Opportunity inside trouble",
      "In the middle of difficulties, stay ready to grab any advantage. That readiness is often the way out of misfortune.",
      "If, on the other hand, in the midst of difficulties we are always ready to seize an advantage, we may extricate ourselves from misfortune.",
      "Even in hard times, watch for openings; they can get you out.", "A business that lost customers in lockdown and started delivering instead.",
      "Chinese boat in storm painting"),
    K(15),
    K(16),
    N(C("IX"), None, "Look after your soldiers",
      "Camp on high, dry, sunny ground and keep the army healthy. A sick army cannot fight, and an army free of disease is already halfway to victory.",
      "camp on hard ground, the army will be free from disease of every kind,",
      "An army kept free of disease is on its way to victory.", "A company that gives proper breaks gets fewer sick days.",
      "Chinese military camp tents painting"),
    N(C("IX"), None, "Never underestimate them",
      "The general who doesn't think ahead and laughs at his opponents will end up their prisoner. Respect every enemy enough to prepare for them.",
      "He who exercises no forethought but makes light of his opponents is sure to be captured by them.",
      "Underestimating an opponent and not planning will lead to defeat.", "The champion who skipped training because the opponent was 'easy'.",
      "Chinese prisoners war painting"),
    K(17),
    K(18),
    N(C("X"), None, "Six ways to lose",
      "Sun Tzu lists six ways an army defeats itself, all the general's fault: flight, insubordination, collapse, ruin, disorganisation and rout. None of them is bad luck; every one comes from poor leadership.",
      "These are six ways of courting defeat",
      "There are six ways a leader brings defeat on themselves.", "Most failed projects fail from the same few mistakes: unclear plans, weak leaders, poor teamwork.",
      "Chinese battle defeat painting"),
    K(19),
    N(C("X"), None, "Never at a loss",
      "The experienced soldier, once moving, is never confused, and once the camp is struck, he is never stuck. He knows himself, the enemy, the weather and the ground.",
      "Hence the experienced soldier, once in motion, is never bewildered; once he has broken camp, he is never at a loss.",
      "Experience means you're never lost once things start.", "A seasoned traveller who stays calm when the flight is cancelled.",
      "Chinese soldier armour painting"),
    K(20),
    N(C("XI"), None, "Speed is everything",
      "Rapidity is the essence of war. Move while the enemy is unready, take roads he doesn't expect, and attack where he has not prepared.",
      "Rapidity is the essence of war",
      "Speed is the most important thing in war.", "The first company to launch a good idea often wins the market.",
      "Chinese horseman galloping painting"),
    K(21),
    N(C("XI"), None, "The maiden and the hare",
      "At first look shy and harmless, like a nervous young woman, so the enemy relaxes and leaves an opening. Then move as fast as a running hare, and it will be too late for them to resist.",
      "exhibit the coyness of a maiden, until the enemy gives you an opening; afterwards emulate the rapidity of a running hare",
      "Look weak and quiet until they open up, then move with sudden speed.", "A quiet player who seems harmless until the last minute, then scores.",
      "hare painting Chinese"),
    N(C("XI"), None, "Share good news, hide the bad",
      "Sun Tzu advises showing the troops what's going well and saying nothing of what looks grim. Morale is a weapon too, and leaders guard it.",
      "When the outlook is bright, bring it before their eyes; but tell them nothing when the situation is gloomy.",
      "Show your team the positive things and keep the worrying ones to yourself.", "A captain who keeps the team focused on what they're doing well at half time.",
      "Chinese general addressing troops"),
    K(22),
    N(C("XII"), None, "Plan ahead, build up",
      "The wise ruler plans well in advance; the good general builds up his strength. Neither acts in a hurry, and neither wastes what they have.",
      "The enlightened ruler lays his plans well ahead; the good general cultivates his resources.",
      "Good leaders plan early and strengthen what they have.", "Saving a little each month for a goal years away.",
      "Chinese emperor court painting"),
    K(23),
    N(C("XII"), None, "Some losses can't be undone",
      "Anger can turn to joy and annoyance to happiness again. But a destroyed kingdom never comes back, and the dead can't be brought back to life. So the wise ruler is careful before starting a war.",
      "But a kingdom that has once been destroyed can never come again into being;",
      "A kingdom once destroyed can never be rebuilt.", "Words said in anger can end a friendship forever.",
      "ruined Chinese palace painting"),
    N(C("XIII"), None, "Years of waiting, one day of battle",
      "Armies can face each other for years for a victory decided in a single day. Being stingy with the money spent on information is, Sun Tzu says, the height of cruelty, because ignorance costs lives.",
      "Hostile armies may face each other for years, striving for the victory which is decided in a single day.",
      "Long preparation leads to one decisive day.", "Years of practice for an Olympic final that lasts ten seconds.",
      "Chinese armies facing each other painting"),
    K(24),
    K(25),
    N(C("XIII"), None, "Be subtle",
      "Sun Tzu's last advice on spies is a whisper: be subtle, be subtle, and use spies for everything. Information gathered quietly decides more battles than swords.",
      "Be subtle! be subtle! and use your spies for every kind of business.",
      "Be quiet and clever, and gather information in every situation.", "Listening more than you talk in a negotiation.",
      "Chinese scholar whispering painting"),
]
