from deep_build import K, N

SRC = "dhamma"
TARGET = 40

P = ["Part One", "Part Two", "Part Three", "Part Four", "Part Five", "Part Six", "Part Seven", "Part Eight"]
BRIDGE = {
    P[1]: "Part One showed that everything begins in the mind. Part Two contrasts the fool and the wise.",
    P[2]: "Wisdom shows in a life. Part Three weighs one good day against a hundred wasted years.",
    P[3]: "Every deed comes back. Part Four is about punishment, ageing, and the self that must do the work.",
    P[4]: "If the self must do it, where can it find help? Part Five turns to the world, the Buddha and happiness.",
    P[5]: "Happiness has enemies: clinging, anger and ignorance. Part Six names them.",
    P[6]: "What does a truly good person look like? Part Seven describes the just and the path they walk.",
    P[7]: "The last chapters picture the tamed mind: the elephant, the lotus, and the one who is free.",
}

GLOSS = {
    "earnestness": ("Serious, wholehearted effort; staying alert.", "She studied with real earnestness before the exam.", []),
    "nirvana": ("In Buddhism, freedom from suffering and desire.", "Monks seek nirvana through meditation.", []),
    "fetters": ("Chains; things that hold you back.", "Fear of failure can be the fetters on your dreams.", []),
}

def c(roman, name):
    return f"Chapter {roman} · {name}"

PAGES = [
    K(0, ch=P[0], chTitle=c("I", "The Twin-Verses")), K(1, ch=P[0], chTitle=c("I", "The Twin-Verses")), K(2, ch=P[0], chTitle=c("I", "The Twin-Verses")),
    N(P[0], c("I", "The Twin-Verses"), "Quarrels end with the end in view",
      "Most people forget that everyone must die. Those who remember it stop quarrelling at once, because most fights look small against that fact.",
      "The world does not know that we must all come to an end here;--but those who know it, their quarrels cease at once.",
      "Remembering we all die makes quarrels seem pointless.", "Making up with a sibling after a family funeral.",
      "Buddha teaching Ajanta"),
    K(3, ch=P[0], chTitle=c("II", "On Earnestness")),
    N(P[0], c("II", "On Earnestness"), "The racer among hacks",
      "Among careless people, the alert person moves ahead like a racehorse leaving an old nag behind. Wakefulness is the Buddha's word for living deliberately.",
      "Earnest among the thoughtless, awake among the sleepers, the wise man advances like a racer, leaving behind the hack.",
      "The alert person races ahead of the careless.", "The student who pays attention in class while others scroll.",
      "Mughal horse painting"),
    K(4, ch=P[0], chTitle=c("III", "Thought")),
    N(P[0], c("III", "Thought"), "Guard your thoughts",
      "Thoughts are slippery and sneaky; they run wherever they like. Guarding them is hard, but a well-guarded mind brings happiness.",
      "Let the wise man guard his thoughts, for they are difficult to perceive, very artful, and they rush wherever they list: thoughts well guarded bring happiness.",
      "Watch your thoughts carefully; a guarded mind is happy.", "Catching a negative thought spiral before it ruins your evening.",
      "Buddha meditating painting"),
    N(P[1], c("IV", "Flowers"), "The scent of virtue",
      "Sandalwood and jasmine smell sweet only so far, and only with the wind. The fragrance of good people travels in every direction, even against the wind.",
      "the perfume of those who possess virtue rises up to the gods as the highest",
      "A good person's goodness spreads further than any perfume.", "A kind teacher remembered by students decades later.",
      "lotus flowers painting India"),
    K(5, ch=P[1], chTitle=c("V", "The Fool")),
    N(P[1], c("V", "The Fool"), "Sweet like honey, at first",
      "While a wrong deed hasn't yet caught up with you, it tastes sweet like honey. When it ripens, the fool suffers.",
      "As long as the evil deed done does not bear fruit, the fool thinks it is like honey; but when it ripens, then the fool suffers grief.",
      "Wrongdoing feels fine until its consequences arrive.", "Copying homework feels easy until the exam comes.",
      "Ajanta cave painting"),
    N(P[1], c("V", "The Fool"), "Your own worst enemy",
      "Foolish people are their own greatest enemies; their bad deeds bear bitter fruit for themselves first.",
      "Fools of little understanding have themselves for their greatest enemies, for they do evil deeds which must bear bitter fruits.",
      "Fools harm themselves most of all.", "Lying to a friend and then losing the friendship.",
      "Jataka tale painting"),
    K(6, ch=P[1], chTitle=c("VI", "The Wise Man")),
    N(P[1], c("VI", "The Wise Man"), "Choose your friends",
      "Don't make friends with the wicked or the mean. Keep company with the good, the best of people.",
      "Do not have evil-doers for friends, do not have low people for friends: have virtuous people for friends, have for friends the best of men.",
      "Choose good people as friends.", "Joining a study group of serious students.",
      "Buddha with disciples painting"),
    N(P[2], c("VII", "The Venerable"), "Like birds in the air",
      "The path of a free person is as hard to trace as the flight of birds through the sky. They leave no track, because they cling to nothing.",
      "his path is difficult to understand, like that of birds in the air",
      "A free person's path is as hard to follow as birds in flight.", "A calm person whose choices puzzle those chasing status.",
      "birds flying Indian miniature"),
    K(7, ch=P[2], chTitle=c("VIII", "The Thousands")),
    N(P[2], c("VIII", "The Thousands"), "One good day",
      "Better one day lived with virtue and reflection than a hundred years of wild, careless living.",
      "But he who lives a hundred years, vicious and unrestrained, a life of one day is better if a man is virtuous and reflecting.",
      "One day of good living beats a hundred careless years.", "One meaningful afternoon helping someone versus a year of wasted weekends.",
      "Indian sage portrait painting"),
    N(P[2], c("IX", "Evil"), "Drop by drop",
      "Don't take small wrongs lightly. A water jar fills drop by drop, and a fool fills up with wrongdoing a little at a time.",
      "Even by the falling of water-drops a water-pot is filled; the fool becomes full of evil, even if he gather it little by little.",
      "Small wrongs add up, like drops filling a pot.", "Little lies that pile into a reputation for dishonesty.",
      "Indian woman water pot painting"),
    N(P[2], c("IX", "Evil"), "Small good counts too",
      "Don't take small good deeds lightly either. The wise fill up with goodness the same way, drop by drop.",
      "Let no man think lightly of good, saying in his heart, It will not come nigh unto me.",
      "Small good deeds matter as much as small bad ones.", "Holding the door every day builds a kind character.",
      "Mahajanaka Jataka"),
    N(P[3], c("X", "Punishment"), "Harsh words echo",
      "Don't speak harshly to anyone. People answer in the same tone, and angry words bring pain back to you.",
      "Do not speak harshly to anybody; those who are spoken to will answer thee in the same way.",
      "Speak harshly and you'll be spoken to harshly.", "Snapping at a waiter and getting slow service in return.",
      "Akbarnama court"),
    N(P[3], c("XI", "Old Age"), "What doesn't decay",
      "Kings' brilliant chariots wear out, and the body ages too. But the goodness of good people never decays.",
      "The brilliant chariots of kings are destroyed, the body also approaches destruction, but the virtue of good people never approaches destruction",
      "Everything wears out except true goodness.", "A grandparent's kindness outlives the house they built.",
      "Konark Sun Temple chariot wheel"),
    N(P[3], c("XII", "Self"), "Master of yourself",
      "Someone who has mastered themself has found a master few people ever find. The self is its own best lord.",
      "With self well subdued, a man finds a lord such as few can find.",
      "Mastering yourself gives you the best guide there is.", "Someone who stays calm in a crisis because they've trained themselves.",
      "seated monk painting"),
    N(P[3], c("XII", "Self"), "You do it to yourself",
      "Wrong is done by yourself, and you suffer for it yourself; you avoid wrong yourself, and you purify yourself. No one can purify another.",
      "By oneself the evil is done, by oneself one suffers; by oneself evil is left undone, by oneself one is purified.",
      "You are responsible for your own wrongs and your own cleansing.", "No one else can make you stop a bad habit; you have to.",
      "Varanasi ghats painting"),
    N(P[4], c("XIII", "The World"), "The moon from clouds",
      "Someone who was once careless and then becomes wise lights up the world, like the moon slipping out of the clouds.",
      "He who formerly was reckless and afterwards became sober, brightens up this world, like the moon when freed from clouds.",
      "Someone who reforms lights up the world.", "A former troublemaker who becomes the most helpful kid in class.",
      "moon clouds Indian painting"),
    N(P[4], c("XIV", "The Buddha"), "Patience",
      "The awakened ones call patience the highest discipline. Someone who strikes or insults others is no true seeker.",
      "The Awakened call patience the highest penance, long-suffering the highest Nirvana",
      "Patience is the highest spiritual practice.", "Waiting calmly in a long queue without complaining.",
      "Buddha statue Sarnath"),
    N(P[4], c("XV", "Happiness"), "Health and contentment",
      "Health is the greatest gift, contentment the greatest wealth, trust the best relationship, and freedom the highest happiness.",
      "Health is the greatest of gifts, contentedness the best riches",
      "Good health and being content are the real riches.", "Being grateful for a normal healthy day.",
      "Indian garden painting"),
    N(P[4], c("XV", "Happiness"), "Company of the wise",
      "Travelling with fools is long and painful, like living with an enemy. Being with the wise is a pleasure, like meeting family.",
      "company with the wise is pleasure, like meeting with kinsfolk",
      "Spending time with wise people feels like being with family.", "A mentor whose conversations always leave you better.",
      "Saptarishi"),
    N(P[5], c("XVI", "Pleasure"), "Affection and fear",
      "From what we cling to come grief and fear. Someone free of clinging knows neither. Love without grasping is the point.",
      "From affection comes grief, from affection comes fear; he who is free from affection knows neither grief nor fear.",
      "Clinging to people and things brings sorrow and fear.", "Worrying constantly about losing what you love.",
      "Indian lovers painting"),
    K(8, ch=P[5], chTitle=c("XVII", "Anger")),
    N(P[5], c("XVII", "Anger"), "No one is always blamed",
      "There never was, never will be, and is not now anyone who is only blamed or only praised. Don't take either too seriously.",
      "There never was, there never will be, nor is there now, a man who is always blamed, or a man who is always praised.",
      "No one is only blamed or only praised.", "Even the best player gets booed sometimes.",
      "Indian crowd painting"),
    N(P[5], c("XVIII", "Impurity"), "The worst stain",
      "Of all the stains on a person, ignorance is the worst. Get rid of it and you are free of the rest.",
      "But there is a taint worse than all taints,--ignorance is the greatest taint.",
      "Ignorance is the worst flaw of all.", "Many mistakes come from simply not knowing better.",
      "palm-leaf manuscript Buddhist"),
    N(P[6], c("XIX", "The Just"), "Talk isn't learning",
      "A person isn't learned because they talk a lot. Someone patient, free of hatred and fear, is the truly learned one.",
      "A man is not learned because he talks much; he who is patient, free from hatred and fear, he is called learned.",
      "Real learning shows in patience, not in talking.", "The quiet expert versus the loud know-it-all.",
      "Indian scholar manuscript painting"),
    N(P[6], c("XIX", "The Just"), "What makes an elder",
      "Grey hair doesn't make an elder. Truth, virtue, love, restraint and moderation do.",
      "He in whom there is truth, virtue, love, restraint, moderation, he who is free from impurity and is wise, he is called an elder.",
      "Respect comes from character, not age.", "A young volunteer everyone turns to for advice.",
      "Bodhidharma"),
    N(P[6], c("XX", "The Way"), "Three roads to keep clear",
      "Guard your speech, restrain your mind, and do no wrong with your body. Keep these three clear and you will walk the path of the wise.",
      "Let a man but keep these three roads of action clear, and he will achieve the way which is taught by the wise.",
      "Keep your words, thoughts and actions clean.", "Before acting, checking what you say, think and do.",
      "Borobudur relief"),
    N(P[6], c("XXI", "Miscellaneous"), "Upside-down priorities",
      "Careless people neglect what should be done and do what shouldn't, and their wants keep growing.",
      "What ought to be done is neglected, what ought not to be done is done; the desires of unruly, thoughtless people are always increasing.",
      "Thoughtless people do the wrong things and skip the right ones.", "Gaming all night while the assignment waits.",
      "Company painting bazaar"),
    N(P[7], c("XXII", "The Downward Course"), "No regrets",
      "A bad deed is better left undone, because you'll regret it. A good deed is better done, because you won't.",
      "An evil deed is better left undone, for a man repents of it afterwards; a good deed is better done, for having done it, one does not repent.",
      "Skip the wrong you'd regret; do the good you won't.", "Not posting the angry comment; sending the thank-you note.",
      "Indian temple painting"),
    N(P[7], c("XXIII", "The Elephant"), "Tame yourself",
      "Tamed mules, fine horses and great elephants are valuable. But someone who tames themself is better still.",
      "Mules are good, if tamed, and noble Sindhu horses, and elephants with large tusks; but he who tames himself is better still.",
      "Taming yourself is worth more than taming any animal.", "Controlling your temper is harder and better than any skill.",
      "Mughal elephant painting"),
    N(P[7], c("XXIV", "Thirst"), "Water off a lotus",
      "Whoever overcomes craving, so hard to conquer, finds suffering falls away like water drops off a lotus leaf.",
      "He who overcomes this fierce thirst, difficult to be conquered in this world, sufferings fall off from him, like water-drops from a lotus leaf.",
      "Beat craving and suffering slides off you.", "Once you stop needing the latest gadget, adverts stop bothering you.",
      "Raja Ravi Varma"),
    N(P[7], c("XXV", "The Bhikshu"), "Knowledge and meditation",
      "Without knowledge there's no meditation; without meditation, no knowledge. Whoever has both is close to freedom.",
      "Without knowledge there is no meditation, without meditation there is no knowledge",
      "Understanding and quiet reflection need each other.", "Studying a subject and then thinking it over quietly.",
      "monk meditating cave painting"),
    N(P[7], c("XXVI", "The Brahmana"), "Unshackled",
      "The Dhammapada ends with portraits of the truly free: those who have cut every chain, never tremble, and depend on no one.",
      "Him I call indeed a Brahmana who has cut all fetters, who never trembles, is independent and unshackled.",
      "The truly free person has broken every chain and fears nothing.", "Someone so at peace that criticism and praise barely touch them.",
      "Buddha enlightenment painting"),
]
