from deep_build import K, N

SRC = "enchiridion"
TARGET = 30

P1, P2, P3, P4 = "Part One", "Part Two", "Part Three", "Part Four"
T1 = "What Is Up to Us · sections I–XI"
T2 = "Making Progress · sections XII–XXIV"
T3 = "Among Other People · sections XXV–XLIII"
T4 = "The Philosopher's Way · sections XLIV–LIII"

BRIDGE = {
    P2: "Part One drew the line between what is ours and what isn't. Part Two is about living by that line, day after day.",
    P3: "Progress happens among people who mock, insult and tempt us. Part Three is about them.",
    P4: "The handbook closes with how a real philosopher behaves: quietly, without show, starting now.",
}

GLOSS = {
    "aversion": ("A strong dislike; wanting to avoid something.", "Her aversion to spiders made gardening hard.", []),
    "externals": ("Things outside your mind: money, body, fame, other people.", "He stopped measuring himself by externals like his car.", []),
    "proficient": ("Someone skilled and advanced.", "After years of practice she became proficient at the violin.", []),
}

PAGES = [
    K(0, ch=P1, chTitle=T1),
    N(P1, T1, "Fear only what you control",
      "If you dread only the bad things that are up to you, like your own unkindness, you will never meet what you dread. But fear sickness, death or poverty, and you'll live in misery, because those were never yours to control.",
      "aversion, then, from all things that are not within our power, and apply it to things undesirable which are within our power.",
      "Stop dreading what you can't control; avoid only the bad things you can.", "Worry about whether you studied, not whether the exam will be hard.",
      "Epictetus engraving"),
    N(P1, T1, "Expect the crowded bath",
      "Before any activity, picture what usually happens: at the public baths, people splash, shove, shout and steal. Expect it, and you can keep your calm when it happens, because calm was part of what you came for.",
      "When you set about any action, remind yourself of what nature the action is.",
      "Before doing something, remind yourself what it usually involves.", "Expecting traffic before a festival trip keeps you from losing your temper.",
      "Roman baths painting Alma-Tadema"),
    K(1, ch=P1, chTitle=T1),
    N(P1, T1, "Proud of the horse",
      "If a horse could boast 'I am handsome', fine. But when you boast 'I have a handsome horse', you are proud of the horse's merit, not yours. Be proud only of what is truly your own: how you use your mind.",
      "Be not elated at any excellence not your own.",
      "Don't be proud of good things that aren't really yours.", "Showing off a rich parent's car as if you earned it.",
      "Roman horse statue bronze"),
    N(P1, T1, "Don't stray from the ship",
      "On a voyage you may go ashore and gather shells, but keep listening for the captain's call. Life is the same: enjoy what comes, but be ready to leave it all when called, and if you are old, stay close to the ship.",
      "But if you are old, never go far from the ship, lest you should be missing when called for.",
      "As you age, stay ready for life's end.", "Enjoying the party but keeping your phone charged for the ride home.",
      "Roman ship mosaic"),
    K(2, ch=P1, chTitle=T1),
    K(3, ch=P1, chTitle=T1),
    N(P1, T1, "Find the right tool",
      "Whatever happens, ask which of your strengths it calls for. Temptation calls for self-control, pain for courage, insults for patience. Practise this and events won't overwhelm you.",
      "Upon every accident, remember to turn toward yourself and inquire what faculty you have for its use.",
      "With every event, ask what inner strength it needs from you.", "When a teammate fails, you reach for patience, not blame.",
      "Hercules statue Farnese"),
    K(4, ch=P1, chTitle=T1),
    N(P2, T2, "The price of calm",
      "A little oil is spilled, a little wine stolen. Say: this is the price of peace of mind, and nothing comes free. Better your servant behaves badly than that you become miserable worrying about it.",
      "Is a little oil spilled or a little wine stolen?",
      "When small things go wrong, let them go; peace is worth more.", "Letting a lost umbrella stay lost instead of ruining your evening.",
      "Roman oil amphora"),
    N(P2, T2, "Content to look foolish",
      "If you want to grow, accept looking foolish about outward things like fashion and status. You can't chase both inner progress and outer approval at once.",
      "If you would improve, be content to be thought foolish and dull with regard to externals.",
      "To improve, accept that people may think you're uncool.", "Wearing old shoes so you can save for a course.",
      "Diogenes painting"),
    N(P2, T2, "Who is your master?",
      "Whoever can give or take away what you want is your master. To be free, want nothing that depends on others.",
      "Whoever then would be free, let him wish nothing, let him decline nothing, which depends on others; else he must necessarily be a slave.",
      "To be free, don't depend on others for what you want.", "If your mood depends on a reply, that person controls your day.",
      "Roman slave freedman relief"),
    K(5, ch=P2, chTitle=T2),
    K(6, ch=P2, chTitle=T2),
    N(P2, T2, "Every omen is lucky",
      "A raven croaks: an ill omen? Nothing it predicts touches your will. For a wise person every sign is lucky, because whatever happens, you can draw some good from it.",
      "For whatsoever happens, it belongs to me to derive advantage therefrom.",
      "Whatever happens, I can make something good of it.", "A rejected job application becomes practice for the next interview.",
      "raven painting"),
    N(P2, T2, "Unbeatable",
      "You can never be beaten if you only enter contests that are within your power to win: the contest with your own judgments.",
      "You can be unconquerable if you enter into no combat in which it is not in your own power to conquer.",
      "Fight only battles that depend on you, and you can't lose.", "Competing with your own past self instead of everyone online.",
      "Roman wrestlers mosaic"),
    N(P2, T2, "Your opinion provokes you",
      "It isn't the person who insults or hits you who affronts you; it's your opinion that they did. When someone provokes you, pause; with time you'll command yourself.",
      "When, therefore, anyone provokes you, be assured that it is your own opinion which provokes you.",
      "What really provokes you is your own view of what happened.", "Counting to ten before answering a rude comment.",
      "Roman orator statue"),
    N(P2, T2, "Keep death in view",
      "Keep death, exile and every frightening thing before your eyes daily, death most of all. You'll never think a small thought or want anything too much.",
      "Let death and exile, and all other things which appear terrible, be daily before your eyes, but death chiefly",
      "Remember daily that life ends; it puts everything in proportion.", "A health scare that makes someone stop sweating small stuff.",
      "memento mori mosaic Pompeii"),
    N(P2, T2, "Mockery passes",
      "When you start living by principle, people will laugh. Hold steady: the same people who mocked you will come to admire you. Give in, and you'll be mocked twice.",
      "For remember that, if you are persistent, those very persons who at first ridiculed will afterwards admire you.",
      "Keep going and those who mocked you will end up admiring you.", "Classmates who laughed at your early-morning runs later ask to join.",
      "Socrates teaching painting"),
    N(P3, T3, "Everything has a price",
      "Someone else was invited to dinner, and you weren't? He paid the price: flattery and attendance. If you won't pay it, don't complain you didn't get the dinner. You kept your dignity instead.",
      "You are unjust, then, and unreasonable if you are unwilling to pay the price for which these things are sold, and would have them for nothing.",
      "If you won't pay the price for something, don't expect to get it.", "Not getting promoted after refusing to flatter the boss, and being fine with it.",
      "Roman banquet fresco"),
    N(P3, T3, "Guard your mind",
      "You would be furious if someone handed your body to a passing stranger. Yet you hand your mind to anyone who insults you, letting them upset you. Be as protective of your mind as of your body.",
      "And do you feel no shame in delivering up your own mind to any reviler, to be disconcerted and confounded?",
      "Don't let anyone who insults you take control of your mind.", "Muting a troll rather than arguing for hours.",
      "Roman soldier shield"),
    N(P3, T3, "Count the cost first",
      "Before any undertaking, look at what comes before and after it. You want to win the Olympics? Then the diet, the training, the defeats. Many people try everything halfway and finish nothing.",
      "In every affair consider what precedes and what follows, and then undertake it.",
      "Before starting something, think about what it will really take.", "Researching what medical school demands before choosing it.",
      "Olympic athletes Greek vase"),
    N(P3, T3, "Mind your company",
      "However pure you are, keep company with the corrupt and you'll be corrupted too. Choose companions carefully; their habits rub off.",
      "For be assured that if a person be ever so pure himself, yet, if his companion be corrupted, he who converses with him will be corrupted likewise.",
      "Bad company corrupts even good people.", "Friends who skip class make it easier for you to skip too.",
      "Greek symposium painting"),
    N(P3, T3, "Don't fear being seen",
      "If you are sure an action is right, do it openly, even if people misunderstand. If it's wrong, don't do it at all. If it's right, why fear those who wrongly criticise you?",
      "When you do anything from a clear judgment that it ought to be done, never shrink from being seen to do it, even though the world should misunderstand it",
      "If you know it's right, do it openly, even if others misunderstand.", "Standing up for a bullied classmate though others laugh.",
      "Roman forum painting"),
    N(P3, T3, "The shoe that grew jewels",
      "Your body is the right measure for what you own, as a foot is for a shoe. Go beyond that and there's no limit: first a gilded shoe, then purple, then studded with jewels.",
      "For to that which once exceeds the fit measure there is no bound.",
      "Once you go beyond what you need, there's no stopping point.", "A phone upgrade that turns into buying every new model.",
      "Roman sandal"),
    K(7, ch=P3, chTitle=T3),
    N(P3, T3, "Two handles",
      "Everything has two handles: one you can carry it by, one you can't. If your brother wrongs you, don't grab it by 'he wronged me'. Take it by 'he is my brother, we grew up together', and you can bear it.",
      "Everything has two handles: one by which it may be borne, another by which it cannot.",
      "Every situation can be seen in a way that's bearable or unbearable.", "Remembering years of friendship when a friend lets you down once.",
      "Greek amphora two handles"),
    N(P4, T4, "Richer isn't better",
      "'I'm richer than you, so I'm better than you' doesn't follow. Richer means only that your possessions are greater. And you are neither your possessions nor your style.",
      "But you, after all, consist neither in property nor in style.",
      "You are not your money or your style.", "A neighbour's bigger house doesn't make them a better person.",
      "Roman coins hoard"),
    N(P4, T4, "Describe, don't judge",
      "Someone bathes quickly: don't say badly, say quickly. Someone drinks a lot: don't say wrongly, say a lot. Unless you know their reasons, describe what happened without judging it.",
      "Does anyone bathe hastily? Do not say that he does it ill, but hastily.",
      "Describe what people do without assuming they're wrong.", "'He left early' instead of 'he's lazy' when you don't know why.",
      "Roman bath house ruins"),
    N(P4, T4, "Sheep give wool",
      "Don't lecture people about your principles; live them. Sheep don't vomit up grass to show the shepherd how much they ate. They digest it and give wool and milk.",
      "For sheep do not hastily throw up the grass to show the shepherds how much they have eaten",
      "Show what you've learned through actions, not talk.", "A fit person who simply lives healthily instead of preaching about it.",
      "sheep and shepherd painting"),
    N(P4, T4, "Tell nobody",
      "If you train yourself to live simply, don't boast about it. If you're thirsty, rinse your mouth with water and tell no one. Discipline done for show is not discipline.",
      "when you are violently thirsty, just rinse your mouth with water, and tell nobody.",
      "Practise self-discipline quietly, without telling anyone.", "Fasting or saving money without announcing it.",
      "Roman water jug"),
    N(P4, T4, "Signs of progress",
      "How do you know you're making progress? You blame no one, praise no one, accuse no one, say nothing about yourself as if you were somebody. You watch yourself as you would an enemy in ambush.",
      "The marks of a proficient are that he censures no one, praises no one, blames no one, accuses no one",
      "Real progress shows when you stop blaming and judging others.", "Noticing you no longer gossip about colleagues.",
      "Roman philosopher bust"),
    N(P4, T4, "Now is the contest",
      "How long will you put off becoming who you could be? You're not a child anymore. The contest is now, the Olympics have begun and can't be postponed. Live as someone trying to be a Socrates.",
      "remember that now is the combat, now the Olympiad comes on, nor can it be put off",
      "The test is happening now; it can't be postponed.", "Starting the habit today instead of 'from Monday'.",
      "Olympia stadium"),
    N(P4, T4, "Practice first",
      "The most important part of philosophy is using its principles, not proving them. We spend our time on arguments and forget to live by them.",
      "The first and most necessary topic in philosophy is the practical",
      "The most important part of philosophy is putting it into practice.", "Reading about exercise is useless until you go for a walk.",
      "Stoa painting Athens"),
]
