from deep_build import K, N

SRC = "gita"
TARGET = 54

BRIDGE = {
    "Chapter II": "Arjuna has dropped his bow and refuses to fight. Krishna, his charioteer, begins to answer him.",
    "Chapter III": "Krishna has praised the steady, detached mind. Arjuna asks: then why act at all?",
    "Chapter IV": "Action is unavoidable. Now Krishna reveals who he is, and how knowledge frees action from its chains.",
    "Chapter V": "Knowledge or action, giving up or doing: Arjuna wants one plain answer.",
    "Chapter VI": "Both roads meet in a disciplined mind. This chapter is about training that mind.",
    "Chapter VII": "With the mind trained, Krishna turns to what it should know: God in everything.",
    "Chapter VIII": "Arjuna asks what happens at the end of life, and how the good find God then.",
    "Chapter IX": "Krishna now shares what he calls the royal secret: how all things rest in him.",
    "Chapter X": "Arjuna asks for more. Krishna names the greatest things in creation as glimpses of himself.",
    "Chapter XI": "Hearing is not enough. Arjuna asks to see Krishna's universal form with his own eyes.",
    "Chapter XII": "After the terrifying vision, a gentle question: which kind of devotion is best?",
    "Chapter XIII": "From the devotee to the body and soul: the field, and the one who knows the field.",
    "Chapter XIV": "Krishna explains the three threads that weave every human nature.",
    "Chapter XV": "The three threads tangle us in the world. Here is the world pictured as an upside-down tree.",
    "Chapter XVI": "Two kinds of people walk that tree: those drawn upward and those drawn down.",
    "Chapter XVII": "What separates them shows in their faith, their food, their gifts and their speech.",
    "Chapter XVIII": "The final chapter gathers every thread: what true giving-up means, and Krishna's last word.",
}

GLOSS = {
    "detachment": ("Not clinging to results or things.", "She worked hard on the exam, then let go of worrying about the marks.", ["detached"]),
    "devotion": ("Deep love and loyalty, especially to God.", "His devotion to his grandmother showed in daily visits.", []),
    "renounce": ("To give something up completely.", "He renounced sugar for Lent.", ["renouncing", "renounced"]),
}

C1, C2, C3, C4, C5, C6, C7, C8, C9 = (f"Chapter {r}" for r in "I II III IV V VI VII VIII IX".split())
C10, C11, C12, C13, C14, C15, C16, C17, C18 = (f"Chapter {r}" for r in "X XI XII XIII XIV XV XVI XVII XVIII".split())

PAGES = [
    K(0), K(1),
    N(C1, None, "Rather die unarmed",
      "Arjuna's despair reaches its lowest point. He would rather walk into the battle with no weapon and let his cousins kill him than shed the blood of his own family. Winning a kingdom, he says, could never be worth it. Then he sinks down in the chariot and drops his bow.",
      "Better I deem it, if my kinsmen strike, To face them weaponless, and bare my breast To shaft and spear, than answer blow with blow.",
      "I would rather be killed unarmed than strike back at my family.", "Someone so hurt by a family feud that they'd rather give up everything than fight their own relatives.",
      "Arjuna in despair on the chariot painting"),
    K(2),
    N(C2, None, "What is real cannot end",
      "Krishna's first lesson is about what lasts. Bodies come and go like seasons, but what truly is can never stop being, and what is not real was never there at all. The wise learn to tell the lasting thing from the passing one.",
      "That which is Can never cease to be; that which is not Will not exist.",
      "What is truly real never ends; what is unreal never really existed.", "Your love for a friend outlasts the many small fights that pass like weather.",
      "Krishna teaching Arjuna Kangra painting"),
    K(3), K(4), K(5),
    N(C3, None, "No escape from action",
      "Arjuna hoped quiet thought might excuse him from fighting. Krishna says no one becomes perfect just by sitting still. Even breathing and eating are actions. Refusing to act is itself a choice, and usually a worse one.",
      "No man shall 'scape from act By shunning action",
      "You can't avoid acting by refusing to act; doing nothing is also a choice.", "Not replying to an important message is still a reply.",
      "Indian village life painting 18th century"),
    K(6),
    N(C3, None, "People follow the best",
      "Leaders carry a special duty. Whatever the respected do, everyone else copies, and whatever standard they set, the world follows. So even a wise person who needs nothing should keep working, as an example.",
      "What the wise choose The unwise people take; what best men do The multitude will follow.",
      "Ordinary people copy what respected people do.", "When the class topper starts taking notes by hand, half the class does too.",
      "Mughal court painting procession"),
    K(7),
    K(8),
    N(C4, None, "Rest inside action",
      "Krishna offers a puzzle: true action can feel like rest, and true rest can be a kind of action. The wise person does the work without the inner restlessness of wanting, so even busy days stay calm inside.",
      "He who sees How action may be rest, rest action--he Is wisest 'mid his kind; he hath the truth!",
      "The wisest people can be busy yet calm, or still yet useful.", "A surgeon who works fast but feels calm inside.",
      "Indian sage meditating painting"),
    K(9),
    N(C5, None, "Two good roads",
      "Is it better to give up work or to do work in a holy way? Krishna says both lead to the same peace. But of the two, working without selfishness is the better road, because it is easier to walk and does good along the way.",
      "To cease from works Is well, and to do works in holiness Is well",
      "Stepping back from work and working selflessly are both good paths.", "One person serves by teaching, another by quietly praying for others; both help.",
      "two paths landscape Indian miniature"),
    K(10),
    N(C5, None, "The sun of wisdom",
      "When ignorance lifts, the truth appears all at once, like sunrise after night. Such a person sees the same spirit in a scholar, a cow, an elephant and a dog, and stops ranking people as higher or lower.",
      "As if a Sun of Wisdom sprang to shed Its beams of dawn.",
      "Real understanding arrives like the sun rising, lighting everything.", "The moment a hard maths idea suddenly makes sense and everything else clicks.",
      "sunrise over the Ganges painting"),
    K(11),
    N(C6, None, "Effort until ease",
      "Meditation does not come easily. At first the will must work hard, again and again, until effort turns into ease and even thinking falls quiet. Krishna is honest: the restless mind is like the wind, but practice and detachment can tame it.",
      "Steadfastly the will Must toil thereto, till efforts end in ease, And thought has passed from thinking.",
      "Keep practising until what was hard becomes effortless.", "Learning to ride a bicycle: wobbly effort first, then it's like breathing.",
      "yogi seated meditation Indian painting"),
    K(12),
    N(C6, None, "No effort is wasted",
      "Arjuna worries: what if someone tries and fails? Krishna comforts him. Nothing good is ever lost. The person who falls short begins again later with all the progress already made, and climbs higher.",
      "So hath he back again what heights of heart He did achieve, and so he strives anew To perfectness",
      "If you fail, you keep what you learned and start again from a higher place.", "Failing a driving test still leaves you a better driver for the next attempt.",
      "Himalaya mountain painting 19th century"),
    K(13),
    N(C7, None, "One in thousands",
      "Few people even look for the truth, and of those who look, very few find it. Krishna is not discouraging Arjuna; he is telling him how rare and precious the search is.",
      "Of many thousand mortals, one, perchance, Striveth for Truth",
      "Out of thousands of people, perhaps one really searches for truth.", "Many people buy a gym membership; few keep going every week.",
      "crowd at Indian festival painting"),
    N(C7, None, "Every sincere faith",
      "People worship in many ways and many forms. Krishna says that wherever faith is sincere, he is the one who gives it strength, even when people pray to other gods with other names.",
      "Worship what shrine they will, what shapes, in faith-- 'Tis I who give them faith!",
      "Whatever form people worship, the faith itself comes from the one God.", "Different people find peace in a temple, a church or a quiet walk; the longing is the same.",
      "Indian temple shrine painting"),
    K(14),
    N(C8, None, "A steady heart",
      "The thought you hold most often becomes the thought you hold at the end. That is why Krishna asks Arjuna to keep him in mind always, even while fighting, and promises that a mind fixed on him reaches him.",
      "Thou too, when heart and mind are fixed on Me, Shalt surely come to Me!",
      "If your heart and mind stay fixed on God, you will reach God.", "The habits you practise daily are the ones you fall back on in a crisis.",
      "Krishna with flute painting"),
    N(C8, None, "Unwavering will",
      "Those who hold on with steady, unwavering faith, not distracted by other gods or other goals, all arrive at the highest. The key is not cleverness but constancy.",
      "All come who cleave With never-wavering will of firmest faith",
      "Everyone who holds on with steady faith gets there.", "The student who studies a little every day beats the one who crams in bursts.",
      "pilgrims walking India painting"),
    K(15),
    N(C9, None, "Like air in the sky",
      "How can everything be in God without being God? Krishna's image: wind moves through the whole sky but is not the sky. In the same way all creatures live in him, yet he is more than all of them.",
      "So all things are in Me, but are not I.",
      "Everything exists within God, but God is more than everything.", "Fish live in the sea, but the sea is much more than the fish.",
      "clouds sky Indian miniature painting"),
    N(C9, None, "Easy to walk by",
      "Krishna calls his teaching the royal secret, yet he insists it is not hard. It is a light that cleans the heart, clear to see and easy to follow, and it never runs out.",
      "a light of holiness With inmost splendour shining; plain to see; Easy to walk by, inexhaustible!",
      "This teaching is like a bright, clear light that is easy to follow.", "Good advice is often simple, like 'be kind and tell the truth'.",
      "oil lamps Diwali painting"),
    K(16),
    N(C10, None, "Within every heart",
      "Krishna lists his glories, the brightest star, the greatest mountain, the wisest sage, but first he says the simplest thing: he lives in the heart of every creature, giving it life and taking it back.",
      "I am the Spirit seated deep in every creature's heart",
      "God lives deep inside every living being.", "Seeing something worth respecting even in a stranger on the bus.",
      "Vishnu painting Indian"),
    N(C10, None, "Never enough",
      "Arjuna, delighted, asks to hear more. He says his ears can never drink enough of these words, like the nectar of immortality. Real learning makes you hungrier, not fuller.",
      "Never enough Can mine ears drink the Amrit of such words!",
      "I could never hear enough of these wonderful words.", "A good story you want told again and again.",
      "Arjuna and Krishna conversation painting"),
    K(17),
    N(C11, None, "Arms without end",
      "Krishna shows Arjuna his universal form. Arjuna sees countless arms, faces and eyes in every direction, with no beginning, middle or end, brighter than a thousand suns. He is terrified and amazed.",
      "I see Thy thousand thousand arms, and breasts, and faces, And eyes",
      "Arjuna sees God's form, endless in every direction.", "Seeing the night sky full of stars and feeling how small you are.",
      "Vishvarupa painting"),
    N(C11, None, "You only strike the fallen",
      "In the vision Arjuna sees the warriors already swallowed by time. Krishna tells him the outcome is settled; Arjuna is only the instrument. Do your part, he says, without the burden of thinking it all depends on you.",
      "Thou wilt but slay the slain",
      "The result is already decided; you only carry out your part.", "A relay runner runs their leg well without carrying the whole race on their shoulders.",
      "Kurukshetra battle painting"),
    K(18),
    N(C12, None, "Untroubled and untroubling",
      "Krishna describes the devotee he loves: someone who doesn't upset others and isn't upset by them, free of anger, beyond wild joy and fear. Calm is not coldness; it is love that stays steady.",
      "Who troubleth not his kind, And is not troubled by them; clear of wrath",
      "God loves the person who neither disturbs others nor is easily disturbed.", "A friend who never starts drama and doesn't get pulled into it.",
      "Indian sage under tree painting"),
    N(C12, None, "Work done for love",
      "If deep meditation is too hard, Krishna offers another way: do your work for love of God. Ordinary work done with that love is enough to reach him.",
      "For he that laboureth right for love of Me Shall finally attain!",
      "Whoever works well out of love for God will reach God.", "A mother cooking for her family with love turns a chore into devotion.",
      "Indian women working painting"),
    K(19),
    N(C13, None, "Light of lights",
      "The knower inside us, the true self, is described as the light behind all lights, shining in the middle of darkness. It is in every heart, guiding those who look for it.",
      "The Light of Lights He is, in the heart of the Dark Shining eternally.",
      "The divine is the source of all light, shining even in darkness.", "Hope that keeps burning even in the worst week of your life.",
      "lamp in darkness painting"),
    N(C13, None, "Untouched by the body",
      "The highest self lives inside the body but is not stained by what the body does, just as space touches everything but is touched by nothing. Seeing this ends fear.",
      "Taketh no stain of acts, worketh in nought!",
      "The true self is not stained by the body's actions.", "Clear sky isn't dirtied by the smoke that passes through it.",
      "sky with clouds landscape painting 19th century"),
    K(20),
    N(C14, None, "The dark thread",
      "Of the three threads, the darkest is ignorance. It blinds people and ties them down with dullness, laziness and sleep. Recognising it in yourself is the first step out.",
      "But Ignorance, begot Of Darkness, blinding mortal men, binds down Their souls to stupor, sloth, and drowsiness.",
      "Ignorance blinds people and binds them with dullness and laziness.", "Scrolling for hours half-asleep when you meant to do something important.",
      "night scene Indian miniature"),
    N(C14, None, "Like breeds like",
      "Each thread produces more of itself. Clarity grows clarity, restless desire grows more desire, and darkness grows confusion. Whatever you feed, grows.",
      "For Light brings light, and Passion ache to have",
      "Good brings more good; craving brings more craving.", "One good habit, like an early night, makes the next good choice easier.",
      "sun rays through clouds painting"),
    K(21),
    N(C15, None, "Leaves that whisper",
      "The holy fig tree with roots above and branches below is the world. Its leaves are the sacred hymns, whispering truth to those who listen. Cutting through it with the axe of detachment, the wise find the way home.",
      "its leaves Are green and waving hymns which whisper Truth!",
      "The tree's leaves are like holy songs that speak the truth.", "Finding wisdom in ordinary things, like a tree in the wind.",
      "banyan tree India engraving"),
    N(C15, None, "As the wind carries scent",
      "When the soul moves from one body to the next, it carries the mind and senses with it, the way the wind carries the scent of flowers. Only the wise see this happening.",
      "as the wind gathers scents, Blowing above the flower-beds",
      "The soul carries the mind with it like wind carries a flower's scent.", "A person moving house still carries their habits and memories with them.",
      "flower garden Mughal painting"),
    K(22),
    N(C16, None, "The boaster",
      "Krishna paints the proud, ungodly mind in its own words: today I beat one enemy, tomorrow I beat another; I am rich, I am powerful, who is like me? It is a mind that never rests.",
      "To-day we slew a foe, and we will slay Our other enemy to-morrow!",
      "The proud boast of beating one enemy after another.", "A bully who always needs a new target to feel big.",
      "Mughal emperor hunting painting"),
    N(C16, None, "Three doors to ruin",
      "There are three gates to self-destruction: lust, anger and greed. Krishna's advice is simple: shut all three, and walk the better road.",
      "The Doors of Hell Are threefold, whereby men to ruin pass,-- The door of Lust, the door of Wrath, the door Of Avarice.",
      "Lust, anger and greed are the three doors to ruin.", "Most bad decisions you regret came from wanting too much, getting angry, or getting greedy.",
      "fortress gate India painting"),
    K(23),
    N(C17, None, "Kind true words",
      "Speech can be a discipline too. Words that hurt no one, that are true, gentle and pleasant, and that come from study, are a quiet kind of worship.",
      "Words causing no man woe, words ever true, Gentle and pleasing words",
      "Speak words that are true, kind and hurt no one.", "Telling a friend an honest truth gently, not harshly.",
      "Indian teacher with students painting"),
    N(C17, None, "Showing off",
      "Religion done for display, to get praise, honour and attention, belongs to restless passion. It looks holy but is really about the self, and its rewards don't last.",
      "Religion shown in act of proud display To win good entertainment, worship, fame",
      "Showy religion done for fame is selfish, not holy.", "Donating loudly for photos instead of quietly to help.",
      "Indian royal procession painting"),
    N(C18, None, "Do it, but let go",
      "Should good works like worship and charity be given up? No, Krishna says, they purify us. But they must be done without clinging to them or to what they bring. That letting go is the real renunciation.",
      "Yet must be practised even those high works In yielding up attachment, and all fruit Produced by works.",
      "Keep doing good deeds, but without clinging to them or their rewards.", "Volunteering every week without needing anyone to notice.",
      "Indian charity alms painting"),
    N(C18, None, "Every fire has smoke",
      "No work is perfect. Every action has some fault in it, as every flame has some smoke. So don't abandon your own duty because it is imperfect.",
      "For every work hath blame, as every flame Is wrapped in smoke!",
      "Every job has flaws, just as every fire has smoke.", "No profession is perfect; that's not a reason to quit yours.",
      "oil lamp flame Indian"),
    N(C18, None, "The stubborn fool",
      "There is a bad kind of steadfastness too: the fool who clings to laziness, sadness, fear and despair. Being stubborn is only a virtue when you hold on to the right things.",
      "Sad is the steadfastness wherewith the fool Cleaves to his sloth, his sorrow, and his fears",
      "Clinging stubbornly to laziness and fear is foolish, not strong.", "Refusing every new idea just because you've 'always done it this way'.",
      "Indian man sleeping painting"),
    K(24),
]
