from deep_build import K, N

SRC = None  # a digest: every quote comes from a public-domain classic, signed with its source
TARGET = 96

BRIDGE = {
    "Law 2": "Don't threaten those above you. And don't trust too easily those beside you.",
    "Law 3": "Friends can turn. So keep your real plans to yourself.",
    "Law 4": "Hiding your aims starts with your mouth: say less.",
    "Law 5": "What you don't say protects you. What others say about you protects you more: your reputation.",
    "Law 6": "A reputation needs fuel. Attention is the fuel.",
    "Law 7": "Attention follows achievement. Here is the cynical shortcut: borrowed achievement.",
    "Law 8": "Make others work for you, and make them come to you too.",
    "Law 9": "When they come, don't argue with them. Show them.",
    "Law 10": "Choose carefully whom you let close: unhappiness spreads.",
    "Law 11": "Keep the right people near, and make them need you.",
    "Law 12": "To be needed you must be trusted. Sometimes trust is bought with one honest act.",
    "Law 13": "When you need something back, speak to self-interest, not gratitude.",
    "Law 14": "Knowing what others want requires watching them closely.",
    "Law 15": "What you learn about an enemy, use completely.",
    "Law 16": "After victory, step back. Absence makes people value you.",
    "Law 17": "Being hard to predict keeps others off balance.",
    "Law 18": "Don't hide away in safety. Isolation is its own danger.",
    "Law 19": "Moving among people, know exactly whom you are dealing with.",
    "Law 20": "Know them, but don't belong to any of them.",
    "Law 21": "Staying free sometimes means looking less clever than you are.",
    "Law 22": "Looking weak can be a weapon. So can surrender.",
    "Law 23": "Bend when you must; but when you strike, strike in one place.",
    "Law 24": "Focus works at court too. The perfect courtier is focused charm.",
    "Law 25": "Playing a role well leads to the boldest move: writing your own role.",
    "Law 26": "A new self must stay spotless. Let others carry the dirt.",
    "Law 27": "With clean hands you can become something more: a figure people believe in.",
    "Law 28": "Belief follows confidence. Act boldly.",
    "Law 29": "Boldness is not recklessness. Plan to the very end.",
    "Law 30": "A planned victory should look effortless.",
    "Law 31": "Effortless control means choosing the choices others make.",
    "Law 32": "People choose with their hopes. Speak to their fantasies.",
    "Law 33": "Every fantasy hides a weakness: find each person's lever.",
    "Law 34": "Use levers quietly, and carry yourself like royalty.",
    "Law 35": "Royal dignity includes patience. Master timing.",
    "Law 36": "Some things will never be yours. Act as if you don't want them.",
    "Law 37": "Instead of chasing, create a spectacle people come to see.",
    "Law 38": "Stand out in display, but blend in with your opinions.",
    "Law 39": "Calm on the outside, you can unsettle others.",
    "Law 40": "Unsettled people grab at free things. Be wary of anything free.",
    "Law 41": "Gifts and inheritances bind you. So does a great man's name.",
    "Law 42": "Make your own name, and when attacked, go after the source.",
    "Law 43": "Force wins battles; hearts win wars.",
    "Law 44": "To win hearts, sometimes hold up a mirror.",
    "Law 45": "Mirrors unsettle. So does too much change at once.",
    "Law 46": "Change slowly, and don't look perfect while you do it.",
    "Law 47": "Imperfection keeps you human. Knowing when to stop keeps you safe.",
    "Law 48": "The last law sums up all the rest: stay fluid.",
}

def law(n, idx, title, text, quote, src, mean, life, pic):
    return [K(idx), N(f"Law {n}", None, title, text, quote, mean, life, pic, src=src)]

PAGES = sum([
    law(1, 0, "In history: Fouquet's party",
        "In 1661 Nicolas Fouquet, France's finance minister, threw a dazzling party at his new château for the young Louis XIV. Fireworks, a new Molière play, gold plates. The king felt outshone. Within weeks Fouquet was arrested, and he died in prison. Louis later built Versailles, bigger than anything Fouquet had.",
        "Never seem wiser, nor more learned, than the people you are with.", "chesterfield",
        "Don't act cleverer or grander than those around you.", "Showing up the boss in a meeting can cost you more than the idea was worth.",
        "Nicolas Fouquet portrait"),
    law(2, 1, "In history: a friend turned killer",
        "The Byzantine emperor Michael III raised his friend Basil, a stable groom, to co-emperor. Basil had him murdered and took the throne. Benjamin Franklin found the opposite trick: he turned a rival into a lifelong friend by asking to borrow a book.",
        "He that has once done you a kindness will be more ready to do you another, than he whom you yourself have obliged.", "franklin",
        "People who have helped you once tend to like you more, not less.", "Asking a cold colleague for advice can warm them up.",
        "Madrid Skylitzes Basil"),
    law(3, 2, "In history: Bismarck's peace speech",
        "In 1850 Otto von Bismarck shocked his colleagues by giving a speech praising peace with Austria, the rival he despised. It won him the post he wanted. Years later, in power, he went to war with Austria and won. Nobody had seen his real plan.",
        "Every one sees what you appear to be, few really know what you are", "prince",
        "People see your surface; few know what's underneath.", "A quiet student who nobody expects to top the exam.",
        "Otto von Bismarck 1860s portrait"),
    law(4, 3, "In history: Coriolanus talks too much",
        "Coriolanus was a Roman war hero, and the people were ready to make him consul. Then he started talking, insulting the common people in speech after speech. They turned on him and drove him into exile. His deeds won them; his words lost them.",
        "Speak not but what may benefit others or yourself; avoid trifling conversation.", "franklin",
        "Only say what helps; skip pointless talk.", "Saying less in a job interview often impresses more than talking nonstop.",
        "Coriolanus painting"),
    law(5, 4, "In history: guarding a name",
        "Julius Caesar divorced his wife Pompeia after a scandal, though he said he believed she was innocent. His reason: Caesar's wife must be above suspicion. He understood that a reputation, once stained, is very hard to clean.",
        "a prince should guard himself, above all things, against being despised and hated", "prince",
        "Above all, a leader must avoid being looked down on or hated.", "One viral bad review can hurt a restaurant more than ten good ones help.",
        "Julius Caesar bust"),
    law(6, 5, "In history: Barnum's mermaid",
        "P. T. Barnum advertised a real 'Fiji mermaid' all over New York. It was a monkey sewn to a fish. Crowds paid to see it anyway, and the arguments about whether it was fake only brought more. Barnum knew attention of any kind could be turned into fame.",
        "affirmation, repetition, and contagion", "crowd",
        "Ideas spread by bold statements, repeated, that catch on like a cold.", "A catchy jingle you can't get out of your head.",
        "Feejee mermaid Barnum"),
    law(7, 6, "In history: the inventor and the businessman",
        "Nikola Tesla worked for Thomas Edison and solved hard engineering problems, but the credit and the money went elsewhere. Edison ran a workshop where many minds worked under one name. Sun Tzu would have understood: great results come from combined effort, not one exhausted individual.",
        "The clever combatant looks to the effect of combined energy, and does not require too much from individuals.", "sunzi",
        "A smart leader relies on teamwork rather than demanding everything from one person.", "A film director takes the bow for the work of hundreds.",
        "Nikola Tesla portrait"),
    law(8, 7, "In history: the waiting general",
        "Sun Tzu's oldest advice is to arrive first, rest, and let the enemy come to you tired. Talleyrand, the French diplomat, played the same game at the Congress of Vienna, waiting while others rushed, and won far more for defeated France than anyone expected.",
        "Whoever is first in the field and awaits the coming of the enemy, will be fresh for the fight", "sunzi",
        "Whoever gets there first and waits will be fresh when the fight comes.", "Arriving early to a negotiation and letting the other side hurry in.",
        "Talleyrand portrait"),
    law(9, 8, "In history: Michelangelo's nose job",
        "The mayor of Florence told Michelangelo that his giant David's nose was too big. Michelangelo didn't argue. He climbed up with a little marble dust, pretended to chisel, let the dust fall, and asked, 'Better?' 'Much better,' said the mayor. The statue was unchanged.",
        "I made it a rule to forbear all direct contradiction to the sentiments of others, and all positive assertion of my own.", "franklin",
        "I made it a rule never to contradict people directly or insist I was right.", "Letting a parent think the plan was their idea.",
        "Michelangelo David statue"),
    law(10, 9, "In history: a dangerous charm",
        "Lola Montez, a dancer of the 1840s, left trouble wherever she went. King Ludwig I of Bavaria fell for her, gave her titles and power, and lost his throne in the uproar. The Buddha's advice on companions is blunt: better to travel alone than with a fool.",
        "If a traveller does not meet with one who is his better, or his equal, let him firmly keep to his solitary journey; there is no companionship with a fool.", "dhamma",
        "If you can't find good company, go alone rather than with a fool.", "Better to eat lunch alone than with a group that drags you down.",
        "Lola Montez portrait"),
    law(11, 10, "In history: the indispensable minister",
        "Machiavelli advised rulers to arrange things so that the people always need the state and the ruler; then they stay loyal. Court advisers learned the same lesson: those who held the secrets nobody else understood could never be dismissed.",
        "a wise prince ought to adopt such a course that his citizens will always in every sort and kind of circumstance have need of the state and of him, and then he will always find them faithful", "prince",
        "Make sure people always need you, and they will stay loyal.", "The only person who knows how the old billing system works never gets laid off.",
        "Renaissance counsellor engraving"),
    law(12, 11, "In history: the honest con",
        "A swindler once borrowed $50,000 from Al Capone, promising to double it. He kept the money untouched, then returned it, apologising that the deal failed. Capone, amazed at the honesty, gave him $5,000 as a reward, which was all the conman had wanted.",
        "Hypocrisy is the homage vice pays to virtue.", "roche",
        "Even dishonest people pretend to be honest, because honesty is admired.", "A shop that loudly refunds one small order to look trustworthy.",
        "Al Capone mugshot 1931"),
    law(13, 12, "In history: Corcyra asks Athens",
        "In 433 BC the island of Corcyra asked Athens for help. It didn't remind Athens of friendship or past favours; it had none. It argued that its navy would make Athens stronger. Athens agreed. Appeals to self-interest work where appeals to gratitude fail.",
        "Self-love is the greatest of flatterers.", "roche",
        "We are always ready to be persuaded by what benefits us.", "Ask a busy friend for help by showing how it helps them too.",
        "Athenian trireme"),
    law(14, 13, "In history: Talleyrand's dinners",
        "Talleyrand learned more over dinner than spies learned in months. Charming and relaxed, he got guests talking, and remembered everything. Sun Tzu's last advice on spies fits him: be subtle, and use information everywhere.",
        "Be subtle! be subtle! and use your spies for every kind of business.", "sunzi",
        "Quietly gather information in everything you do.", "A good journalist listens far more than they talk.",
        "Congress of Vienna dinner"),
    law(15, 14, "In history: injuries all at once",
        "Machiavelli praises leaders who do harsh things all at once and then stop, so people can forget, and condemns those who drag cruelty out bit by bit. Half-defeated enemies recover and come back; that is the whole argument of this law.",
        "injuries ought to be done all at one time, so that, being tasted less, they offend less", "prince",
        "If you must do something painful, do it all at once.", "Ripping off a plaster quickly hurts less than peeling it slowly.",
        "Tang dynasty empress painting"),
    law(16, 15, "In history: the vanishing king",
        "Herodotus tells of Deioces, a judge among the Medes so fair that everyone came to him. Then he withdrew, refusing to judge. Chaos followed, and the people begged him to return as king. He agreed, and lived hidden in a palace, seen by almost no one.",
        "When the work is done, and one's name is becoming distinguished, to withdraw into obscurity is the way of Heaven.", "tao",
        "Once you've succeeded, step back quietly; that is wise.", "A band that takes a long break comes back to sold-out shows.",
        "Ecbatana engraving"),
    law(17, 16, "In history: Fischer at Reykjavík",
        "In 1972 Bobby Fischer arrived late, complained about the lights, the cameras, the chairs, and nearly walked out of the world championship. His opponent, Boris Spassky, was rattled before a game was played. Fischer won the title.",
        "Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt.", "sunzi",
        "Keep your plans hidden, then act suddenly and powerfully.", "A rival team that changes tactics every match is hard to prepare for.",
        "chess players painting 19th century"),
    law(18, 17, "In history: the hidden emperor",
        "Qin Shi Huang, China's first emperor, grew so afraid of assassins that he built hundreds of palaces linked by covered walkways and told no one where he slept. Cut off from his advisers, he lost touch with his empire, which collapsed soon after he died.",
        "A single wheel can never move.", "artha",
        "No ruler can govern alone, just as one wheel can't move a cart.", "A boss who never talks to the team soon has no idea what's going on.",
        "Qin Shi Huang portrait"),
    law(19, 18, "In history: Sun Bin's revenge",
        "Pang Juan, a jealous general, framed his brilliant classmate Sun Bin and had his feet mutilated. Sun Bin escaped, became a strategist for a rival state, lured Pang Juan into an ambush at Maling, and destroyed his army. Pang Juan had badly misjudged whom he was hurting.",
        "He who exercises no forethought but makes light of his opponents is sure to be captured by them.", "sunzi",
        "Underestimate an opponent and you will lose to them.", "Mocking the quiet new kid who turns out to be the best player.",
        "Warring States battle painting"),
    law(20, 19, "In history: the Virgin Queen",
        "Elizabeth I of England was courted by princes from France, Spain and Austria. She never married, keeping each suitor hoping and each kingdom friendly. Machiavelli warned that neutral rulers usually fall; Elizabeth showed that staying uncommitted can work, if you keep everyone guessing.",
        "irresolute princes, to avoid present dangers, generally follow the neutral path", "prince",
        "Hesitant rulers often stay neutral to avoid danger, and usually regret it.", "Being friendly with both groups at school without joining either.",
        "Elizabeth I Armada Portrait"),
    law(21, 20, "In history: Claudius the fool",
        "Claudius stuttered and limped, and his family treated him as a harmless idiot. He survived the murderous reigns of Tiberius and Caligula because no one saw him as a threat. When Caligula was killed, the soldiers made Claudius emperor, and he ruled capably for thirteen years.",
        "Wear your learning, like your watch, in a private pocket", "chesterfield",
        "Keep your cleverness hidden, like a watch in your pocket.", "The quiet employee everyone underestimates who ends up running the company.",
        "Alma-Tadema A Roman Emperor AD 41"),
    law(22, 21, "In history: the willow and the oak",
        "An old fable: the proud oak stood stiff against the storm and was torn out by the roots; the willow bent to the ground and stood again when the wind passed. The Tao Te Ching puts the same idea in one line: the sage places himself last, and ends up first.",
        "Therefore the sage puts his own person last, and yet it is found in the foremost place", "tao",
        "The wise put themselves last and end up first.", "Apologising first in an argument often earns more respect than winning it.",
        "willow tree storm painting"),
    law(23, 22, "In history: the Rothschild brothers",
        "Mayer Amschel Rothschild sent his five sons to five European cities, but they worked as one family firm, sharing information by private couriers. Concentrated trust made them the most powerful bankers in Europe. Chesterfield's advice to his son is the everyday version: one thing at a time.",
        "There is time enough for everything, in the course of the day, if you do but one thing at once", "chesterfield",
        "If you focus on one thing at a time, you'll find time for everything.", "Turning off notifications to finish one assignment properly.",
        "Mayer Amschel Rothschild portrait"),
    law(24, 23, "In history: The Book of the Courtier",
        "In 1528 Baldassare Castiglione described the perfect courtier: graceful, witty, never showing effort, always pleasing. Kings read it for two hundred years. Chesterfield, writing to his son, agreed that pleasing others is a skill to be learned, and a hard one.",
        "The art of pleasing is a very necessary one to possess; but a very difficult one to acquire.", "chesterfield",
        "Being pleasant to others is important, but hard to learn.", "A great receptionist makes every visitor feel welcome.",
        "Baldassare Castiglione Raphael"),
    law(25, 24, "In history: Caesar the actor",
        "Julius Caesar built his public self like a play: generous games, daring speeches, dramatic gestures like crossing the Rubicon. He refused to stay the man people expected. Emerson said the same in his own way: don't be trapped by what you were yesterday.",
        "A foolish consistency is the hobgoblin of little minds", "emerson",
        "Refusing to change just to stay consistent is small-minded.", "Changing your career path when you discover what you really love.",
        "Caesar crossing the Rubicon painting"),
    law(26, 25, "In history: Borgia's scapegoat",
        "Cesare Borgia sent the brutal Remirro de Orco to tame the Romagna. When the people grew to hate the harshness, Borgia had Remirro cut in two and displayed in the square. The people were satisfied, and Borgia's hands looked clean.",
        "The barbarity of this spectacle caused the people to be at once satisfied and dismayed", "prince",
        "The cruel display both pleased and frightened the people.", "A company that fires one manager to take the blame for a scandal.",
        "Rocca di Cesena"),
    law(27, 26, "In history: Mesmer's tubs",
        "Franz Mesmer claimed an invisible 'animal magnetism' could cure illness. In dim Paris salons, patients sat around tubs of iron filings while music played, and many felt better. A royal commission found no magnetism at all, only belief. Le Bon later wrote why it works.",
        "The masses have never thirsted after truth.", "crowd",
        "Crowds want something to believe in more than they want the truth.", "Viral miracle cures that spread despite no evidence.",
        "Mesmer animal magnetism engraving"),
    law(28, 27, "In history: selling the Eiffel Tower",
        "In 1925 the conman Victor Lustig, posing as a government official, persuaded scrap dealers that Paris was selling the Eiffel Tower. His sheer boldness made the story believable. He sold it, fled with the money, and almost sold it again.",
        "While the hungry lion slumbers, not a deer comes to his den.", "hito",
        "Nothing comes to you if you just wait; you must act boldly.", "The job goes to the person who applied, not the one who meant to.",
        "Eiffel Tower 1889"),
    law(29, 28, "In history: Napoleon in Russia",
        "In 1812 Napoleon marched 600,000 men into Russia expecting a quick battle. The Russians retreated, burned the land, and let winter do the rest. Fewer than 100,000 came back. He had planned the beginning, not the end.",
        "Thus do many calculations lead to victory, and few calculations to defeat: how much more no calculation at all!", "sunzi",
        "Careful planning wins; little planning loses.", "Starting a trek without checking the weather on the way down.",
        "Napoleon retreat from Moscow painting"),
    law(30, 29, "In history: Houdini's secret work",
        "Harry Houdini's escapes looked like magic. Behind them were years of practising lock-picking, holding his breath and studying every handcuff made. Audiences saw effortless miracles because he hid the sweat.",
        "It is useless to warn the student that he must be natural.", "speaking",
        "You can't just tell someone to be natural; it comes from practice.", "A dancer whose effortless performance took thousands of hours.",
        "Houdini poster"),
    law(31, 30, "In history: Ivan the Terrible's exit",
        "In 1564 Ivan IV suddenly left Moscow and threatened to abdicate. The terrified people and nobles begged him to return. He agreed, on his terms: unlimited power. They thought they were choosing; he had chosen for them.",
        "the clever combatant imposes his will on the enemy", "sunzi",
        "The clever fighter makes the other side play his game.", "A parent who asks 'peas or carrots?' when vegetables were never optional.",
        "Ivan the Terrible painting"),
    law(32, 31, "In history: the Venetian alchemist",
        "In 1589 Bragadino arrived in bankrupt Venice claiming he could make gold. The desperate city gave him money and a palace. He kept delaying the miracle, until the truth came out. People wanted the dream too much to look closely, like Plato's prisoners watching shadows.",
        "human beings living in an underground den which is open towards the light", "republic",
        "Plato pictures people trapped in a cave, seeing only shadows of reality.", "Believing an investment that promises to double your money in a month.",
        "Teniers alchemist painting"),
    law(33, 32, "In history: Richelieu's lever",
        "Cardinal Richelieu rose by finding what the queen mother, Marie de' Medici, craved: flattery and power for herself. He gave her both, became indispensable, then used her son, Louis XIII, to push her aside. Machiavelli knew where people are most sensitive.",
        "men more quickly forget the death of their father than the loss of their patrimony", "prince",
        "People forgive a parent's death sooner than losing their property.", "Touch someone's savings and you'll see how strongly they react.",
        "Cardinal Richelieu Champaigne"),
    law(34, 33, "In history: Columbus asks for titles",
        "Before sailing, Christopher Columbus, a poor sailor's son, demanded to be made Admiral of the Ocean Sea, viceroy of any lands he found, and to receive a tenth of all riches. Ferdinand and Isabella agreed, partly because he asked as if it were obvious.",
        "Trust thyself: every heart vibrates to that iron string.", "emerson",
        "Believe in yourself; everyone responds to that.", "Asking for the salary you're worth instead of apologising for it.",
        "Columbus before Ferdinand and Isabella"),
    law(35, 34, "In history: Fouché the survivor",
        "Joseph Fouché served the Revolution, Napoleon and the returning king, switching sides at exactly the right moment each time. He survived what killed almost everyone else. His secret was waiting until the tide had clearly turned, then moving fast.",
        "Energy may be likened to the bending of a crossbow; decision, to the releasing of the trigger.", "sunzi",
        "Build up patiently, then act decisively at the right moment.", "Waiting for the right moment to ask for a raise, then asking clearly.",
        "Joseph Fouché portrait"),
    law(36, 35, "In history: the fox and the grapes",
        "Aesop's fox couldn't reach the grapes, so he walked off saying they were sour anyway. The fable mocks him, but the law takes him seriously: showing you don't care about what you can't have robs it of its power over you. Epictetus said our troubles come from how we see things.",
        "Men are disturbed not by things, but by the views which they take of things.", "enchiridion",
        "It's our opinions about things, not the things themselves, that upset us.", "Losing a game feels smaller once you decide it was just a game.",
        "fox and the grapes illustration"),
    law(37, 36, "In history: Cleopatra's barge",
        "When Mark Antony summoned Cleopatra, she came up the river on a golden barge with purple sails and silver oars, dressed as Venus, with perfume drifting to the shore. Antony was conquered before they spoke. Crowds, Le Bon wrote, are moved by images, not reasons.",
        "allows himself to be impressed by words and images", "crowd",
        "People in crowds are swayed by striking words and pictures.", "A brilliant product launch that people remember more than the product.",
        "Alma-Tadema Antony and Cleopatra"),
    law(38, 37, "In history: Socrates' trial",
        "Socrates questioned everyone in Athens and openly mocked its customs. In 399 BC the city tried him for corrupting the young and executed him. Wise people since have learned to keep their most unusual thoughts to themselves.",
        "He who knows (the Tao) does not (care to) speak (about it); he who is (ever ready to) speak about it does not know it.", "tao",
        "Those who truly understand rarely talk about it; those who talk the most understand least.", "The person bragging loudest at a party usually knows the least.",
        "Death of Socrates David"),
    law(39, 38, "In history: Fabius the delayer",
        "Hannibal tried every trick to provoke the Roman general Fabius into battle: insults, burned farms, feigned retreats. Fabius refused, shadowing him patiently. Hannibal's angry frustration, not Roman swords, slowly wore his army down. Darwin noticed that giving way to anger only feeds it.",
        "He who gives way to violent gestures will increase his rage", "darwin",
        "Acting out anger makes you angrier.", "Shouting back in an argument only makes both people madder.",
        "Fabius Maximus bust"),
    law(40, 39, "In history: the Trojan Horse",
        "After ten years of war, the Greeks left a giant wooden horse as a gift and sailed away. The Trojans dragged it inside their walls. That night Greek soldiers climbed out and opened the gates. The free gift cost Troy everything. Money and gifts, the Hitopadesha warns, change how people treat you.",
        "Wealth is friends, home, father, brother", "hito",
        "Money brings friends, family and respect, which is why it's dangerous.", "A 'free' trial that quietly signs you up for a yearly plan.",
        "Tiepolo Trojan Horse"),
    law(41, 40, "In history: Alexander and Philip",
        "Alexander the Great grew up in the shadow of his father Philip, who had already conquered Greece. He reportedly complained that his father would leave him nothing to win. So he went further, to Persia, Egypt and India, and made a name bigger than Philip's.",
        "Whoso would be a man, must be a nonconformist.", "emerson",
        "To be your own person you must not just follow the crowd, or your parents.", "Choosing your own career instead of the family business.",
        "Alexander Mosaic"),
    law(42, 41, "In history: the crowd's leader",
        "Athenians sometimes held an 'ostracism': each citizen scratched on a pottery shard the name of the man they most wanted gone, and the top name was exiled for ten years. Remove the leader and the faction falls apart. Le Bon explains why crowds depend on their leaders.",
        "by the mere fact that he forms part of an organised crowd, a man descends several rungs in the ladder of civilisation", "crowd",
        "In a crowd, a person thinks less for themselves.", "A rowdy group of fans calms down when its loudest member leaves.",
        "ostracon Themistocles"),
    law(43, 42, "In history: Akbar wins hearts",
        "The Mughal emperor Akbar conquered by the sword, but he held his empire by winning hearts: he married Rajput princesses, abolished the tax on non-Muslims and welcomed scholars of every faith to debate at his court. Tiruvalluvar's way is gentler still.",
        "Let him do them a good turn and make them ashamed in their hearts.", "kural",
        "Answer people who hurt you with kindness.", "Helping a neighbour who once complained about you.",
        "Akbar court painting"),
    law(44, 43, "In history: Diogenes and Alexander",
        "Alexander the Great found the philosopher Diogenes lying in the sun and asked what he could do for him. 'Stand out of my sunlight,' said Diogenes. Alexander, used to flattery, saw his own pride reflected back. Emerson's mirror is a kinder one.",
        "the only way to have a friend is to be one.", "emerson",
        "To have friends, be a good friend first.", "Being the first to say hello in a new class.",
        "Diogenes and Alexander painting"),
    law(45, 44, "In history: Cromwell's revolution",
        "Thomas Cromwell rushed through huge changes for Henry VIII: closing the monasteries, rewriting church law. The speed made enemies everywhere, and when the king turned on him, no one defended him. He was executed in 1540. Lao Tzu's advice on governing is to handle things gently.",
        "Governing a great state is like cooking small fish.", "tao",
        "Govern gently, without stirring too much, or things fall apart.", "A new manager who changes everything in week one usually faces a revolt.",
        "Thomas Cromwell Holbein"),
    law(46, 45, "In history: Cosimo's modesty",
        "Cosimo de' Medici, richest man in Florence, wore plain clothes, built modest houses and rejected a grand palace design as too showy. He ruled the city for thirty years without a title, and people let him. Nietzsche said every deep mind needs a mask.",
        "Every profound spirit needs a mask", "bge",
        "Deep people need to hide parts of themselves.", "A brilliant student who doesn't brag about grades keeps more friends.",
        "Cosimo de' Medici Pontormo"),
    law(47, 46, "In history: Croesus goes too far",
        "Croesus of Lydia, the richest king alive, asked the oracle whether to attack Persia. 'You will destroy a great empire,' it said. He attacked, and destroyed his own. He should have stopped while ahead. Epictetus' rule: take your modest share, as at a banquet.",
        "Remember that you must behave as at a banquet.", "enchiridion",
        "Take your fair share politely, don't grab everything.", "Leaving the game while you're winning instead of betting it all.",
        "Croesus on the pyre"),
    law(48, 47, "In history: the Mongol horsemen",
        "Genghis Khan's armies had no cities to defend and no slow supply wagons. They moved fast, split up, joined again and appeared where no one expected. Fixed walls and heavy armies could not hold them. Water, in the Tao Te Ching, is the model.",
        "The highest excellence is like (that of) water.", "tao",
        "The best way to be is like water: flexible and patient.", "A startup that pivots quickly while big companies are stuck.",
        "Mongol cavalry painting"),
], [])
