from deep_build import K, N

SRC = "meditations"
TARGET = 60

BRIDGE = {
    "Book II": "Book I thanked the people who shaped him. Book II, written in a camp on the Danube, turns to the day ahead.",
    "Book III": "If the day is short, so is life. Book III asks what to do with the time left.",
    "Book IV": "The answer begins inside: a mind that can always retreat into itself.",
    "Book V": "From the inner fortress back to the morning, and the duty that gets you out of bed.",
    "Book VI": "Duty means dealing with people. Book VI is about meeting them without becoming like the worst of them.",
    "Book VII": "Most of what upsets us is outside our control. Book VII draws the line around what is ours.",
    "Book VIII": "Marcus admits he has fallen short. Book VIII is about beginning again.",
    "Book IX": "Starting over includes forgiving others. Book IX is about patience with people who do wrong.",
    "Book X": "Patience with others needs honesty with yourself: be good, not just talk about it.",
    "Book XI": "A life needs one aim. Book XI asks what that aim should be.",
    "Book XII": "The last book gathers it all: the soul, the short play of life, and leaving the stage well.",
}

GLOSS = {
    "providence": ("The care and plan of God or nature for the world.", "She trusted providence when the trip went wrong.", []),
    "tranquillity": ("Calm, peaceful state of mind.", "A walk by the sea restored his tranquillity.", ["tranquility"]),
    "virtue": ("Goodness of character.", "Honesty is a virtue that takes courage.", ["virtues"]),
}

B = lambda r: f"Book {r}"

PAGES = [
    K(0),
    N(B("I"), "Debts of Gratitude", "A father's example",
      "Marcus remembers what he learned from his adoptive father, the emperor Antoninus: modesty, patience, hard work, and a quiet refusal to be flattered. He lists simple habits too, like never bathing at odd hours or fussing over food and clothes.",
      "From the fame and memory of him that begot me I have learned both shamefastness and manlike behaviour.",
      "From my father I learned modesty and manly courage.", "Remembering a parent's quiet example when you're tempted to show off.",
      "Antoninus Pius bust"),
    N(B("I"), "Debts of Gratitude", "Good teachers at home",
      "His great-grandfather taught him the value of good teachers, and that spending money on learning is never waste. Marcus filled his youth with philosophers, rhetoricians and painters, and thanks each by name.",
      "and to get me good and able teachers at home",
      "I learned to find good teachers and not mind the cost.", "Saving for a course instead of a new phone.",
      "Roman school relief Neumagen"),
    N(B("I"), "Debts of Gratitude", "No regrets with a friend",
      "Rusticus often annoyed him, but Marcus never did anything to him that he later regretted. Even in irritation, he kept the friendship clean.",
      "That having been often displeased with Rusticus, I never did him anything for which afterwards I had occasion to repent.",
      "Even when a friend annoyed me, I never did anything I'd regret.", "Not sending the angry text you'd be ashamed of tomorrow.",
      "Roman friends fresco"),
    N(B("I"), "Debts of Gratitude", "Why people go wrong",
      "The first book ends with a key idea: those who do wrong do it because they don't know what is truly good or bad. Understanding this makes it possible to be angry less and help more.",
      "All these ill qualities have happened unto them, through ignorance of that which is truly good and truly bad.",
      "People behave badly because they don't understand what is really good.", "A rude driver is often just stressed and lost, not evil.",
      "Marcus Aurelius equestrian statue"),
    K(1),
    K(2),
    N(B("II"), "Happiness Within", "Your happiness is yours",
      "Marcus scolds himself for letting his happiness depend on other people's opinions. Life is nearly over, he writes, and you still hand your peace to what others think.",
      "Every man's happiness depends from himself",
      "Each person's happiness depends on themselves.", "Not checking your phone for likes after posting something you're proud of.",
      "Roman philosopher statue"),
    N(B("II"), "Happiness Within", "Fame after death",
      "Fame is worth little even in life. After death it is worth nothing: the people who remember you will soon be forgotten themselves.",
      "Fame after life is no better than oblivion.",
      "Being famous after you die is the same as being forgotten.", "Few people remember last year's viral star.",
      "Roman ruins Piranesi"),
    K(3),
    N(B("III"), "Ripeness", "The beauty of ripeness",
      "Marcus notices beauty in things others overlook: figs splitting as they ripen, the wrinkles of old age, a loaf's cracked crust. Nature's leftovers have their own charm, if you look properly.",
      "So figs are accounted fairest and ripest then, when they begin to shrink, and wither as it were.",
      "Figs are best just as they begin to shrivel.", "Finding beauty in a grandparent's wrinkled hands.",
      "figs still life painting"),
    N(B("III"), "Other People's Business", "Mind your own mind",
      "Don't waste your remaining days imagining what others are doing, saying or plotting, unless it helps the common good. It steals time from better work.",
      "Spend not the remnant of thy days in thoughts and fancies concerning other men",
      "Don't spend your life thinking about what other people are up to.", "Hours lost scrolling through other people's lives online.",
      "Roman street scene painting"),
    N(B("III"), "Honest Without Oaths", "Your word is enough",
      "The good person needs no oath and no witness. Their word stands on its own, because their life has made it trustworthy.",
      "One who for his word or actions neither needs an oath, nor any man to be a witness.",
      "A good person's word is trusted without swearing or witnesses.", "A shopkeeper who lets a regular pay tomorrow.",
      "Roman handshake relief"),
    N(B("III"), "Choose the Best", "Choose, and stick to it",
      "Decide freely what is best and hold to it. Don't let comfort, praise or pleasure pull you off it, however attractive they look.",
      "Do thou therefore I say absolutely and freely make choice of that which is best, and stick unto it.",
      "Freely choose what's best and hold on to it.", "Sticking to your study plan when friends invite you out.",
      "Hercules at the crossroads painting"),
    N(B("III"), "Only Now", "Only this moment",
      "No one lives anything but the present moment. The past is gone, the future uncertain. Keep to a few principles and remember how small your share of time is.",
      "no man properly can be said to live more than that which is now present, which is but a moment of time",
      "We only ever live in the present moment.", "Enjoying the meal in front of you instead of worrying about tomorrow's test.",
      "sundial Roman"),
    N(B("III"), "The Play's End", "Death mid-scene",
      "The good man's life is never cut short as unfinished, because each part of it is complete in itself, like a well-played scene, even if the play ends early.",
      "The life of such an one, death can never surprise as imperfect",
      "A good person's life is never incomplete, however soon it ends.", "A short life lived kindly can feel more complete than a long careless one.",
      "Roman theatre masks mosaic"),
    K(4),
    K(5),
    N(B("IV"), "God or Ape", "Ten days from god to ape",
      "Return to your principles, Marcus writes, and within ten days people who now treat you like a beast or an ape will call you a god. Character changes how others see you faster than you think.",
      "Within ten days, if so happen, thou shalt be esteemed a god of them",
      "Live by your principles and people will soon look up to you.", "A new hire who works steadily wins over doubters in weeks.",
      "Roman god statue Capitoline"),
    K(6),
    N(B("IV"), "Only the Necessary", "Cut the unnecessary",
      "Most of what we say and do is unnecessary. Cut it out and you gain time and calm. Ask before each act: is this necessary? Cut needless thoughts too, and needless actions will follow.",
      "Certainly there is nothing better, than for a man to confine himself to necessary actions",
      "It's best to stick to what's really necessary.", "Unsubscribing from the newsletters you never read.",
      "Roman lamp still life"),
    K(7),
    N(B("V"), "Thoughts Dye the Soul", "Your thoughts colour you",
      "Your mind becomes what you usually think about. The soul takes on the colour of its thoughts, like cloth soaked in dye. So soak it in good ones.",
      "Such as thy thoughts and ordinary cogitations are, such will thy mind be in time.",
      "Whatever you think about most, you become.", "Someone who complains constantly ends up seeing problems everywhere.",
      "dyers at work engraving"),
    N(B("V"), "The Obstacle Is the Way", "The obstacle becomes the way",
      "Others can block your actions, but never your mind's purpose. The mind turns every obstacle into material: what stood in the way becomes the way.",
      "what before was the impediment, is now the principal object of her working; and that which before was in her way, is now her readiest way",
      "What blocked your path becomes the path itself.", "A cancelled flight becomes the reason you finally explore a new city.",
      "Roman road paving"),
    N(B("V"), "Rest", "Yes, rest",
      "Marcus argues with himself: 'But you need rest.' Yes, he replies, but only as much as nature needs, not more. Rest is part of the work, not an escape from it.",
      "'But thou must have some rest.' Yes, thou must.",
      "Rest is needed, but in the right amount.", "A study break that lasts fifteen minutes, not three hours.",
      "Roman villa garden fresco"),
    N(B("V"), "Ordinary Things", "See things as they are",
      "Marcus strips grand things down: fine wine is grape juice, a purple robe is sheep's wool dyed with shellfish blood. Seeing things plainly removes their hold on you.",
      "This purple robe, but sheep's hairs, dyed with the blood of a shellfish.",
      "The royal purple robe is only dyed sheep's wool.", "A designer bag is still just leather and thread.",
      "Roman emperor purple toga statue"),
    K(8),
    N(B("VI"), "Revenge", "The best revenge",
      "When someone wrongs you, the best revenge is not to become like them. Their behaviour is their problem; copying it would make it yours.",
      "The best kind of revenge is, not to become like unto them.",
      "Don't take revenge by acting as badly as they did.", "Staying polite to a rude customer instead of snapping back.",
      "Marcus Aurelius bust Capitoline"),
    N(B("VI"), "Praise", "The clatter of tongues",
      "The praise of crowds is just the noise of many tongues clapping together. Don't work for applause; it's only sound.",
      "For the praises of many tongues, is in effect no better than the clattering of so many tongues.",
      "Crowd praise is just noise.", "A performer who plays well whether or not the audience claps.",
      "Roman crowd amphitheatre painting"),
    N(B("VI"), "Truth Hurts No One", "Truth never harmed anyone",
      "If someone shows Marcus he is wrong, he is glad to change. Truth never hurt anybody; staying in error does.",
      "For it is the truth that I seek after, by which I am sure that never any man was hurt",
      "Seeking the truth never harms anyone; staying wrong does.", "Thanking a friend who points out a mistake in your work.",
      "philosopher reading scroll Roman"),
    N(B("VI"), "Teach, Don't Rage", "Teach them, don't rage",
      "When people go wrong, show them better if you can, and don't be angry with them. Anger fixes nothing; teaching sometimes does.",
      "Thou therefore teach them better, and make it appear unto them: but be not thou angry with them.",
      "Teach people who are wrong, without getting angry.", "Calmly showing a colleague the right way to file a report.",
      "Roman teacher pupils relief"),
    N(B("VII"), "Look Within", "Dig within",
      "Look inside yourself. Within is the spring of all good, which never runs dry if you keep digging deeper.",
      "Look within; within is the fountain of all good.",
      "Look inside yourself; that's where all goodness comes from.", "Quiet reflection after a hard week rather than another distraction.",
      "Roman fountain"),
    N(B("VII"), "Few Things", "Happiness needs little",
      "Real happiness needs very few things. The more you need, the more you can lose.",
      "a man's true happiness doth consist in very few things",
      "True happiness requires very little.", "A picnic with good friends can beat an expensive restaurant.",
      "simple Roman meal fresco"),
    N(B("VII"), "Help Is Fine", "Ask for help",
      "Don't be ashamed to need help. A soldier storming a wall may need a hand up; what matters is that the wall is climbed.",
      "Be not therefore ashamed, whensoever thou must use the help of others.",
      "There's no shame in getting help.", "Asking a classmate to explain the maths you missed.",
      "Roman soldiers siege relief Trajan's Column"),
    N(B("VII"), "One Word at a Time", "One thing at a time",
      "Understand things one by one: each word spoken, each act done. Overwhelm comes from swallowing everything at once.",
      "Word after word, every one by itself, must the things that are spoken be conceived and understood",
      "Take in things one at a time.", "Reading one page carefully instead of skimming ten.",
      "Roman inscription stone letters"),
    N(B("VII"), "The Common Good", "Work for all",
      "What matters most in a person's nature is caring for the common good. We are made for each other, like hands and feet.",
      "That therefore which is chief in every man's constitution, is, that he intend the common good.",
      "Above all, people should aim at what's good for everyone.", "Picking up litter in a park you didn't drop.",
      "Roman aqueduct"),
    K(9),
    N(B("VIII"), "Starting Over", "You fell short; begin again",
      "Marcus admits he has often failed to live like a philosopher, as others well know. Instead of despair, he simply resolves to live by nature from now on.",
      "For both unto others, and to thyself especially, it is well known, that thou hast done many things contrary to that perfection of life.",
      "Everyone, including you, knows you've often fallen short.", "Admitting you broke your diet, then starting again at dinner.",
      "Marcus Aurelius sacrificing relief"),
    N(B("VIII"), "The Citadel", "A mind no one can storm",
      "A mind free from passions is a fortress. There is no stronger place for a person to retreat to and become unbeatable.",
      "A stronger place, (whereunto to make his refuge, and so to become impregnable) and better fortified than this, hath no man.",
      "No fortress is stronger than a calm mind.", "Staying calm under pressure when everyone else panics.",
      "Roman fortress walls"),
    N(B("VIII"), "Only the Facts", "Hurt is an added opinion",
      "Someone speaks badly of you: that's the report. That you are hurt by it is not reported; that's your own addition. Leave it out.",
      "But that thou art hurt thereby, is not reported: that is the addition of opinion, which thou must exclude.",
      "Feeling hurt is something you add to the facts.", "A bad review is just words; feeling crushed is your own extra step.",
      "Roman scroll reading"),
    N(B("VIII"), "Not Your Fault", "When it's not on you",
      "If something isn't done and it isn't your fault, don't grieve over it. Do what is yours, and let the rest go.",
      "Let it not grieve thee then, if it be not thy fault that the thing is not performed.",
      "Don't be upset over what wasn't your fault.", "A cancelled match because of rain isn't your failure.",
      "storm at sea painting Roman"),
    N(B("IX"), "Little Progress", "Even a little progress",
      "Marcus doesn't expect Plato's ideal republic. If people improve even a little, he is content and counts it a real gain.",
      "If they profit though never so little, I must be content; and think much even of that little progress.",
      "Be happy with even small improvements.", "Celebrating a child's first B after a string of Ds.",
      "Plato bust"),
    N(B("IX"), "Your Kinsman", "They are your family",
      "When someone wrongs you, remember they are your kin, a fellow human. You still have to love them; by nature they are your friends.",
      "Yet must thou love them still, for by nature they are thy friends.",
      "You must still love people who wrong you; we're all connected.", "Making peace with a cousin after a family argument.",
      "Roman family relief"),
    N(B("IX"), "The World Needs Them", "Such people must exist",
      "Meeting a shameless person, ask: can the world be without shameless people? No. Then this is one of them. Expecting otherwise is the mistake.",
      "For this one, (thou must think) whosoever he be, is one of those impudent ones, that the world cannot be without.",
      "Some rude people will always exist; this is one of them.", "Expecting no trolls online is the real error.",
      "Roman satyr mask"),
    N(B("IX"), "Instruct Them", "Show them better",
      "Is it not in your power to teach someone who is mistaken? Then do that instead of complaining.",
      "And generally, is it not in thy power to instruct him better, that is in an error?",
      "You can always try to correct someone kindly.", "Showing a new colleague the shortcut instead of mocking their slowness.",
      "Roman school scene"),
    N(B("IX"), "Look at Yourself", "Turn the blame inward",
      "When you blame someone for ingratitude or lying, look at yourself first: did you trust the wrong person, or give expecting a reward?",
      "But then especially, when thou dost find fault with either an unthankful, or a false man, must thou reflect upon thyself.",
      "When you blame others, check your own part first.", "Asking what you could have done differently after a group project fails.",
      "Roman mirror bronze"),
    N(B("X"), "O My Soul", "When will you be good?",
      "Marcus speaks to his own soul: when will you be good, simple and open, content with what you have, needing nothing from anyone?",
      "O my soul, the time I trust will be, when thou shalt be good, simple, single, more open and visible",
      "Someday, my soul, you'll be good, simple and open.", "A New Year's resolution to be more honest and less complicated.",
      "Marcus Aurelius statue"),
    N(B("X"), "Part of the Whole", "What's good for the whole",
      "Remember you are a part of a larger whole. Nothing that is good for the whole can really harm the part.",
      "For nothing that is behoveful unto the whole, can be truly hurtful to that which is part of it.",
      "What's good for the whole can't truly harm its parts.", "A player benched for the team's sake still shares the win.",
      "Pantheon Rome"),
    N(B("X"), "Principles Fade", "Principles fade slowly",
      "Bit by bit, if you don't watch out, your best principles will be erased from your mind. Keep them fresh by practice.",
      "By little and little, if thou doest not better look to it, those sacred dogmata will be blotted out of thy mind.",
      "Your principles can slowly fade if you don't keep them up.", "Skipping one workout, then another, until you've stopped.",
      "faded Roman fresco"),
    N(B("X"), "Ask the Best", "Ask the wise",
      "If you can see the right path, take it and don't be turned aside. If you can't, pause and ask the best people.",
      "But if alone thou doest not so well perceive it, suspend thine action, and take advice from the best.",
      "When unsure, stop and get advice from the wisest people.", "Asking an experienced doctor for a second opinion.",
      "Roman senate meeting painting"),
    N(B("X"), "A Good Eye", "A good eye sees everything",
      "A healthy eye sees all things, not only green ones. A healthy mind is ready for whatever happens, not only pleasant things.",
      "A good eye must be good to see whatsoever is to be seen, and not green things only.",
      "A healthy mind accepts all experiences, not just pleasant ones.", "Taking criticism as calmly as praise.",
      "Roman eye votive"),
    N(B("XI"), "False Friendship", "The worst thing",
      "Nothing is more shameful than false friendship. Avoid it above all. A good person's goodness should show in their eyes.",
      "There is nothing more shameful than perfidious friendship.",
      "Nothing is worse than a fake friendship.", "A friend who gossips about you behind your back.",
      "Judas kiss painting"),
    N(B("XI"), "One Aim", "One aim, one self",
      "A person without one constant aim in life cannot stay one consistent person. Choose your aim, and let it be the common good.",
      "He that hath not one and the self-same general end always as long as he liveth, cannot possibly be one and the self-same man always.",
      "Without one steady aim in life, you can't stay the same person.", "Someone who changes goals every month never gets far.",
      "Roman archer relief"),
    N(B("XI"), "Correct Gently", "Correct without scorn",
      "When you must correct someone, do it tenderly, without mockery or harsh words, as you would to a friend.",
      "But this thou must do, not scoffingly, not by way of exprobation, but tenderly without any harshness of words.",
      "Correct people gently, without mocking them.", "Pointing out a typo kindly rather than with a sarcastic comment.",
      "Roman mother and child relief"),
    N(B("XI"), "Learn to Live", "Life needs lessons",
      "You had to be taught to read and write. Living well needs even more teaching. Don't assume you know how.",
      "In matter of writing or reading thou must needs be taught before thou can do either: much more in matter of life.",
      "If reading needs teaching, living well needs it even more.", "Reading books about relationships, not just about careers.",
      "Roman writing tablet stylus"),
    N(B("XI"), "Nobody Errs on Purpose", "No one chooses to be wrong",
      "Following Plato, Marcus believes no soul goes wrong willingly. People who do wrong are mistaken, which calls for patience rather than hatred.",
      "For as, according to Plato's opinion, no soul doth willingly err",
      "No one wants to be wrong; people err from ignorance.", "A child who breaks a rule usually didn't understand it.",
      "Plato Academy mosaic"),
    N(B("XII"), "Others' Opinions", "Whose opinion counts?",
      "Marcus wonders why each person loves themself most yet values others' opinions of them more than their own.",
      "I have often wondered how it should come to pass, that every man loving himself best, should more regard other men's opinions concerning himself than his own.",
      "Strange that we love ourselves most yet care more what others think.", "Changing an outfit because of what strangers might think.",
      "Roman portrait busts row"),
    N(B("XII"), "Speak Your Thoughts", "If thoughts were spoken",
      "If we had to say out loud everything we think, no one could stand it for a day. We care more about others' views than our own, yet hide our thoughts from them.",
      "For if any God or grave master standing by, should command any of us to think nothing by himself but what he should presently speak out; no man were able to endure it, though but for one day.",
      "No one could bear to speak every thought out loud for a single day.", "Imagine your thoughts appearing as subtitles in a meeting.",
      "Roman orator statue"),
    N(B("XII"), "Something Divine", "Better than your passions",
      "It is time to realise there is something in you more divine than your passions and appetites, which pull you around like a puppet.",
      "It is high time for thee, to understand that there is somewhat in thee, better and more divine than either thy passions, or thy sensual appetites and affections.",
      "Something in you is greater than your desires.", "Choosing to finish a task instead of giving in to a craving.",
      "marionette puppet painting"),
    N(B("XII"), "Proud of Humility", "The worst pride",
      "The most unbearable pride is being proud of how humble you are.",
      "For, for a man to be proud and high conceited, that he is not proud and high conceited, is of all kind of pride and presumption, the most intolerable.",
      "Being proud of your humility is the worst pride.", "Someone who keeps mentioning how modest they are.",
      "Roman peacock mosaic"),
    N(B("XII"), "Three Acts", "Only three acts",
      "'But I have played only three acts!' Then for you the play is three acts. The one who wrote it decides its length. Leave the stage gracefully, as the one dismissing you is gracious.",
      "Oh, but the play is not yet at an end, there are but three acts yet acted of it?",
      "You may feel your life ended too soon, but its length isn't yours to decide.", "A good guest leaves a party graciously when it's time.",
      "Roman theatre Orange"),
]
