from deep_build import K, N

SRC = "tao"
TARGET = 40

P = ["Part One", "Part Two", "Part Three", "Part Four", "Part Five", "Part Six", "Part Seven", "Part Eight"]
BRIDGE = {
    P[1]: "Part One met the nameless Way and its first image, water. Part Two turns to emptiness and stillness.",
    P[2]: "Stillness lets things return to their roots. Part Three shows how bending and yielding make things whole.",
    P[3]: "Yielding is not weakness. Part Four is about how the soft overcomes the hard, even in war.",
    P[4]: "Lao Tzu now turns to the second half of his book, on Te, the power that comes from living the Way.",
    P[5]: "Contentment is real power. Part Six asks what that means for rulers.",
    P[6]: "The quiet ruler acts early and small. Part Seven is about great things done through small steps.",
    P[7]: "The book closes with its plainest words on knowledge, softness and sincerity.",
}

GLOSS = {
    "sage": ("A very wise person.", "Villagers went to the sage for advice.", ["sages"]),
    "moderation": ("Avoiding too much of anything.", "Eating sweets in moderation is fine.", []),
    "contentment": ("Being satisfied with what you have.", "She found contentment in small daily pleasures.", []),
}

def n(part, chap, title, text, quote, mean, life, pic):
    return N(P[part], f"Chapter {chap}", title, text, quote, mean, life, pic)

PAGES = [
    K(0, ch=P[0], chTitle="Chapter 1"),
    n(0, 2, "Beauty needs ugliness",
      "The moment everyone agrees what is beautiful, they also create the idea of ugly. Good and bad, hard and easy, long and short all exist only in relation to each other. So the sage doesn't cling to one side.",
      "All in the world know the beauty of the beautiful",
      "Calling something beautiful creates the idea of ugliness too.", "Calling one child 'the clever one' quietly labels the others.",
      "Chinese landscape Ma Yuan"),
    n(0, 4, "The empty bowl",
      "The Way is like an empty bowl that never needs filling. However much you draw from it, it never runs out, and it never overflows. Usefulness comes from emptiness, not fullness.",
      "The Tao is (like) the emptiness of a vessel",
      "The Way is like an empty bowl that is always useful.", "An open mind can take in more than a mind already full of opinions.",
      "Song dynasty ceramic bowl"),
    K(1, ch=P[0], chTitle="Chapter 7"), K(2, ch=P[0], chTitle="Chapter 8"), K(3, ch=P[0], chTitle="Chapter 9"),
    K(4, ch=P[1], chTitle="Chapter 11"),
    n(1, 13, "Praise and blame alike",
      "Being praised and being disgraced should both make us uneasy, because both tie us to other people's opinions. Care too much about honour and you will fear losing it.",
      "Favour and disgrace would seem equally to be feared",
      "Both praise and shame should be treated with caution.", "Someone who lives for likes is shaken by every bad comment.",
      "Chinese court official painting Ming"),
    n(1, 16, "Return to the root",
      "Make your mind as still as possible. Then you can watch all things rise, flourish and return to their roots. Returning to the root is peace.",
      "All things alike go through their processes of activity, and (then) we see them return (to their original state).",
      "Everything goes through its life and then returns to where it began.", "Leaves fall in autumn and feed the same tree in spring.",
      "Chinese painting tree roots"),
    n(1, 17, "The best leaders are barely noticed",
      "The best rulers are hardly known by their people. Next come those loved and praised, then those feared, then those despised. When the best leader's work is done, the people say: we did it ourselves.",
      "Their work was done and their undertakings were successful, while the people all said, 'We are as we are, of ourselves!'",
      "When good leaders succeed, people feel they did it themselves.", "A coach whose team believes the win was all theirs.",
      "Chinese village life scroll"),
    n(1, 18, "When the Way is lost",
      "Only when the great Way is forgotten do people start preaching kindness and duty. Rules appear when natural goodness is gone, and cleverness brings hypocrisy with it.",
      "When the Great Tao (Way or Method) ceased to be observed, benevolence and righteousness came into vogue.",
      "People talk about being good only once natural goodness is lost.", "Families that trust each other don't need written house rules.",
      "Confucius portrait"),
    n(2, 22, "Bend to be whole",
      "What is partial becomes complete; what is bent becomes straight; what is empty is filled. The sage doesn't show off, so he shines; doesn't boast, so he is respected.",
      "The partial becomes complete; the crooked, straight; the empty, full",
      "What seems incomplete or crooked can become whole and straight.", "A humble beginner often ends up the most skilled.",
      "bamboo in wind painting"),
    n(2, 23, "Storms don't last",
      "A whirlwind doesn't last all morning; a cloudburst doesn't last all day. If even heaven and earth can't keep up violent bursts, how could people?",
      "If Heaven and Earth cannot make such (spasmodic) actings last long, how much less can man!",
      "Nothing violent or sudden lasts long, especially for people.", "Crash diets end quickly; steady habits stay.",
      "Chinese storm painting"),
    n(2, 26, "Weight steadies the light",
      "Heaviness is the root of lightness; stillness rules over restlessness. A wise ruler, travelling all day, never leaves his supply wagons. Don't let showy prospects pull you from your base.",
      "Gravity is the root of lightness; stillness, the ruler of movement",
      "Seriousness grounds frivolity; calm controls restlessness.", "A calm parent keeps a hectic household steady.",
      "Chinese ox cart painting"),
    n(2, 27, "No tracks left",
      "A skilled traveller leaves no wheel ruts; a skilled speaker makes no slips. The sage is good at saving people, and so casts no one away.",
      "The skilful traveller leaves no traces of his wheels or footsteps",
      "True skill leaves no visible trace.", "A great editor's work is invisible in a smooth book.",
      "Chinese traveller mountain painting"),
    n(2, 29, "Grab it and lose it",
      "Whoever tries to seize the world and shape it to their will fails. The world is a sacred vessel; grasp it and you lose it.",
      "He who would so win it destroys it; he who would hold it in his grasp loses it.",
      "Trying to control everything destroys what you wanted.", "A controlling friend who loses the friendship by clinging.",
      "Chinese bronze ritual vessel"),
    n(3, 31, "Weapons are unlucky",
      "Even beautiful weapons are instruments of ill omen. The wise use them only when there is no choice, and mourn even a victory, because it was paid for in lives.",
      "Now arms, however beautiful, are instruments of evil omen",
      "Weapons, however fine, bring bad fortune.", "Winning a bitter argument can still cost a friendship.",
      "Chinese bronze sword"),
    K(5, ch=P[3], chTitle="Chapter 33"),
    n(3, 33, "Rich with enough",
      "Whoever is content with what they have is rich. Whoever keeps going with energy has a firm will. Whoever stays true to their place lasts long.",
      "He who is satisfied with his lot is rich",
      "Being satisfied with what you have is true wealth.", "Enjoying your old phone instead of craving the newest one.",
      "Chinese scholar garden painting"),
    n(3, 36, "Soft beats hard",
      "To shrink something, first let it expand; to weaken it, first let it grow strong. Lao Tzu's lesson: the soft overcomes the hard, the weak the strong.",
      "The soft overcomes the hard; and the weak the strong.",
      "Gentleness ends up beating force.", "A patient listener calms an angry customer better than an argument.",
      "Chinese waterfall painting"),
    n(3, 37, "Doing nothing, leaving nothing undone",
      "The Way never forces anything, yet nothing is left undone. If rulers could keep to it, everything would transform by itself.",
      "The Tao in its regular course does nothing (for the sake of doing it), and so there is nothing which it does not do.",
      "The Way doesn't force things, yet everything gets done.", "A good garden mostly grows itself if the soil is right.",
      "Chinese rice fields painting"),
    n(4, 41, "If they didn't laugh",
      "When the best scholars hear of the Way, they practise it. Average ones half believe. The worst laugh out loud. If they didn't laugh, it wouldn't be the Way.",
      "If it were not (thus) laughed at, it would not be fit to be the Tao.",
      "Deep truths often sound ridiculous to shallow minds.", "Great ideas are often mocked before they're accepted.",
      "Laughing Buddha painting"),
    n(4, 42, "Lose to gain",
      "Sometimes things grow by being reduced and shrink by being increased. The violent and strong rarely die a natural death.",
      "some things are increased by being diminished",
      "Giving something up can leave you with more.", "Saying no to some commitments gives you more time for what matters.",
      "Chinese pruned tree painting"),
    n(4, 46, "Enough is enough",
      "When the Way rules, war-horses pull manure carts on the farms. When it's lost, war-horses breed at the borders. Knowing when you have enough is the only lasting sufficiency.",
      "the sufficiency of contentment is an enduring and unchanging sufficiency",
      "Being content is the only 'enough' that lasts.", "Stopping eating when full instead of when the plate is empty.",
      "Chinese horses painting Han Gan"),
    n(4, 47, "Understand without going out",
      "Without leaving home you can understand the world; without looking out the window you can see the Way of heaven. The farther you go, the less you know.",
      "The farther that one goes out (from himself), the less he knows.",
      "Chasing far away often teaches less than looking within.", "Travelling the world won't fix what you avoid facing at home.",
      "Chinese scholar at window painting"),
    n(4, 49, "Good to all",
      "The sage is good to those who are good and also to those who are not, and so everyone becomes good. He trusts the trustworthy and the untrustworthy, and trust spreads.",
      "To those who are good (to me), I am good; and to those who are not good (to me), I am also good",
      "Be kind even to those who aren't kind to you.", "Greeting a grumpy neighbour warmly every morning.",
      "Chinese sage with children painting"),
    n(5, 55, "Strong means old",
      "A newborn is soft yet holds tight, cries all day without going hoarse. When things become hard and strong, they begin to age. Forcing strength is against the Way.",
      "When things have become strong, they (then) become old",
      "When things grow rigid and strong, they start to decline.", "A company that stops changing once it's big starts to fall behind.",
      "Chinese child painting"),
    K(6, ch=P[5], chTitle="Chapter 56"),
    n(5, 57, "Rule by doing less",
      "The more rules and bans, the poorer the people; the more weapons, the more chaos. The sage says: I do nothing on purpose, and the people change by themselves.",
      "I will do nothing (of purpose), and the people will be transformed of themselves",
      "If I don't force things, people improve on their own.", "Fewer pointless school rules can mean better behaviour.",
      "Chinese peaceful village painting"),
    n(5, 59, "Moderation",
      "For ruling people and serving heaven, nothing beats moderation. Holding back early builds up a reserve of strength that overcomes everything.",
      "there is nothing like moderation",
      "Nothing is better than moderation.", "Saving a little energy for the end of a long race.",
      "Chinese tea ceremony painting"),
    K(7, ch=P[5], chTitle="Chapter 60"),
    n(6, 63, "Great things, small steps",
      "Deal with the hard while it's easy; do great things while they're small. The sage never tries to do anything great, and so achieves greatness.",
      "Therefore the sage, while he never does what is great, is able on that account to accomplish the greatest things.",
      "By doing small things well, the wise achieve great things.", "Writing one page a day finishes a book.",
      "Chinese stone steps mountain painting"),
    n(6, 63, "Easy promises",
      "Someone who promises lightly rarely keeps faith; someone who thinks everything easy finds everything hard. The sage treats things as difficult, and so never meets difficulty.",
      "He who lightly promises is sure to keep but little faith",
      "People who promise easily often don't deliver.", "The friend who says yes to everything and turns up for nothing.",
      "Chinese scholars conversation painting"),
    K(8, ch=P[6], chTitle="Chapter 64"),
    n(6, 64, "Before it starts",
      "Act before things take shape; set order before disorder begins. A tree you can't wrap your arms around grew from a tiny shoot.",
      "Action should be taken before a thing has made its appearance; order should be secured before disorder has begun.",
      "Deal with problems before they appear.", "Fixing a small leak before it becomes a flood.",
      "Chinese pine tree painting"),
    n(6, 66, "The sea is lowest",
      "Rivers and seas rule a hundred valleys because they lie lower than them. The sage leads by putting himself below, and since he doesn't compete, no one can compete with him.",
      "Because he does not strive, no one finds it possible to strive with him.",
      "If you don't compete, no one can fight you.", "A humble expert people turn to instead of the loud rival.",
      "Chinese river delta painting"),
    n(6, 67, "Three treasures",
      "Lao Tzu holds three treasures: gentleness, frugality, and not daring to put himself first. Gentleness gives courage, frugality gives generosity, and humility makes a true leader.",
      "I have three precious things which I prize and hold fast",
      "I keep three treasures close: gentleness, simplicity and humility.", "A grandparent who is kind, careful with money and never brags.",
      "Lao Tzu riding ox painting"),
    n(7, 71, "Knowing you don't know",
      "To know and think you don't know is best. Not to know and think you know is a sickness. Only by recognising it as sickness can you be free of it.",
      "To know and yet (think) we do not know is the highest (attainment)",
      "The wisest know the limits of what they know.", "A doctor who says 'let's run another test' rather than guessing.",
      "Chinese scholar reading painting"),
    n(7, 73, "Heaven's net",
      "The net of heaven is wide and its holes are large, yet nothing slips through. Wrongdoing catches up in the end.",
      "The meshes of the net of Heaven are large; far apart, but letting nothing escape.",
      "Heaven's justice seems loose but nothing escapes it.", "A lie that seems safe eventually comes out.",
      "Chinese fishermen nets painting"),
    n(7, 76, "Supple and alive",
      "At birth we are soft and supple; at death, stiff and hard. Green plants bend; dead ones snap. Stiffness belongs to death, suppleness to life.",
      "Man at his birth is supple and weak; at his death, firm and strong",
      "Flexibility is a sign of life; rigidity of death.", "Stretching every morning to stay supple as you age.",
      "bamboo painting Chinese ink"),
    n(7, 78, "Knowing isn't doing",
      "Nothing is softer than water, yet nothing beats it at wearing away the hard. Everyone knows the soft overcomes the hard, but almost no one lives by it.",
      "Every one in the world knows that the soft overcomes the hard, and the weak the strong, but no one is able to carry it out in practice.",
      "Everyone knows gentleness wins, but few practise it.", "Knowing shouting won't help, and shouting anyway.",
      "Chinese waves painting"),
    n(7, 81, "Sincere words",
      "The book ends simply: sincere words aren't pretty, pretty words aren't sincere. The wise don't argue; those who argue aren't wise. The sage keeps nothing back, and the more he gives, the more he has.",
      "Sincere words are not fine; fine words are not sincere.",
      "True words are plain; fancy words are often false.", "A simple 'I'm sorry' means more than a long, polished excuse.",
      "Chinese calligraphy scroll"),
]
