from deep_build import K, N

SRC = "thinketh"
TARGET = 22

CH = "Thought and Character"
CI = "Effect of Thought on Circumstances"
HB = "Effect of Thought on Health and the Body"
PU = "Thought and Purpose"
AC = "The Thought-Factor in Achievement"
VI = "Visions and Ideals"
SE = "Serenity"

BRIDGE = {
    CI: "If character is built from thoughts, what about the world around us? Allen says circumstances grow from the same seed.",
    HB: "Thought shapes our surroundings. Next Allen turns inward, to the body itself.",
    PU: "A clean mind and a healthy body still drift without a direction. This chapter gives thought an aim.",
    AC: "With a purpose set, Allen asks what success really costs.",
    VI: "Achievement starts somewhere: in a dream. This chapter defends the dreamers.",
    SE: "The book ends where every effort should lead: a calm, steady mind.",
}

PAGES = [
    K(0, ch=CH),
    N(CH, None, "Seeds of action",
      "Every action grows from a thought, the way a plant grows from a seed. Even 'spontaneous' acts have a thought behind them.",
      "As the plant springs from, and could not be without, the seed, so every act of a man springs from the hidden seeds of thought",
      "Every action begins as a thought.", "Snapping at someone after brooding over a slight all day.",
      "acorn oak botanical illustration"),
    N(CH, None, "Character is not luck",
      "A good character isn't a gift of chance. It comes from steady effort and from keeping company with good thoughts for a long time.",
      "A noble and Godlike character is not a thing of favour or chance, but is the natural result of continued effort in right thinking",
      "Good character is built by practice, not luck.", "A patient nurse who became patient by choosing it daily.",
      "Millet The Sower"),
    K(1, ch=CI),
    N(CI, None, "Master-gardener",
      "By tending their thoughts, a person discovers they are the gardener of their own mind and the director of their life.",
      "a man sooner or later discovers that he is the master-gardener of his soul, the director of his life",
      "You are in charge of your own mind.", "Choosing which habits to grow and which to pull out.",
      "Monet garden painting"),
    K(2, ch=CI), K(3, ch=CI),
    N(CI, None, "Corn from corn",
      "Good thoughts and actions can't produce bad results, and bad ones can't produce good. You reap what you plant.",
      "Good thoughts and actions can never produce bad results; bad thoughts and actions can never produce good results.",
      "You reap what you sow.", "Steady revision produces good grades; cramming produces panic.",
      "wheat harvest painting"),
    N(CI, None, "The kaleidoscope",
      "The world keeps showing you new patterns, and each one mirrors your shifting thoughts.",
      "The world is your kaleidoscope, and the varying combinations of colours, which at every succeeding moment it presents to you are the exquisitely adjusted pictures of your ever-moving thoughts.",
      "How you see the world reflects how you think.", "On a good day traffic seems fine; on a bad day it's unbearable.",
      "stained glass rose window"),
    N(HB, None, "The body serves the mind",
      "The body follows the mind's orders, whether we choose them or not. Fear and worry show up in the body; calm and cheer do too.",
      "THE body is the servant of the mind.",
      "Your body follows your mind.", "Stomach knots before a big presentation.",
      "anatomical drawing Leonardo"),
    N(HB, None, "Pure at the source",
      "Thought is the spring that action and life flow from. Clean the spring and everything downstream runs clean.",
      "Thought is the fount of action, life, and manifestation; make the fountain pure, and all will be pure.",
      "Clean thoughts lead to a clean life.", "Dropping a grudge and sleeping better.",
      "mountain spring painting"),
    N(HB, None, "Like the setting sun",
      "Allen describes a woman of ninety-six with the bright face of a girl. For those who have lived well, old age is calm and soft.",
      "With those who have lived righteously, age is calm, peaceful, and softly mellowed, like the setting sun.",
      "A good life makes for a peaceful old age.", "A cheerful grandparent everyone loves to visit.",
      "Rembrandt old woman"),
    K(4, ch=PU),
    N(PU, None, "Thought needs a purpose",
      "Until thinking is tied to a goal, nothing intelligent gets done. Aimless drifting leads toward trouble.",
      "UNTIL thought is linked with purpose there is no intelligent accomplishment.",
      "Thinking without a goal achieves nothing.", "Months of 'wanting to get fit' versus signing up for a race.",
      "ship compass engraving"),
    N(PU, None, "Start with your duty",
      "If you can't yet see a big purpose, do your daily duty perfectly, however small. That builds focus and resolve.",
      "should fix the thoughts upon the faultless performance of their duty, no matter how insignificant their task may appear.",
      "Doing small tasks well prepares you for big ones.", "An intern who does every small job well and gets trusted with more.",
      "Vermeer The Milkmaid"),
    N(PU, None, "Doubt and fear",
      "Doubt and fear never got anything done. Conquer them and you've conquered failure.",
      "He who has conquered doubt and fear has conquered failure.",
      "Beat doubt and fear and you beat failure.", "Finally sending the job application you kept putting off.",
      "mountain climber painting"),
    N(AC, None, "Your own doing",
      "Everything a person achieves or fails to achieve comes from their own thoughts. Weakness and strength are theirs alone to change.",
      "ALL that a man achieves and all that he fails to achieve is the direct result of his own thoughts.",
      "Your results come from your own thinking.", "Owning a bad result instead of blaming the teacher.",
      "Rodin The Thinker"),
    N(AC, None, "Some sacrifice",
      "You don't have to give up every comfort to succeed, but you must give up some.",
      "but a portion of it must, at least, be sacrificed.",
      "Success needs some sacrifice.", "Skipping a few nights out to build a side project.",
      "blacksmith forge painting"),
    N(VI, None, "Dreamers save the world",
      "Dreamers are the world's saviours. Whoever holds a beautiful vision in their heart will one day realise it.",
      "He who cherishes a beautiful vision, a lofty ideal in his heart, will one day realize it.",
      "Hold onto a beautiful vision and you'll reach it.", "A child who dreams of flying and becomes a pilot.",
      "Wright brothers first flight"),
    N(VI, None, "You can't stand still",
      "Hard circumstances won't last if you see an ideal and strive for it. Growing inside means moving outside too.",
      "Your circumstances may be uncongenial, but they shall not long remain so if you but perceive an Ideal and strive to reach it.",
      "Aim for an ideal and your situation will change.", "A night-shift worker studying for a better job.",
      "factory workers painting nineteenth century"),
    N(VI, None, "Not luck: effort",
      "People see others' success and call it luck. They don't see the long struggle. The strength of the effort is the measure of the result.",
      "the strength of the effort is the measure of the result.",
      "Success comes from effort, not luck.", "An 'overnight' star who practised for ten years.",
      "Paganini portrait"),
    N(SE, None, "Calm earns trust",
      "A calm person who governs themself can adapt to others, and others come to rely on them. The calmer you are, the greater your influence.",
      "The more tranquil a man becomes, the greater is his success, his influence, his power for good.",
      "Calm people gain trust and influence.", "The team member everyone turns to in a crisis.",
      "Caspar David Friedrich sea"),
    K(5, ch=SE),
    N(SE, None, "Hand on the helm",
      "To anyone tossed by life's storms: a calm shore is waiting. Keep a firm hand on the helm of your thoughts.",
      "Keep your hand firmly upon the helm of thought.",
      "Steer your life by controlling your thoughts.", "Taking a breath before reacting to bad news.",
      "ship storm painting Aivazovsky"),
]
